/*
 * GENERATED by builder/stages/s1-evidence.mjs — DO NOT EDIT.
 * 212 permission URIs from GD-permissions.txt.
 */
import type { PermissionEvidence } from '../evidence-types';

export const gdPermissions: PermissionEvidence[] = [
  {
    "raw": "User.AaaAllowedActPermissions.Get",
    "scope": "User",
    "resource": "AaaAllowedActPermissions",
    "action": "Get"
  },
  {
    "raw": "User.AaaAppClients.Create",
    "scope": "User",
    "resource": "AaaAppClients",
    "action": "Create"
  },
  {
    "raw": "User.AaaAppClients.Delete",
    "scope": "User",
    "resource": "AaaAppClients",
    "action": "Delete"
  },
  {
    "raw": "User.AaaAppClients.Get",
    "scope": "User",
    "resource": "AaaAppClients",
    "action": "Get"
  },
  {
    "raw": "User.AaaAppClients.Update",
    "scope": "User",
    "resource": "AaaAppClients",
    "action": "Update"
  },
  {
    "raw": "User.AaaAppPermissionCheck.Get",
    "scope": "User",
    "resource": "AaaAppPermissionCheck",
    "action": "Get"
  },
  {
    "raw": "User.AaaAppPermissions.Create",
    "scope": "User",
    "resource": "AaaAppPermissions",
    "action": "Create"
  },
  {
    "raw": "User.AaaAppPermissions.Delete",
    "scope": "User",
    "resource": "AaaAppPermissions",
    "action": "Delete"
  },
  {
    "raw": "User.AaaAppPermissions.Get",
    "scope": "User",
    "resource": "AaaAppPermissions",
    "action": "Get"
  },
  {
    "raw": "User.AaaAppPermissions.Update",
    "scope": "User",
    "resource": "AaaAppPermissions",
    "action": "Update"
  },
  {
    "raw": "User.AaaAppTypePermissions.Create",
    "scope": "User",
    "resource": "AaaAppTypePermissions",
    "action": "Create"
  },
  {
    "raw": "User.AaaAppTypePermissions.Delete",
    "scope": "User",
    "resource": "AaaAppTypePermissions",
    "action": "Delete"
  },
  {
    "raw": "User.AaaAppTypePermissions.Get",
    "scope": "User",
    "resource": "AaaAppTypePermissions",
    "action": "Get"
  },
  {
    "raw": "User.AaaAppTypePermissions.Update",
    "scope": "User",
    "resource": "AaaAppTypePermissions",
    "action": "Update"
  },
  {
    "raw": "User.AaaAppTypes.Create",
    "scope": "User",
    "resource": "AaaAppTypes",
    "action": "Create"
  },
  {
    "raw": "User.AaaAppTypes.Delete",
    "scope": "User",
    "resource": "AaaAppTypes",
    "action": "Delete"
  },
  {
    "raw": "User.AaaAppTypes.Get",
    "scope": "User",
    "resource": "AaaAppTypes",
    "action": "Get"
  },
  {
    "raw": "User.AaaAppTypes.Update",
    "scope": "User",
    "resource": "AaaAppTypes",
    "action": "Update"
  },
  {
    "raw": "User.AaaEntityProfile.Create",
    "scope": "User",
    "resource": "AaaEntityProfile",
    "action": "Create"
  },
  {
    "raw": "User.AaaEntityProfile.Delete",
    "scope": "User",
    "resource": "AaaEntityProfile",
    "action": "Delete"
  },
  {
    "raw": "User.AaaEntityProfile.Get",
    "scope": "User",
    "resource": "AaaEntityProfile",
    "action": "Get"
  },
  {
    "raw": "User.AaaEntityProfile.Update",
    "scope": "User",
    "resource": "AaaEntityProfile",
    "action": "Update"
  },
  {
    "raw": "User.AaaEntityRolePermissions.Create",
    "scope": "User",
    "resource": "AaaEntityRolePermissions",
    "action": "Create"
  },
  {
    "raw": "User.AaaEntityRolePermissions.Delete",
    "scope": "User",
    "resource": "AaaEntityRolePermissions",
    "action": "Delete"
  },
  {
    "raw": "User.AaaEntityRolePermissions.Get",
    "scope": "User",
    "resource": "AaaEntityRolePermissions",
    "action": "Get"
  },
  {
    "raw": "User.AaaEntityRolePermissions.Update",
    "scope": "User",
    "resource": "AaaEntityRolePermissions",
    "action": "Update"
  },
  {
    "raw": "User.AaaEntityRoles.Create",
    "scope": "User",
    "resource": "AaaEntityRoles",
    "action": "Create"
  },
  {
    "raw": "User.AaaEntityRoles.Delete",
    "scope": "User",
    "resource": "AaaEntityRoles",
    "action": "Delete"
  },
  {
    "raw": "User.AaaEntityRoles.Get",
    "scope": "User",
    "resource": "AaaEntityRoles",
    "action": "Get"
  },
  {
    "raw": "User.AaaEntityRoles.Update",
    "scope": "User",
    "resource": "AaaEntityRoles",
    "action": "Update"
  },
  {
    "raw": "User.AaaEntityScenarios.Create",
    "scope": "User",
    "resource": "AaaEntityScenarios",
    "action": "Create"
  },
  {
    "raw": "User.AaaEntityScenarios.Delete",
    "scope": "User",
    "resource": "AaaEntityScenarios",
    "action": "Delete"
  },
  {
    "raw": "User.AaaEntityScenarios.Get",
    "scope": "User",
    "resource": "AaaEntityScenarios",
    "action": "Get"
  },
  {
    "raw": "User.AaaEntityScenarios.Update",
    "scope": "User",
    "resource": "AaaEntityScenarios",
    "action": "Update"
  },
  {
    "raw": "User.AaaPermissions.Create",
    "scope": "User",
    "resource": "AaaPermissions",
    "action": "Create"
  },
  {
    "raw": "User.AaaPermissions.Delete",
    "scope": "User",
    "resource": "AaaPermissions",
    "action": "Delete"
  },
  {
    "raw": "User.AaaPermissions.Get",
    "scope": "User",
    "resource": "AaaPermissions",
    "action": "Get"
  },
  {
    "raw": "User.AaaPermissions.Update",
    "scope": "User",
    "resource": "AaaPermissions",
    "action": "Update"
  },
  {
    "raw": "User.AaaRestrictedUserInfo.Get",
    "scope": "User",
    "resource": "AaaRestrictedUserInfo",
    "action": "Get"
  },
  {
    "raw": "User.AaaScenarioDataMap.Create",
    "scope": "User",
    "resource": "AaaScenarioDataMap",
    "action": "Create"
  },
  {
    "raw": "User.AaaScenarioDataMap.Delete",
    "scope": "User",
    "resource": "AaaScenarioDataMap",
    "action": "Delete"
  },
  {
    "raw": "User.AaaScenarioDataMap.Get",
    "scope": "User",
    "resource": "AaaScenarioDataMap",
    "action": "Get"
  },
  {
    "raw": "User.AaaScenarioDataMap.Update",
    "scope": "User",
    "resource": "AaaScenarioDataMap",
    "action": "Update"
  },
  {
    "raw": "User.AaaScenarioDetails.Get",
    "scope": "User",
    "resource": "AaaScenarioDetails",
    "action": "Get"
  },
  {
    "raw": "User.AaaScenarios.Create",
    "scope": "User",
    "resource": "AaaScenarios",
    "action": "Create"
  },
  {
    "raw": "User.AaaScenarios.Delete",
    "scope": "User",
    "resource": "AaaScenarios",
    "action": "Delete"
  },
  {
    "raw": "User.AaaScenarios.Get",
    "scope": "User",
    "resource": "AaaScenarios",
    "action": "Get"
  },
  {
    "raw": "User.AaaScenarios.Update",
    "scope": "User",
    "resource": "AaaScenarios",
    "action": "Update"
  },
  {
    "raw": "User.AaaTableAuditConfigs.Create",
    "scope": "User",
    "resource": "AaaTableAuditConfigs",
    "action": "Create"
  },
  {
    "raw": "User.AaaTableAuditConfigs.Delete",
    "scope": "User",
    "resource": "AaaTableAuditConfigs",
    "action": "Delete"
  },
  {
    "raw": "User.AaaTableAuditConfigs.Get",
    "scope": "User",
    "resource": "AaaTableAuditConfigs",
    "action": "Get"
  },
  {
    "raw": "User.AaaTableAuditConfigs.Update",
    "scope": "User",
    "resource": "AaaTableAuditConfigs",
    "action": "Update"
  },
  {
    "raw": "User.AaaTableAudits.Create",
    "scope": "User",
    "resource": "AaaTableAudits",
    "action": "Create"
  },
  {
    "raw": "User.AaaTableAudits.Delete",
    "scope": "User",
    "resource": "AaaTableAudits",
    "action": "Delete"
  },
  {
    "raw": "User.AaaTableAudits.Get",
    "scope": "User",
    "resource": "AaaTableAudits",
    "action": "Get"
  },
  {
    "raw": "User.AaaTableAudits.Update",
    "scope": "User",
    "resource": "AaaTableAudits",
    "action": "Update"
  },
  {
    "raw": "User.AaaUserEntityProfileCheck.Get",
    "scope": "User",
    "resource": "AaaUserEntityProfileCheck",
    "action": "Get"
  },
  {
    "raw": "User.AaaUserEntityRoleCheck.Get",
    "scope": "User",
    "resource": "AaaUserEntityRoleCheck",
    "action": "Get"
  },
  {
    "raw": "User.AaaUserEntityRoles.Create",
    "scope": "User",
    "resource": "AaaUserEntityRoles",
    "action": "Create"
  },
  {
    "raw": "User.AaaUserEntityRoles.Delete",
    "scope": "User",
    "resource": "AaaUserEntityRoles",
    "action": "Delete"
  },
  {
    "raw": "User.AaaUserEntityRoles.Get",
    "scope": "User",
    "resource": "AaaUserEntityRoles",
    "action": "Get"
  },
  {
    "raw": "User.AaaUserEntityRoles.Update",
    "scope": "User",
    "resource": "AaaUserEntityRoles",
    "action": "Update"
  },
  {
    "raw": "User.AaaUserInfo.Get",
    "scope": "User",
    "resource": "AaaUserInfo",
    "action": "Get"
  },
  {
    "raw": "User.AaaUserInfo.Invite",
    "scope": "User",
    "resource": "AaaUserInfo",
    "action": "Invite"
  },
  {
    "raw": "User.AaaUserPermissionCheck.Get",
    "scope": "User",
    "resource": "AaaUserPermissionCheck",
    "action": "Get"
  },
  {
    "raw": "User.AaaUserProfile.Create",
    "scope": "User",
    "resource": "AaaUserProfile",
    "action": "Create"
  },
  {
    "raw": "User.AaaUserProfile.Delete",
    "scope": "User",
    "resource": "AaaUserProfile",
    "action": "Delete"
  },
  {
    "raw": "User.AaaUserProfile.Get",
    "scope": "User",
    "resource": "AaaUserProfile",
    "action": "Get"
  },
  {
    "raw": "User.AaaUserProfile.Update",
    "scope": "User",
    "resource": "AaaUserProfile",
    "action": "Update"
  },
  {
    "raw": "User.ActorVersions.Create",
    "scope": "User",
    "resource": "ActorVersions",
    "action": "Create"
  },
  {
    "raw": "User.ActorVersions.Delete",
    "scope": "User",
    "resource": "ActorVersions",
    "action": "Delete"
  },
  {
    "raw": "User.ActorVersions.Get",
    "scope": "User",
    "resource": "ActorVersions",
    "action": "Get"
  },
  {
    "raw": "User.ActorVersions.Update",
    "scope": "User",
    "resource": "ActorVersions",
    "action": "Update"
  },
  {
    "raw": "User.AppConfigs.Create",
    "scope": "User",
    "resource": "AppConfigs",
    "action": "Create"
  },
  {
    "raw": "User.AppConfigs.Delete",
    "scope": "User",
    "resource": "AppConfigs",
    "action": "Delete"
  },
  {
    "raw": "User.AppConfigs.Get",
    "scope": "User",
    "resource": "AppConfigs",
    "action": "Get"
  },
  {
    "raw": "User.AppConfigs.Update",
    "scope": "User",
    "resource": "AppConfigs",
    "action": "Update"
  },
  {
    "raw": "User.CfgActionConfigBases.Create",
    "scope": "User",
    "resource": "CfgActionConfigBases",
    "action": "Create"
  },
  {
    "raw": "User.CfgActionConfigBases.Delete",
    "scope": "User",
    "resource": "CfgActionConfigBases",
    "action": "Delete"
  },
  {
    "raw": "User.CfgActionConfigBases.Get",
    "scope": "User",
    "resource": "CfgActionConfigBases",
    "action": "Get"
  },
  {
    "raw": "User.CfgActionConfigBases.Update",
    "scope": "User",
    "resource": "CfgActionConfigBases",
    "action": "Update"
  },
  {
    "raw": "User.CfgEntityConfigs.Create",
    "scope": "User",
    "resource": "CfgEntityConfigs",
    "action": "Create"
  },
  {
    "raw": "User.CfgEntityConfigs.Delete",
    "scope": "User",
    "resource": "CfgEntityConfigs",
    "action": "Delete"
  },
  {
    "raw": "User.CfgEntityConfigs.Get",
    "scope": "User",
    "resource": "CfgEntityConfigs",
    "action": "Get"
  },
  {
    "raw": "User.CfgEntityConfigs.Update",
    "scope": "User",
    "resource": "CfgEntityConfigs",
    "action": "Update"
  },
  {
    "raw": "User.CfgGlobalConfigs.Create",
    "scope": "User",
    "resource": "CfgGlobalConfigs",
    "action": "Create"
  },
  {
    "raw": "User.CfgGlobalConfigs.Delete",
    "scope": "User",
    "resource": "CfgGlobalConfigs",
    "action": "Delete"
  },
  {
    "raw": "User.CfgGlobalConfigs.Get",
    "scope": "User",
    "resource": "CfgGlobalConfigs",
    "action": "Get"
  },
  {
    "raw": "User.CfgGlobalConfigs.Update",
    "scope": "User",
    "resource": "CfgGlobalConfigs",
    "action": "Update"
  },
  {
    "raw": "User.ComponentChildren.Create",
    "scope": "User",
    "resource": "ComponentChildren",
    "action": "Create"
  },
  {
    "raw": "User.ComponentChildren.Delete",
    "scope": "User",
    "resource": "ComponentChildren",
    "action": "Delete"
  },
  {
    "raw": "User.ComponentChildren.Get",
    "scope": "User",
    "resource": "ComponentChildren",
    "action": "Get"
  },
  {
    "raw": "User.ComponentChildren.Update",
    "scope": "User",
    "resource": "ComponentChildren",
    "action": "Update"
  },
  {
    "raw": "User.Components.Get",
    "scope": "User",
    "resource": "Components",
    "action": "Get"
  },
  {
    "raw": "User.ComponentsBases.Create",
    "scope": "User",
    "resource": "ComponentsBases",
    "action": "Create"
  },
  {
    "raw": "User.ComponentsBases.Delete",
    "scope": "User",
    "resource": "ComponentsBases",
    "action": "Delete"
  },
  {
    "raw": "User.ComponentsBases.Get",
    "scope": "User",
    "resource": "ComponentsBases",
    "action": "Get"
  },
  {
    "raw": "User.ComponentsBases.Update",
    "scope": "User",
    "resource": "ComponentsBases",
    "action": "Update"
  },
  {
    "raw": "User.Cvodrivers.Create",
    "scope": "User",
    "resource": "Cvodrivers",
    "action": "Create"
  },
  {
    "raw": "User.Cvodrivers.Delete",
    "scope": "User",
    "resource": "Cvodrivers",
    "action": "Delete"
  },
  {
    "raw": "User.Cvodrivers.Get",
    "scope": "User",
    "resource": "Cvodrivers",
    "action": "Get"
  },
  {
    "raw": "User.Cvodrivers.Update",
    "scope": "User",
    "resource": "Cvodrivers",
    "action": "Update"
  },
  {
    "raw": "User.Cvos.Create",
    "scope": "User",
    "resource": "Cvos",
    "action": "Create"
  },
  {
    "raw": "User.Cvos.Delete",
    "scope": "User",
    "resource": "Cvos",
    "action": "Delete"
  },
  {
    "raw": "User.Cvos.Get",
    "scope": "User",
    "resource": "Cvos",
    "action": "Get"
  },
  {
    "raw": "User.Cvos.Update",
    "scope": "User",
    "resource": "Cvos",
    "action": "Update"
  },
  {
    "raw": "User.Cvoservices.Create",
    "scope": "User",
    "resource": "Cvoservices",
    "action": "Create"
  },
  {
    "raw": "User.Cvoservices.Delete",
    "scope": "User",
    "resource": "Cvoservices",
    "action": "Delete"
  },
  {
    "raw": "User.Cvoservices.Get",
    "scope": "User",
    "resource": "Cvoservices",
    "action": "Get"
  },
  {
    "raw": "User.Cvoservices.Update",
    "scope": "User",
    "resource": "Cvoservices",
    "action": "Update"
  },
  {
    "raw": "User.Cvovehicles.Create",
    "scope": "User",
    "resource": "Cvovehicles",
    "action": "Create"
  },
  {
    "raw": "User.Cvovehicles.Delete",
    "scope": "User",
    "resource": "Cvovehicles",
    "action": "Delete"
  },
  {
    "raw": "User.Cvovehicles.Get",
    "scope": "User",
    "resource": "Cvovehicles",
    "action": "Get"
  },
  {
    "raw": "User.Cvovehicles.Update",
    "scope": "User",
    "resource": "Cvovehicles",
    "action": "Update"
  },
  {
    "raw": "User.DataGateway.Get",
    "scope": "User",
    "resource": "DataGateway",
    "action": "Get"
  },
  {
    "raw": "User.DistributorCvos.Create",
    "scope": "User",
    "resource": "DistributorCvos",
    "action": "Create"
  },
  {
    "raw": "User.DistributorCvos.Delete",
    "scope": "User",
    "resource": "DistributorCvos",
    "action": "Delete"
  },
  {
    "raw": "User.DistributorCvos.Get",
    "scope": "User",
    "resource": "DistributorCvos",
    "action": "Get"
  },
  {
    "raw": "User.DistributorCvos.Update",
    "scope": "User",
    "resource": "DistributorCvos",
    "action": "Update"
  },
  {
    "raw": "User.DistributorDrivers.Create",
    "scope": "User",
    "resource": "DistributorDrivers",
    "action": "Create"
  },
  {
    "raw": "User.DistributorDrivers.Delete",
    "scope": "User",
    "resource": "DistributorDrivers",
    "action": "Delete"
  },
  {
    "raw": "User.DistributorDrivers.Get",
    "scope": "User",
    "resource": "DistributorDrivers",
    "action": "Get"
  },
  {
    "raw": "User.DistributorDrivers.Update",
    "scope": "User",
    "resource": "DistributorDrivers",
    "action": "Update"
  },
  {
    "raw": "User.Distributors.Create",
    "scope": "User",
    "resource": "Distributors",
    "action": "Create"
  },
  {
    "raw": "User.Distributors.Delete",
    "scope": "User",
    "resource": "Distributors",
    "action": "Delete"
  },
  {
    "raw": "User.Distributors.Get",
    "scope": "User",
    "resource": "Distributors",
    "action": "Get"
  },
  {
    "raw": "User.Distributors.Update",
    "scope": "User",
    "resource": "Distributors",
    "action": "Update"
  },
  {
    "raw": "User.DriverPermitVehicleTypes.Create",
    "scope": "User",
    "resource": "DriverPermitVehicleTypes",
    "action": "Create"
  },
  {
    "raw": "User.DriverPermitVehicleTypes.Delete",
    "scope": "User",
    "resource": "DriverPermitVehicleTypes",
    "action": "Delete"
  },
  {
    "raw": "User.DriverPermitVehicleTypes.Get",
    "scope": "User",
    "resource": "DriverPermitVehicleTypes",
    "action": "Get"
  },
  {
    "raw": "User.DriverPermitVehicleTypes.Update",
    "scope": "User",
    "resource": "DriverPermitVehicleTypes",
    "action": "Update"
  },
  {
    "raw": "User.Drivers.Create",
    "scope": "User",
    "resource": "Drivers",
    "action": "Create"
  },
  {
    "raw": "User.Drivers.Delete",
    "scope": "User",
    "resource": "Drivers",
    "action": "Delete"
  },
  {
    "raw": "User.Drivers.Get",
    "scope": "User",
    "resource": "Drivers",
    "action": "Get"
  },
  {
    "raw": "User.Drivers.Update",
    "scope": "User",
    "resource": "Drivers",
    "action": "Update"
  },
  {
    "raw": "User.DynamicPages.Get",
    "scope": "User",
    "resource": "DynamicPages",
    "action": "Get"
  },
  {
    "raw": "User.EnumActivityClasses.Get",
    "scope": "User",
    "resource": "EnumActivityClasses",
    "action": "Get"
  },
  {
    "raw": "User.EnumActors.Get",
    "scope": "User",
    "resource": "EnumActors",
    "action": "Get"
  },
  {
    "raw": "User.EnumActorsSorts.Get",
    "scope": "User",
    "resource": "EnumActorsSorts",
    "action": "Get"
  },
  {
    "raw": "User.EnumDataSourceTypes.Get",
    "scope": "User",
    "resource": "EnumDataSourceTypes",
    "action": "Get"
  },
  {
    "raw": "User.EnumRequestStatuses.Get",
    "scope": "User",
    "resource": "EnumRequestStatuses",
    "action": "Get"
  },
  {
    "raw": "User.EnumRequestTypes.Get",
    "scope": "User",
    "resource": "EnumRequestTypes",
    "action": "Get"
  },
  {
    "raw": "User.EnumServiceCategories.Get",
    "scope": "User",
    "resource": "EnumServiceCategories",
    "action": "Get"
  },
  {
    "raw": "User.EnumServiceClasses.Get",
    "scope": "User",
    "resource": "EnumServiceClasses",
    "action": "Get"
  },
  {
    "raw": "User.EnumVehicleTypes.Get",
    "scope": "User",
    "resource": "EnumVehicleTypes",
    "action": "Get"
  },
  {
    "raw": "User.Features.Create",
    "scope": "User",
    "resource": "Features",
    "action": "Create"
  },
  {
    "raw": "User.Features.Delete",
    "scope": "User",
    "resource": "Features",
    "action": "Delete"
  },
  {
    "raw": "User.Features.Get",
    "scope": "User",
    "resource": "Features",
    "action": "Get"
  },
  {
    "raw": "User.Features.Update",
    "scope": "User",
    "resource": "Features",
    "action": "Update"
  },
  {
    "raw": "User.Hubdistributors.Create",
    "scope": "User",
    "resource": "Hubdistributors",
    "action": "Create"
  },
  {
    "raw": "User.Hubdistributors.Delete",
    "scope": "User",
    "resource": "Hubdistributors",
    "action": "Delete"
  },
  {
    "raw": "User.Hubdistributors.Get",
    "scope": "User",
    "resource": "Hubdistributors",
    "action": "Get"
  },
  {
    "raw": "User.Hubdistributors.Update",
    "scope": "User",
    "resource": "Hubdistributors",
    "action": "Update"
  },
  {
    "raw": "User.Hubs.Create",
    "scope": "User",
    "resource": "Hubs",
    "action": "Create"
  },
  {
    "raw": "User.Hubs.Delete",
    "scope": "User",
    "resource": "Hubs",
    "action": "Delete"
  },
  {
    "raw": "User.Hubs.Get",
    "scope": "User",
    "resource": "Hubs",
    "action": "Get"
  },
  {
    "raw": "User.Hubs.Update",
    "scope": "User",
    "resource": "Hubs",
    "action": "Update"
  },
  {
    "raw": "User.KeyResolver.Get",
    "scope": "User",
    "resource": "KeyResolver",
    "action": "Get"
  },
  {
    "raw": "User.MasterServices.Create",
    "scope": "User",
    "resource": "MasterServices",
    "action": "Create"
  },
  {
    "raw": "User.MasterServices.Delete",
    "scope": "User",
    "resource": "MasterServices",
    "action": "Delete"
  },
  {
    "raw": "User.MasterServices.Get",
    "scope": "User",
    "resource": "MasterServices",
    "action": "Get"
  },
  {
    "raw": "User.MasterServices.Update",
    "scope": "User",
    "resource": "MasterServices",
    "action": "Update"
  },
  {
    "raw": "User.PermitIssuers.Create",
    "scope": "User",
    "resource": "PermitIssuers",
    "action": "Create"
  },
  {
    "raw": "User.PermitIssuers.Delete",
    "scope": "User",
    "resource": "PermitIssuers",
    "action": "Delete"
  },
  {
    "raw": "User.PermitIssuers.Get",
    "scope": "User",
    "resource": "PermitIssuers",
    "action": "Get"
  },
  {
    "raw": "User.PermitIssuers.Update",
    "scope": "User",
    "resource": "PermitIssuers",
    "action": "Update"
  },
  {
    "raw": "User.Permits.Create",
    "scope": "User",
    "resource": "Permits",
    "action": "Create"
  },
  {
    "raw": "User.Permits.Delete",
    "scope": "User",
    "resource": "Permits",
    "action": "Delete"
  },
  {
    "raw": "User.Permits.Get",
    "scope": "User",
    "resource": "Permits",
    "action": "Get"
  },
  {
    "raw": "User.Permits.Update",
    "scope": "User",
    "resource": "Permits",
    "action": "Update"
  },
  {
    "raw": "User.PermitStatusCheck.Get",
    "scope": "User",
    "resource": "PermitStatusCheck",
    "action": "Get"
  },
  {
    "raw": "User.PermitStatuses.Create",
    "scope": "User",
    "resource": "PermitStatuses",
    "action": "Create"
  },
  {
    "raw": "User.PermitStatuses.Delete",
    "scope": "User",
    "resource": "PermitStatuses",
    "action": "Delete"
  },
  {
    "raw": "User.PermitStatuses.Get",
    "scope": "User",
    "resource": "PermitStatuses",
    "action": "Get"
  },
  {
    "raw": "User.PermitStatuses.Update",
    "scope": "User",
    "resource": "PermitStatuses",
    "action": "Update"
  },
  {
    "raw": "User.PermitStatusVerifications.Create",
    "scope": "User",
    "resource": "PermitStatusVerifications",
    "action": "Create"
  },
  {
    "raw": "User.PermitStatusVerifications.Delete",
    "scope": "User",
    "resource": "PermitStatusVerifications",
    "action": "Delete"
  },
  {
    "raw": "User.PermitStatusVerifications.Get",
    "scope": "User",
    "resource": "PermitStatusVerifications",
    "action": "Get"
  },
  {
    "raw": "User.PermitStatusVerifications.Update",
    "scope": "User",
    "resource": "PermitStatusVerifications",
    "action": "Update"
  },
  {
    "raw": "User.PermitTypeIssuers.Create",
    "scope": "User",
    "resource": "PermitTypeIssuers",
    "action": "Create"
  },
  {
    "raw": "User.PermitTypeIssuers.Delete",
    "scope": "User",
    "resource": "PermitTypeIssuers",
    "action": "Delete"
  },
  {
    "raw": "User.PermitTypeIssuers.Get",
    "scope": "User",
    "resource": "PermitTypeIssuers",
    "action": "Get"
  },
  {
    "raw": "User.PermitTypeIssuers.Update",
    "scope": "User",
    "resource": "PermitTypeIssuers",
    "action": "Update"
  },
  {
    "raw": "User.PermitTypes.Create",
    "scope": "User",
    "resource": "PermitTypes",
    "action": "Create"
  },
  {
    "raw": "User.PermitTypes.Delete",
    "scope": "User",
    "resource": "PermitTypes",
    "action": "Delete"
  },
  {
    "raw": "User.PermitTypes.Get",
    "scope": "User",
    "resource": "PermitTypes",
    "action": "Get"
  },
  {
    "raw": "User.PermitTypes.Update",
    "scope": "User",
    "resource": "PermitTypes",
    "action": "Update"
  },
  {
    "raw": "User.RequestBases.Create",
    "scope": "User",
    "resource": "RequestBases",
    "action": "Create"
  },
  {
    "raw": "User.RequestBases.Delete",
    "scope": "User",
    "resource": "RequestBases",
    "action": "Delete"
  },
  {
    "raw": "User.RequestBases.Get",
    "scope": "User",
    "resource": "RequestBases",
    "action": "Get"
  },
  {
    "raw": "User.RequestBases.Update",
    "scope": "User",
    "resource": "RequestBases",
    "action": "Update"
  },
  {
    "raw": "User.RequestStatusCheck.Get",
    "scope": "User",
    "resource": "RequestStatusCheck",
    "action": "Get"
  },
  {
    "raw": "User.RequestStatuses.Create",
    "scope": "User",
    "resource": "RequestStatuses",
    "action": "Create"
  },
  {
    "raw": "User.RequestStatuses.Delete",
    "scope": "User",
    "resource": "RequestStatuses",
    "action": "Delete"
  },
  {
    "raw": "User.RequestStatuses.Get",
    "scope": "User",
    "resource": "RequestStatuses",
    "action": "Get"
  },
  {
    "raw": "User.RequestStatuses.Update",
    "scope": "User",
    "resource": "RequestStatuses",
    "action": "Update"
  },
  {
    "raw": "User.ServiceBases.Create",
    "scope": "User",
    "resource": "ServiceBases",
    "action": "Create"
  },
  {
    "raw": "User.ServiceBases.Delete",
    "scope": "User",
    "resource": "ServiceBases",
    "action": "Delete"
  },
  {
    "raw": "User.ServiceBases.Get",
    "scope": "User",
    "resource": "ServiceBases",
    "action": "Get"
  },
  {
    "raw": "User.ServiceBases.Update",
    "scope": "User",
    "resource": "ServiceBases",
    "action": "Update"
  },
  {
    "raw": "User.VehicleDrivers.Create",
    "scope": "User",
    "resource": "VehicleDrivers",
    "action": "Create"
  },
  {
    "raw": "User.VehicleDrivers.Delete",
    "scope": "User",
    "resource": "VehicleDrivers",
    "action": "Delete"
  },
  {
    "raw": "User.VehicleDrivers.Get",
    "scope": "User",
    "resource": "VehicleDrivers",
    "action": "Get"
  },
  {
    "raw": "User.VehicleDrivers.Update",
    "scope": "User",
    "resource": "VehicleDrivers",
    "action": "Update"
  },
  {
    "raw": "User.VehicleFeatures.Create",
    "scope": "User",
    "resource": "VehicleFeatures",
    "action": "Create"
  },
  {
    "raw": "User.VehicleFeatures.Delete",
    "scope": "User",
    "resource": "VehicleFeatures",
    "action": "Delete"
  },
  {
    "raw": "User.VehicleFeatures.Get",
    "scope": "User",
    "resource": "VehicleFeatures",
    "action": "Get"
  },
  {
    "raw": "User.VehicleFeatures.Update",
    "scope": "User",
    "resource": "VehicleFeatures",
    "action": "Update"
  },
  {
    "raw": "User.VehicleProfile.Create",
    "scope": "User",
    "resource": "VehicleProfile",
    "action": "Create"
  },
  {
    "raw": "User.VehicleProfile.Delete",
    "scope": "User",
    "resource": "VehicleProfile",
    "action": "Delete"
  },
  {
    "raw": "User.VehicleProfile.Get",
    "scope": "User",
    "resource": "VehicleProfile",
    "action": "Get"
  },
  {
    "raw": "User.VehicleProfile.Update",
    "scope": "User",
    "resource": "VehicleProfile",
    "action": "Update"
  }
];
