/*
 * GENERATED by builder/stages/s1-evidence.mjs — DO NOT EDIT.
 * Per-backend permission catalog manifest (static dumps; SSOT).
 */
import type { PermissionSourceManifest } from '../evidence-types';

export const permissionManifest: PermissionSourceManifest[] = [
  {
    "source": "gd",
    "sourceFile": "GD-permissions.txt",
    "sha256": "2c4170f2bef97d37b5ec050b02fbf1a645e92a86afd7ab4095561235e42515c8",
    "capturedAt": "2026-06-23",
    "permissionCount": 212
  },
  {
    "source": "ntf",
    "sourceFile": "Notification-permissions.txt",
    "sha256": "add32a470c4d35547bf46454512000f02668e3ec3c2dba4af2ecdf990f7ef1dd",
    "capturedAt": "2026-06-23",
    "permissionCount": 114
  },
  {
    "source": "core",
    "sourceFile": "core-permissions.txt",
    "sha256": "15a5bea3326d463a16ff0a256034bcc90377c7e4d665528a8a56a9af7e61d4bc",
    "capturedAt": "2026-06-23",
    "permissionCount": 291
  }
];
