-- GENERATED by builder/stages/s4-spc-emit.mjs — DO NOT EDIT.
-- 100 views emitted (ListSummary + Profile), 1 tab/tray stubbed, 0 skipped (no evidence).
-- Field rules: _fsx verbatim · ENUM ints raw (grid maps) · own-FK label hydration · per-relationship counts.
-- Idempotent: safe to re-run.

-- ===== definitions.access.entities (H_AAA_EntityProfile) =====
DROP VIEW IF EXISTS Vi_SPC_EntityListSummary;
CREATE OR REPLACE VIEW Vi_SPC_EntityListSummary AS
SELECT
m.Id,
m.PartyCode,
m.Title,
m.Address_fsx,
m.City,
m.Province,
m.Country,
m.PostalCode_fsx,
m.Phone_fsx,
m.FaxNumber_fsx,
m.Email_fsx,
m.Discriminator,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_AAA_EntityProfile m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_EntityProfile;
CREATE OR REPLACE VIEW Vi_SPC_EntityProfile AS
SELECT
m.Id,
m.PartyCode,
m.Title,
m.Address_fsx,
m.City,
m.Province,
m.Country,
m.PostalCode_fsx,
m.Phone_fsx,
m.FaxNumber_fsx,
m.Email_fsx,
m.Discriminator,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_AAA_EntityProfile m
WHERE m.RecordDeleted IS NULL;

-- ===== definitions.access.scenarios (H_AAA_Scenarios) [system-admin] =====
DROP VIEW IF EXISTS Vi_SPC_ScenarioListSummary;
CREATE OR REPLACE VIEW Vi_SPC_ScenarioListSummary AS
SELECT
m.Id,
m.Description,
m.ActivityClassENUM,
m.ClientEntityId,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Address_fsx,
  h0.PostalCode_fsx,
  h0.Phone_fsx,
  h0.FaxNumber_fsx,
  h0.Email_fsx,
  (SELECT COUNT(*) FROM H_AAA_EntityScenarios cc WHERE cc.ScenarioId = m.Id AND cc.RecordDeleted IS NULL) AS EntityScenariosCount,
  (SELECT COUNT(*) FROM H_AAA_ScenarioDataMap cc WHERE cc.ScenarioId = m.Id AND cc.RecordDeleted IS NULL) AS DataMapCount
FROM H_AAA_Scenarios m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.ClientEntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_ScenarioProfile;
CREATE OR REPLACE VIEW Vi_SPC_ScenarioProfile AS
SELECT
m.Id,
m.Description,
m.ActivityClassENUM,
m.ClientEntityId,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Address_fsx,
  h0.PostalCode_fsx,
  h0.Phone_fsx,
  h0.FaxNumber_fsx,
  h0.Email_fsx
FROM H_AAA_Scenarios m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.ClientEntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_ScenarioEntityScenarios;
CREATE OR REPLACE VIEW Vi_SPC_ScenarioEntityScenarios AS
SELECT
j.Id,
j.EntityId,
j.PermittedActENUM,
j.ScenarioId,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0e.Title AS ScenarioTitle,
  h1.Address_fsx,
  h1.PostalCode_fsx,
  h1.Phone_fsx,
  h1.FaxNumber_fsx,
  h1.Email_fsx
FROM H_AAA_EntityScenarios j
  LEFT JOIN H_AAA_Scenarios h0 ON h0.Id = j.ScenarioId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.ClientEntityId
  LEFT JOIN H_AAA_EntityProfile h1 ON h1.Id = j.EntityId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_ScenarioDataMap;
CREATE OR REPLACE VIEW Vi_SPC_ScenarioDataMap AS
SELECT
j.Id,
j.ScenarioId,
j.TargetActENUM,
j.PermitTableName,
j.PermitEntityFieldName,
j.SourceDataType,
j.EntityId,
j.BaseTableName,
j.JoinerActENUM,
j.JoinerFieldName,
j.JoiningTableName,
j.TargetFieldName,
j.CachedQuerySQL,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0e.Title AS ScenarioTitle
FROM H_AAA_ScenarioDataMap j
  LEFT JOIN H_AAA_Scenarios h0 ON h0.Id = j.ScenarioId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.ClientEntityId
WHERE j.RecordDeleted IS NULL;

-- ===== definitions.access.users (H_AAA_Synced_UserInfo) =====
DROP VIEW IF EXISTS Vi_SPC_UserListSummary;
CREATE OR REPLACE VIEW Vi_SPC_UserListSummary AS
SELECT
m.Id,
m.Firstname_fsx,
m.Lastname_fsx,
m.Username,
m.Email_fsx,
m.EmailConfirmed,
m.CellPhone_fsx,
m.CellPhoneConfirmed,
m.IssuedBy,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  (SELECT COUNT(*) FROM H_AAA_UserEntityRoles cc WHERE cc.UserId = m.Id AND cc.RecordDeleted IS NULL) AS EntityRolesCount
FROM H_AAA_Synced_UserInfo m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_UserProfile;
CREATE OR REPLACE VIEW Vi_SPC_UserProfile AS
SELECT
m.Id,
m.Firstname_fsx,
m.Lastname_fsx,
m.Username,
m.Email_fsx,
m.EmailConfirmed,
m.CellPhone_fsx,
m.CellPhoneConfirmed,
m.IssuedBy,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_AAA_Synced_UserInfo m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_UserEntityRoles;
CREATE OR REPLACE VIEW Vi_SPC_UserEntityRoles AS
SELECT
j.Id,
j.UserId,
j.EntityRoleId,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0.Title AS EntityRoleTitle,
  h1.Firstname_fsx,
  h1.Lastname_fsx,
  h1.Username,
  h1.Email_fsx,
  h1.CellPhone_fsx
FROM H_AAA_UserEntityRoles j
  LEFT JOIN H_AAA_EntityRoles h0 ON h0.Id = j.EntityRoleId
  LEFT JOIN H_AAA_Synced_UserInfo h1 ON h1.Id = j.UserId
WHERE j.RecordDeleted IS NULL;

-- ===== definitions.customers (H_TransportCustomers) =====
DROP VIEW IF EXISTS Vi_SPC_CustomerListSummary;
CREATE OR REPLACE VIEW Vi_SPC_CustomerListSummary AS
SELECT
m.Id,
m.EntityId,
m.UserId,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Firstname_fsx,
  h0.Lastname_fsx,
  h0.Username,
  h0.Email_fsx,
  h0.CellPhone_fsx,
  h1.Address_fsx,
  h1.PostalCode_fsx,
  h1.Phone_fsx,
  h1.FaxNumber_fsx,
  h1.Email_fsx,
  (SELECT COUNT(*) FROM H_TransportCustomerContacts cc WHERE cc.CustomerId = m.Id AND cc.RecordDeleted IS NULL) AS ContactsCount,
  (SELECT COUNT(*) FROM H_TransportCustomerMasterGoods cc WHERE cc.CustomerId = m.Id AND cc.RecordDeleted IS NULL) AS MasterGoodsCount,
  (SELECT COUNT(*) FROM H_TransportDistributorCustomers cc WHERE cc.CustomerId = m.Id AND cc.RecordDeleted IS NULL) AS DistributorCustomersCount
FROM H_TransportCustomers m
  LEFT JOIN H_AAA_Synced_UserInfo h0 ON h0.Id = m.UserId
  LEFT JOIN H_AAA_Synced_EntityProfile h1 ON h1.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CustomerProfile;
CREATE OR REPLACE VIEW Vi_SPC_CustomerProfile AS
SELECT
m.Id,
m.EntityId,
m.UserId,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Firstname_fsx,
  h0.Lastname_fsx,
  h0.Username,
  h0.Email_fsx,
  h0.CellPhone_fsx,
  h1.Address_fsx,
  h1.PostalCode_fsx,
  h1.Phone_fsx,
  h1.FaxNumber_fsx,
  h1.Email_fsx
FROM H_TransportCustomers m
  LEFT JOIN H_AAA_Synced_UserInfo h0 ON h0.Id = m.UserId
  LEFT JOIN H_AAA_Synced_EntityProfile h1 ON h1.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CustomerContact;
CREATE OR REPLACE VIEW Vi_SPC_CustomerContact AS
SELECT
j.Id,
j.PossibleUserId,
j.Firstname_fsx,
j.Lastname_fsx,
j.PossibleEntityId,
j.Title,
j.MainLocationId,
j.Buzzer,
j.Language,
j.TimeZone,
j.Currency,
j.SignatureUri,
j.PhotoUri,
j.BirthDate_fsx,
j.Notification_SMS_fsx,
j.Notification_Phone_fsx,
j.Notification_Phone_Extention_fsx,
j.Notification_Email_fsx,
j.Notification_WhatsApp_fsx,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0.Firstname_fsx,
  h0.Lastname_fsx,
  h0.Username,
  h0.Email_fsx,
  h0.CellPhone_fsx,
  h1.Address_fsx,
  h1.PostalCode_fsx,
  h1.Phone_fsx,
  h1.FaxNumber_fsx,
  h1.Email_fsx,
  h2.Title AS MainLocationTitle
FROM H_TransportContactRegistry j
  LEFT JOIN H_AAA_Synced_UserInfo h0 ON h0.Id = j.PossibleUserId
  LEFT JOIN H_AAA_Synced_EntityProfile h1 ON h1.Id = j.PossibleEntityId
  LEFT JOIN H_TransportLocations h2 ON h2.Id = j.MainLocationId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CustomerContacts;
CREATE OR REPLACE VIEW Vi_SPC_CustomerContacts AS
SELECT
j.Id,
j.ContactId,
j.CustomerId,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0e.Title AS ContactTitle,
  h1e.Title AS CustomerTitle
FROM H_TransportCustomerContacts j
  LEFT JOIN H_TransportContactRegistry h0 ON h0.Id = j.ContactId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.PossibleEntityId
  LEFT JOIN H_TransportCustomers h1 ON h1.Id = j.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CustomerMasterGoods;
CREATE OR REPLACE VIEW Vi_SPC_CustomerMasterGoods AS
SELECT
j.Id,
j.Code,
j.Title,
j.Description,
j.CustomerId,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0e.Title AS CustomerTitle
FROM H_TransportCustomerMasterGoods j
  LEFT JOIN H_TransportCustomers h0 ON h0.Id = j.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CustomerDistributorCustomers;
CREATE OR REPLACE VIEW Vi_SPC_CustomerDistributorCustomers AS
SELECT
j.Id,
j.DistributorId,
j.CustomerId,
j.IssuedDate_UTC,
j.ExpiryDate_UTC,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0e.Title AS CustomerTitle,
  h1e.Title AS DistributorTitle
FROM H_TransportDistributorCustomers j
  LEFT JOIN H_TransportCustomers h0 ON h0.Id = j.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_Distributors h1 ON h1.Id = j.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE j.RecordDeleted IS NULL;

-- ===== definitions.cvos (H_CVOs) =====
DROP VIEW IF EXISTS Vi_SPC_CVOListSummary;
CREATE OR REPLACE VIEW Vi_SPC_CVOListSummary AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Address_fsx,
  h0.PostalCode_fsx,
  h0.Phone_fsx,
  h0.FaxNumber_fsx,
  h0.Email_fsx,
  (SELECT COUNT(*) FROM H_CVODrivers cc WHERE cc.CVOId = m.Id AND cc.RecordDeleted IS NULL) AS DriversCount,
  (SELECT COUNT(*) FROM H_CVOServices cc WHERE cc.CVOId = m.Id AND cc.RecordDeleted IS NULL) AS ServicesCount,
  (SELECT COUNT(*) FROM H_CVOVehicles cc WHERE cc.CVOId = m.Id AND cc.RecordDeleted IS NULL) AS VehiclesCount,
  (SELECT COUNT(*) FROM H_DistributorCVOs cc WHERE cc.CVOId = m.Id AND cc.RecordDeleted IS NULL) AS DistributorsCount,
  (SELECT COUNT(*) FROM H_Permits cc WHERE cc.CVOId = m.Id AND cc.RecordDeleted IS NULL) AS PermitsCount
FROM H_CVOs m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CVOProfile;
CREATE OR REPLACE VIEW Vi_SPC_CVOProfile AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Address_fsx,
  h0.PostalCode_fsx,
  h0.Phone_fsx,
  h0.FaxNumber_fsx,
  h0.Email_fsx
FROM H_CVOs m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CVODrivers;
CREATE OR REPLACE VIEW Vi_SPC_CVODrivers AS
SELECT
  j.Id AS LinkId,
  j.CVOId,
  j.DriverId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.UserId,
rel.PersonCVOId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Firstname_fsx,
  rh0.Lastname_fsx,
  rh0.Username,
  rh0.Email_fsx,
  rh0.CellPhone_fsx,
  rh1e.Title AS PersonCVOTitle
FROM H_CVODrivers j
  JOIN H_Drivers rel ON rel.Id = j.DriverId
  LEFT JOIN H_AAA_Synced_UserInfo rh0 ON rh0.Id = rel.UserId
  LEFT JOIN H_CVOs rh1 ON rh1.Id = rel.PersonCVOId
  LEFT JOIN H_AAA_EntityProfile rh1e ON rh1e.Id = rh1.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CVOServices;
CREATE OR REPLACE VIEW Vi_SPC_CVOServices AS
SELECT
j.Id,
j.CVOId,
j.ServiceId,
j.ServiceCategory,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h1e.Title AS CVOTitle
FROM H_CVOServices j
  LEFT JOIN H_CVOs h1 ON h1.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CVOVehicles;
CREATE OR REPLACE VIEW Vi_SPC_CVOVehicles AS
SELECT
  j.Id AS LinkId,
  j.CVOId,
  j.VehicleId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.Plate,
rel.VIN,
rel.Make,
rel.Model,
rel.Province,
rel.Color,
rel.Year,
rel.TransportCategory,
rel.Cargo_Height,
rel.Cargo_Weight,
rel.Cargo_Length,
rel.Cargo_Width,
rel.Capacity_Passengers,
rel.Capacity_Luggage,
rel.VehicleType,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted
FROM H_CVOVehicles j
  JOIN H_VehicleProfile rel ON rel.Id = j.VehicleId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CVODistributors;
CREATE OR REPLACE VIEW Vi_SPC_CVODistributors AS
SELECT
  j.Id AS LinkId,
  j.DistributorId,
  j.CVOId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Address_fsx,
  rh0.PostalCode_fsx,
  rh0.Phone_fsx,
  rh0.FaxNumber_fsx,
  rh0.Email_fsx
FROM H_DistributorCVOs j
  JOIN H_Distributors rel ON rel.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CVOPermits;
CREATE OR REPLACE VIEW Vi_SPC_CVOPermits AS
SELECT
j.Id,
j.HUBId,
j.DistributorId,
j.CVOId,
j.VehicleId,
j.DriverId,
j.ActENUM,
j.PermitIssuerId,
j.PermitTypeId,
j.Code,
j.ServiceCategory,
j.IssuedDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h2e.Title AS HUBTitle,
  h3e.Title AS CVOTitle,
  h5e.Title AS DistributorTitle,
  h6.Title AS PermitTypeTitle,
  h7e.Title AS PermitIssuerTitle
FROM H_Permits j
  LEFT JOIN H_HUBs h2 ON h2.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_CVOs h3 ON h3.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_Distributors h5 ON h5.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_PermitTypes h6 ON h6.Id = j.PermitTypeId
  LEFT JOIN H_PermitIssuers h7 ON h7.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h7e ON h7e.Id = h7.EntityId
WHERE j.RecordDeleted IS NULL;

-- ===== definitions.distributors (H_Distributors) =====
DROP VIEW IF EXISTS Vi_SPC_DistributorListSummary;
CREATE OR REPLACE VIEW Vi_SPC_DistributorListSummary AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Address_fsx,
  h0.PostalCode_fsx,
  h0.Phone_fsx,
  h0.FaxNumber_fsx,
  h0.Email_fsx,
  (SELECT COUNT(*) FROM H_DistributorCVOs cc WHERE cc.DistributorId = m.Id AND cc.RecordDeleted IS NULL) AS CVOsCount,
  (SELECT COUNT(*) FROM H_DistributorDrivers cc WHERE cc.DistributorId = m.Id AND cc.RecordDeleted IS NULL) AS DriversCount,
  (SELECT COUNT(*) FROM H_HUBDistributors cc WHERE cc.DistributorId = m.Id AND cc.RecordDeleted IS NULL) AS HUBsCount,
  (SELECT COUNT(*) FROM H_Permits cc WHERE cc.DistributorId = m.Id AND cc.RecordDeleted IS NULL) AS PermitsCount
FROM H_Distributors m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DistributorProfile;
CREATE OR REPLACE VIEW Vi_SPC_DistributorProfile AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Address_fsx,
  h0.PostalCode_fsx,
  h0.Phone_fsx,
  h0.FaxNumber_fsx,
  h0.Email_fsx
FROM H_Distributors m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DistributorCVOs;
CREATE OR REPLACE VIEW Vi_SPC_DistributorCVOs AS
SELECT
  j.Id AS LinkId,
  j.DistributorId,
  j.CVOId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Address_fsx,
  rh0.PostalCode_fsx,
  rh0.Phone_fsx,
  rh0.FaxNumber_fsx,
  rh0.Email_fsx
FROM H_DistributorCVOs j
  JOIN H_CVOs rel ON rel.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DistributorDrivers;
CREATE OR REPLACE VIEW Vi_SPC_DistributorDrivers AS
SELECT
  j.Id AS LinkId,
  j.DistributorId,
  j.DriverId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.UserId,
rel.PersonCVOId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Firstname_fsx,
  rh0.Lastname_fsx,
  rh0.Username,
  rh0.Email_fsx,
  rh0.CellPhone_fsx,
  rh1e.Title AS PersonCVOTitle
FROM H_DistributorDrivers j
  JOIN H_Drivers rel ON rel.Id = j.DriverId
  LEFT JOIN H_AAA_Synced_UserInfo rh0 ON rh0.Id = rel.UserId
  LEFT JOIN H_CVOs rh1 ON rh1.Id = rel.PersonCVOId
  LEFT JOIN H_AAA_EntityProfile rh1e ON rh1e.Id = rh1.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DistributorHUBs;
CREATE OR REPLACE VIEW Vi_SPC_DistributorHUBs AS
SELECT
  j.Id AS LinkId,
  j.DistributorId,
  j.HUBId,
  j.ParticipationCategory,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Address_fsx,
  rh0.PostalCode_fsx,
  rh0.Phone_fsx,
  rh0.FaxNumber_fsx,
  rh0.Email_fsx
FROM H_HUBDistributors j
  JOIN H_HUBs rel ON rel.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DistributorPermits;
CREATE OR REPLACE VIEW Vi_SPC_DistributorPermits AS
SELECT
j.Id,
j.HUBId,
j.DistributorId,
j.CVOId,
j.VehicleId,
j.DriverId,
j.ActENUM,
j.PermitIssuerId,
j.PermitTypeId,
j.Code,
j.ServiceCategory,
j.IssuedDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h2e.Title AS HUBTitle,
  h3e.Title AS CVOTitle,
  h5e.Title AS DistributorTitle,
  h6.Title AS PermitTypeTitle,
  h7e.Title AS PermitIssuerTitle
FROM H_Permits j
  LEFT JOIN H_HUBs h2 ON h2.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_CVOs h3 ON h3.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_Distributors h5 ON h5.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_PermitTypes h6 ON h6.Id = j.PermitTypeId
  LEFT JOIN H_PermitIssuers h7 ON h7.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h7e ON h7e.Id = h7.EntityId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DistributorCustomers;
CREATE OR REPLACE VIEW Vi_SPC_DistributorCustomers AS
SELECT
j.Id,
j.DistributorId,
j.CustomerId,
j.IssuedDate_UTC,
j.ExpiryDate_UTC,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0e.Title AS CustomerTitle,
  h1e.Title AS DistributorTitle
FROM H_TransportDistributorCustomers j
  LEFT JOIN H_TransportCustomers h0 ON h0.Id = j.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_Distributors h1 ON h1.Id = j.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE j.RecordDeleted IS NULL;

-- ===== definitions.drivers (H_Drivers) =====
DROP VIEW IF EXISTS Vi_SPC_DriverListSummary;
CREATE OR REPLACE VIEW Vi_SPC_DriverListSummary AS
SELECT
m.Id,
m.UserId,
m.PersonCVOId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Firstname_fsx,
  h0.Lastname_fsx,
  h0.Username,
  h0.Email_fsx,
  h0.CellPhone_fsx,
  h1e.Title AS PersonCVOTitle,
  (SELECT COUNT(*) FROM H_CVODrivers cc WHERE cc.DriverId = m.Id AND cc.RecordDeleted IS NULL) AS CVOsCount,
  (SELECT COUNT(*) FROM H_DistributorDrivers cc WHERE cc.DriverId = m.Id AND cc.RecordDeleted IS NULL) AS DistributorsCount,
  (SELECT COUNT(*) FROM H_Permits cc WHERE cc.DriverId = m.Id AND cc.RecordDeleted IS NULL) AS PermitsCount,
  (SELECT COUNT(*) FROM H_VehicleDrivers cc WHERE cc.DriverId = m.Id AND cc.RecordDeleted IS NULL) AS VehiclesCount
FROM H_Drivers m
  LEFT JOIN H_AAA_Synced_UserInfo h0 ON h0.Id = m.UserId
  LEFT JOIN H_CVOs h1 ON h1.Id = m.PersonCVOId
  LEFT JOIN H_AAA_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DriverProfile;
CREATE OR REPLACE VIEW Vi_SPC_DriverProfile AS
SELECT
m.Id,
m.UserId,
m.PersonCVOId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Firstname_fsx,
  h0.Lastname_fsx,
  h0.Username,
  h0.Email_fsx,
  h0.CellPhone_fsx,
  h1e.Title AS PersonCVOTitle
FROM H_Drivers m
  LEFT JOIN H_AAA_Synced_UserInfo h0 ON h0.Id = m.UserId
  LEFT JOIN H_CVOs h1 ON h1.Id = m.PersonCVOId
  LEFT JOIN H_AAA_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DriverCVOs;
CREATE OR REPLACE VIEW Vi_SPC_DriverCVOs AS
SELECT
  j.Id AS LinkId,
  j.CVOId,
  j.DriverId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Address_fsx,
  rh0.PostalCode_fsx,
  rh0.Phone_fsx,
  rh0.FaxNumber_fsx,
  rh0.Email_fsx
FROM H_CVODrivers j
  JOIN H_CVOs rel ON rel.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DriverDistributors;
CREATE OR REPLACE VIEW Vi_SPC_DriverDistributors AS
SELECT
  j.Id AS LinkId,
  j.DistributorId,
  j.DriverId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Address_fsx,
  rh0.PostalCode_fsx,
  rh0.Phone_fsx,
  rh0.FaxNumber_fsx,
  rh0.Email_fsx
FROM H_DistributorDrivers j
  JOIN H_Distributors rel ON rel.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DriverPermits;
CREATE OR REPLACE VIEW Vi_SPC_DriverPermits AS
SELECT
j.Id,
j.HUBId,
j.DistributorId,
j.CVOId,
j.VehicleId,
j.DriverId,
j.ActENUM,
j.PermitIssuerId,
j.PermitTypeId,
j.Code,
j.ServiceCategory,
j.IssuedDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h2e.Title AS HUBTitle,
  h3e.Title AS CVOTitle,
  h5e.Title AS DistributorTitle,
  h6.Title AS PermitTypeTitle,
  h7e.Title AS PermitIssuerTitle
FROM H_Permits j
  LEFT JOIN H_HUBs h2 ON h2.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_CVOs h3 ON h3.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_Distributors h5 ON h5.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_PermitTypes h6 ON h6.Id = j.PermitTypeId
  LEFT JOIN H_PermitIssuers h7 ON h7.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h7e ON h7e.Id = h7.EntityId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DriverVehicles;
CREATE OR REPLACE VIEW Vi_SPC_DriverVehicles AS
SELECT
  j.Id AS LinkId,
  j.VehicleId,
  j.DriverId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.Plate,
rel.VIN,
rel.Make,
rel.Model,
rel.Province,
rel.Color,
rel.Year,
rel.TransportCategory,
rel.Cargo_Height,
rel.Cargo_Weight,
rel.Cargo_Length,
rel.Cargo_Width,
rel.Capacity_Passengers,
rel.Capacity_Luggage,
rel.VehicleType,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted
FROM H_VehicleDrivers j
  JOIN H_VehicleProfile rel ON rel.Id = j.VehicleId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

-- ===== definitions.hubs (H_HUBs) =====
DROP VIEW IF EXISTS Vi_SPC_HUBListSummary;
CREATE OR REPLACE VIEW Vi_SPC_HUBListSummary AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Address_fsx,
  h0.PostalCode_fsx,
  h0.Phone_fsx,
  h0.FaxNumber_fsx,
  h0.Email_fsx,
  (SELECT COUNT(*) FROM H_HUBDistributors cc WHERE cc.HUBId = m.Id AND cc.RecordDeleted IS NULL) AS DistributorsCount,
  (SELECT COUNT(*) FROM H_Permits cc WHERE cc.HUBId = m.Id AND cc.RecordDeleted IS NULL) AS PermitsCount
FROM H_HUBs m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_HUBProfile;
CREATE OR REPLACE VIEW Vi_SPC_HUBProfile AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Address_fsx,
  h0.PostalCode_fsx,
  h0.Phone_fsx,
  h0.FaxNumber_fsx,
  h0.Email_fsx
FROM H_HUBs m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_HUBDistributors;
CREATE OR REPLACE VIEW Vi_SPC_HUBDistributors AS
SELECT
  j.Id AS LinkId,
  j.DistributorId,
  j.HUBId,
  j.ParticipationCategory,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Address_fsx,
  rh0.PostalCode_fsx,
  rh0.Phone_fsx,
  rh0.FaxNumber_fsx,
  rh0.Email_fsx
FROM H_HUBDistributors j
  JOIN H_Distributors rel ON rel.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_HUBPermits;
CREATE OR REPLACE VIEW Vi_SPC_HUBPermits AS
SELECT
j.Id,
j.HUBId,
j.DistributorId,
j.CVOId,
j.VehicleId,
j.DriverId,
j.ActENUM,
j.PermitIssuerId,
j.PermitTypeId,
j.Code,
j.ServiceCategory,
j.IssuedDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h2e.Title AS HUBTitle,
  h3e.Title AS CVOTitle,
  h5e.Title AS DistributorTitle,
  h6.Title AS PermitTypeTitle,
  h7e.Title AS PermitIssuerTitle
FROM H_Permits j
  LEFT JOIN H_HUBs h2 ON h2.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_CVOs h3 ON h3.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_Distributors h5 ON h5.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_PermitTypes h6 ON h6.Id = j.PermitTypeId
  LEFT JOIN H_PermitIssuers h7 ON h7.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h7e ON h7e.Id = h7.EntityId
WHERE j.RecordDeleted IS NULL;

-- ===== definitions.requests (H_RequestStatuses) =====
DROP VIEW IF EXISTS Vi_SPC_RequestsApprovalListSummary;
CREATE OR REPLACE VIEW Vi_SPC_RequestsApprovalListSummary AS
SELECT
m.Id,
m.RequestId,
m.RequesteeUserId,
m.RequesteeEntityId,
m.RequesteeActENUM,
m.Status,
m.StatusReason,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Address_fsx,
  h0.PostalCode_fsx,
  h0.Phone_fsx,
  h0.FaxNumber_fsx,
  h0.Email_fsx,
  h1.Firstname_fsx,
  h1.Lastname_fsx,
  h1.Username,
  h1.Email_fsx,
  h1.CellPhone_fsx,
  h2e.Title AS RequestTitle,
  (SELECT COUNT(*) FROM H_PermitStatusVerifications cc WHERE cc.RequestStatusId = m.Id AND cc.RecordDeleted IS NULL) AS PermitStatusVerificationsCount
FROM H_RequestStatuses m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.RequesteeEntityId
  LEFT JOIN H_AAA_Synced_UserInfo h1 ON h1.Id = m.RequesteeUserId
  LEFT JOIN H_RequestBases h2 ON h2.Id = m.RequestId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.RequesterEntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RequestsApprovalProfile;
CREATE OR REPLACE VIEW Vi_SPC_RequestsApprovalProfile AS
SELECT
m.Id,
m.RequestId,
m.RequesteeUserId,
m.RequesteeEntityId,
m.RequesteeActENUM,
m.Status,
m.StatusReason,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Address_fsx,
  h0.PostalCode_fsx,
  h0.Phone_fsx,
  h0.FaxNumber_fsx,
  h0.Email_fsx,
  h1.Firstname_fsx,
  h1.Lastname_fsx,
  h1.Username,
  h1.Email_fsx,
  h1.CellPhone_fsx,
  h2e.Title AS RequestTitle
FROM H_RequestStatuses m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.RequesteeEntityId
  LEFT JOIN H_AAA_Synced_UserInfo h1 ON h1.Id = m.RequesteeUserId
  LEFT JOIN H_RequestBases h2 ON h2.Id = m.RequestId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.RequesterEntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RequestsApprovalPermitStatusVerifications;
CREATE OR REPLACE VIEW Vi_SPC_RequestsApprovalPermitStatusVerifications AS
SELECT
j.Id,
j.PermitStatusId,
j.RequestStatusId,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h1e.Title AS RequestStatusTitle
FROM H_PermitStatusVerifications j
  LEFT JOIN H_RequestStatuses h1 ON h1.Id = j.RequestStatusId
  LEFT JOIN H_AAA_EntityProfile h1e ON h1e.Id = h1.RequesteeEntityId
WHERE j.RecordDeleted IS NULL;

-- ===== definitions.vehicles (H_VehicleProfile) =====
DROP VIEW IF EXISTS Vi_SPC_VehicleListSummary;
CREATE OR REPLACE VIEW Vi_SPC_VehicleListSummary AS
SELECT
m.Id,
m.Plate,
m.VIN,
m.Make,
m.Model,
m.Province,
m.Color,
m.Year,
m.TransportCategory,
m.Cargo_Height,
m.Cargo_Weight,
m.Cargo_Length,
m.Cargo_Width,
m.Capacity_Passengers,
m.Capacity_Luggage,
m.VehicleType,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  (SELECT COUNT(*) FROM H_CVOVehicles cc WHERE cc.VehicleId = m.Id AND cc.RecordDeleted IS NULL) AS CVOsCount,
  (SELECT COUNT(*) FROM H_Permits cc WHERE cc.VehicleId = m.Id AND cc.RecordDeleted IS NULL) AS PermitsCount,
  (SELECT COUNT(*) FROM H_VehicleDrivers cc WHERE cc.VehicleId = m.Id AND cc.RecordDeleted IS NULL) AS DriversCount,
  (SELECT COUNT(*) FROM H_VehicleFeatures cc WHERE cc.VehicleId = m.Id AND cc.RecordDeleted IS NULL) AS FeaturesCount
FROM H_VehicleProfile m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_VehicleProfile;
CREATE OR REPLACE VIEW Vi_SPC_VehicleProfile AS
SELECT
m.Id,
m.Plate,
m.VIN,
m.Make,
m.Model,
m.Province,
m.Color,
m.Year,
m.TransportCategory,
m.Cargo_Height,
m.Cargo_Weight,
m.Cargo_Length,
m.Cargo_Width,
m.Capacity_Passengers,
m.Capacity_Luggage,
m.VehicleType,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_VehicleProfile m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_VehicleCVOs;
CREATE OR REPLACE VIEW Vi_SPC_VehicleCVOs AS
SELECT
  j.Id AS LinkId,
  j.CVOId,
  j.VehicleId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Address_fsx,
  rh0.PostalCode_fsx,
  rh0.Phone_fsx,
  rh0.FaxNumber_fsx,
  rh0.Email_fsx
FROM H_CVOVehicles j
  JOIN H_CVOs rel ON rel.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_VehiclePermits;
CREATE OR REPLACE VIEW Vi_SPC_VehiclePermits AS
SELECT
j.Id,
j.HUBId,
j.DistributorId,
j.CVOId,
j.VehicleId,
j.DriverId,
j.ActENUM,
j.PermitIssuerId,
j.PermitTypeId,
j.Code,
j.ServiceCategory,
j.IssuedDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h2e.Title AS HUBTitle,
  h3e.Title AS CVOTitle,
  h5e.Title AS DistributorTitle,
  h6.Title AS PermitTypeTitle,
  h7e.Title AS PermitIssuerTitle
FROM H_Permits j
  LEFT JOIN H_HUBs h2 ON h2.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_CVOs h3 ON h3.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_Distributors h5 ON h5.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_PermitTypes h6 ON h6.Id = j.PermitTypeId
  LEFT JOIN H_PermitIssuers h7 ON h7.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h7e ON h7e.Id = h7.EntityId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_VehicleDrivers;
CREATE OR REPLACE VIEW Vi_SPC_VehicleDrivers AS
SELECT
  j.Id AS LinkId,
  j.VehicleId,
  j.DriverId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.UserId,
rel.PersonCVOId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Firstname_fsx,
  rh0.Lastname_fsx,
  rh0.Username,
  rh0.Email_fsx,
  rh0.CellPhone_fsx,
  rh1e.Title AS PersonCVOTitle
FROM H_VehicleDrivers j
  JOIN H_Drivers rel ON rel.Id = j.DriverId
  LEFT JOIN H_AAA_Synced_UserInfo rh0 ON rh0.Id = rel.UserId
  LEFT JOIN H_CVOs rh1 ON rh1.Id = rel.PersonCVOId
  LEFT JOIN H_AAA_EntityProfile rh1e ON rh1e.Id = rh1.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_VehicleFeatures;
CREATE OR REPLACE VIEW Vi_SPC_VehicleFeatures AS
SELECT
j.Id,
j.FeatureId,
j.VehicleId,
j.HasRule,
j.IssuedDate_UTC,
j.ExpiryDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0.Title AS FeatureTitle
FROM H_VehicleFeatures j
  LEFT JOIN H_Features h0 ON h0.Id = j.FeatureId
WHERE j.RecordDeleted IS NULL;

-- ===== header.notifications (H_NotificationQueue) =====
-- TODO(tray): Vi_SPC_NotificationTray  (source H_NotificationQueue)

-- ===== system.app-registration.app-clients (H_AAA_AppClients) =====
DROP VIEW IF EXISTS Vi_SPC_AppClientListSummary;
CREATE OR REPLACE VIEW Vi_SPC_AppClientListSummary AS
SELECT
m.Id,
m.Title,
m.ClientId,
m.AppTypeId,
m.IsInactive,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS AppTypeTitle
FROM H_AAA_AppClients m
  LEFT JOIN H_AAA_AppTypes h0 ON h0.Id = m.AppTypeId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_AppClientProfile;
CREATE OR REPLACE VIEW Vi_SPC_AppClientProfile AS
SELECT
m.Id,
m.Title,
m.ClientId,
m.AppTypeId,
m.IsInactive,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS AppTypeTitle
FROM H_AAA_AppClients m
  LEFT JOIN H_AAA_AppTypes h0 ON h0.Id = m.AppTypeId
WHERE m.RecordDeleted IS NULL;

-- ===== system.app-registration.app-types (H_AAA_AppTypes) =====
DROP VIEW IF EXISTS Vi_SPC_AppTypeListSummary;
CREATE OR REPLACE VIEW Vi_SPC_AppTypeListSummary AS
SELECT
m.Id,
m.Code,
m.Title,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  (SELECT COUNT(*) FROM H_AAA_AppTypePermissions cc WHERE cc.AppTypeId = m.Id AND cc.RecordDeleted IS NULL) AS PermissionsCount
FROM H_AAA_AppTypes m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_AppTypeProfile;
CREATE OR REPLACE VIEW Vi_SPC_AppTypeProfile AS
SELECT
m.Id,
m.Code,
m.Title,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_AAA_AppTypes m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_AppTypePermissions;
CREATE OR REPLACE VIEW Vi_SPC_AppTypePermissions AS
SELECT
j.Id,
j.AppTypeId,
j.AppPermissionId,
j.Signature,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0.Title AS AppTypeTitle,
  h1.Title AS AppPermissionTitle
FROM H_AAA_AppTypePermissions j
  LEFT JOIN H_AAA_AppTypes h0 ON h0.Id = j.AppTypeId
  LEFT JOIN H_AAA_AppPermissions h1 ON h1.Id = j.AppPermissionId
WHERE j.RecordDeleted IS NULL;

-- ===== system.configurations.action-config-bases (H_CFG_ActionConfigBases) =====
DROP VIEW IF EXISTS Vi_SPC_ActionConfigBaseListSummary;
CREATE OR REPLACE VIEW Vi_SPC_ActionConfigBaseListSummary AS
SELECT
m.Id,
m.Code,
m.Description,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_CFG_ActionConfigBases m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_ActionConfigBaseProfile;
CREATE OR REPLACE VIEW Vi_SPC_ActionConfigBaseProfile AS
SELECT
m.Id,
m.Code,
m.Description,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_CFG_ActionConfigBases m
WHERE m.RecordDeleted IS NULL;

-- ===== system.configurations.actor-configs (H_CFG_ActorConfigs) =====
DROP VIEW IF EXISTS Vi_SPC_ActorConfigListSummary;
CREATE OR REPLACE VIEW Vi_SPC_ActorConfigListSummary AS
SELECT
m.Id,
m.EntityId,
m.VehicleId,
m.UserId,
m.ActENUM,
m.ScenarioId,
m.ConfigBaseId,
m.Value,
m.IsOverridable,
m.Signature,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS ScenarioTitle,
  h2.Code AS ConfigBaseCode,
  h3.Firstname_fsx,
  h3.Lastname_fsx,
  h3.Username,
  h3.Email_fsx,
  h3.CellPhone_fsx
FROM H_CFG_ActorConfigs m
  LEFT JOIN H_AAA_EntityScenarios h0 ON h0.Id = m.ScenarioId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_CFG_ActionConfigBases h2 ON h2.Id = m.ConfigBaseId
  LEFT JOIN H_AAA_Synced_UserInfo h3 ON h3.Id = m.UserId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_ActorConfigProfile;
CREATE OR REPLACE VIEW Vi_SPC_ActorConfigProfile AS
SELECT
m.Id,
m.EntityId,
m.VehicleId,
m.UserId,
m.ActENUM,
m.ScenarioId,
m.ConfigBaseId,
m.Value,
m.IsOverridable,
m.Signature,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS ScenarioTitle,
  h2.Code AS ConfigBaseCode,
  h3.Firstname_fsx,
  h3.Lastname_fsx,
  h3.Username,
  h3.Email_fsx,
  h3.CellPhone_fsx
FROM H_CFG_ActorConfigs m
  LEFT JOIN H_AAA_EntityScenarios h0 ON h0.Id = m.ScenarioId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_CFG_ActionConfigBases h2 ON h2.Id = m.ConfigBaseId
  LEFT JOIN H_AAA_Synced_UserInfo h3 ON h3.Id = m.UserId
WHERE m.RecordDeleted IS NULL;

-- ===== system.configurations.entity-configs (H_CFG_EntityConfigs) =====
DROP VIEW IF EXISTS Vi_SPC_EntityConfigListSummary;
CREATE OR REPLACE VIEW Vi_SPC_EntityConfigListSummary AS
SELECT
m.Id,
m.PermitIssuerId,
m.HUBId,
m.DistributorId,
m.CVOId,
m.VehicleId,
m.DriverId,
m.ActENUM,
m.ScenarioId,
m.ConfigBaseId,
m.Value,
m.IsOverridable,
m.Signature,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS PermitIssuerTitle,
  h1.Code AS ConfigBaseCode,
  h2e.Title AS DistributorTitle,
  h3e.Title AS ScenarioTitle,
  h5e.Title AS CVOTitle,
  h6e.Title AS HUBTitle
FROM H_CFG_EntityConfigs m
  LEFT JOIN H_PermitIssuers h0 ON h0.Id = m.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_CFG_ActionConfigBases h1 ON h1.Id = m.ConfigBaseId
  LEFT JOIN H_Distributors h2 ON h2.Id = m.DistributorId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_AAA_EntityScenarios h3 ON h3.Id = m.ScenarioId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_CVOs h5 ON h5.Id = m.CVOId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_HUBs h6 ON h6.Id = m.HUBId
  LEFT JOIN H_AAA_EntityProfile h6e ON h6e.Id = h6.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_EntityConfigProfile;
CREATE OR REPLACE VIEW Vi_SPC_EntityConfigProfile AS
SELECT
m.Id,
m.PermitIssuerId,
m.HUBId,
m.DistributorId,
m.CVOId,
m.VehicleId,
m.DriverId,
m.ActENUM,
m.ScenarioId,
m.ConfigBaseId,
m.Value,
m.IsOverridable,
m.Signature,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS PermitIssuerTitle,
  h1.Code AS ConfigBaseCode,
  h2e.Title AS DistributorTitle,
  h3e.Title AS ScenarioTitle,
  h5e.Title AS CVOTitle,
  h6e.Title AS HUBTitle
FROM H_CFG_EntityConfigs m
  LEFT JOIN H_PermitIssuers h0 ON h0.Id = m.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_CFG_ActionConfigBases h1 ON h1.Id = m.ConfigBaseId
  LEFT JOIN H_Distributors h2 ON h2.Id = m.DistributorId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_AAA_EntityScenarios h3 ON h3.Id = m.ScenarioId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_CVOs h5 ON h5.Id = m.CVOId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_HUBs h6 ON h6.Id = m.HUBId
  LEFT JOIN H_AAA_EntityProfile h6e ON h6e.Id = h6.EntityId
WHERE m.RecordDeleted IS NULL;

-- ===== system.configurations.global-configs (H_CFG_GlobalConfigs) =====
DROP VIEW IF EXISTS Vi_SPC_GlobalConfigListSummary;
CREATE OR REPLACE VIEW Vi_SPC_GlobalConfigListSummary AS
SELECT
m.Id,
m.ConfigBaseId,
m.Value,
m.IsOverridable,
m.Signature,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Code AS ConfigBaseCode
FROM H_CFG_GlobalConfigs m
  LEFT JOIN H_CFG_ActionConfigBases h0 ON h0.Id = m.ConfigBaseId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_GlobalConfigProfile;
CREATE OR REPLACE VIEW Vi_SPC_GlobalConfigProfile AS
SELECT
m.Id,
m.ConfigBaseId,
m.Value,
m.IsOverridable,
m.Signature,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Code AS ConfigBaseCode
FROM H_CFG_GlobalConfigs m
  LEFT JOIN H_CFG_ActionConfigBases h0 ON h0.Id = m.ConfigBaseId
WHERE m.RecordDeleted IS NULL;

-- ===== system.notification-definitions.templates (H_NotificationTemplateSettings) =====
DROP VIEW IF EXISTS Vi_SPC_NotificationTemplateListSummary;
CREATE OR REPLACE VIEW Vi_SPC_NotificationTemplateListSummary AS
SELECT
m.Id,
m.NotificationTypeENUM,
m.NotificationTemplateENUM,
m.NotificationPlatformENUM,
m.Settings,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_NotificationTemplateSettings m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_NotificationTemplateProfile;
CREATE OR REPLACE VIEW Vi_SPC_NotificationTemplateProfile AS
SELECT
m.Id,
m.NotificationTypeENUM,
m.NotificationTemplateENUM,
m.NotificationPlatformENUM,
m.Settings,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_NotificationTemplateSettings m
WHERE m.RecordDeleted IS NULL;

-- ===== system.permit-management.permit-issuers (H_PermitIssuers) =====
DROP VIEW IF EXISTS Vi_SPC_PermitIssuerListSummary;
CREATE OR REPLACE VIEW Vi_SPC_PermitIssuerListSummary AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Address_fsx,
  h0.PostalCode_fsx,
  h0.Phone_fsx,
  h0.FaxNumber_fsx,
  h0.Email_fsx,
  (SELECT COUNT(*) FROM H_PermitTypeIssuers cc WHERE cc.PermitIssuerId = m.Id AND cc.RecordDeleted IS NULL) AS PermitTypeIssuersCount,
  (SELECT COUNT(*) FROM H_Permits cc WHERE cc.PermitIssuerId = m.Id AND cc.RecordDeleted IS NULL) AS PermitsCount
FROM H_PermitIssuers m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_PermitIssuerProfile;
CREATE OR REPLACE VIEW Vi_SPC_PermitIssuerProfile AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Address_fsx,
  h0.PostalCode_fsx,
  h0.Phone_fsx,
  h0.FaxNumber_fsx,
  h0.Email_fsx
FROM H_PermitIssuers m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_PermitIssuerPermitTypeIssuers;
CREATE OR REPLACE VIEW Vi_SPC_PermitIssuerPermitTypeIssuers AS
SELECT
j.Id,
j.PermitIssuerId,
j.PermitTypeId,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0e.Title AS PermitIssuerTitle,
  h1.Title AS PermitTypeTitle
FROM H_PermitTypeIssuers j
  LEFT JOIN H_PermitIssuers h0 ON h0.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_PermitTypes h1 ON h1.Id = j.PermitTypeId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_PermitIssuerPermits;
CREATE OR REPLACE VIEW Vi_SPC_PermitIssuerPermits AS
SELECT
j.Id,
j.HUBId,
j.DistributorId,
j.CVOId,
j.VehicleId,
j.DriverId,
j.ActENUM,
j.PermitIssuerId,
j.PermitTypeId,
j.Code,
j.ServiceCategory,
j.IssuedDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h2e.Title AS HUBTitle,
  h3e.Title AS CVOTitle,
  h5e.Title AS DistributorTitle,
  h6.Title AS PermitTypeTitle,
  h7e.Title AS PermitIssuerTitle
FROM H_Permits j
  LEFT JOIN H_HUBs h2 ON h2.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_CVOs h3 ON h3.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_Distributors h5 ON h5.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_PermitTypes h6 ON h6.Id = j.PermitTypeId
  LEFT JOIN H_PermitIssuers h7 ON h7.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h7e ON h7e.Id = h7.EntityId
WHERE j.RecordDeleted IS NULL;

-- ===== system.permit-management.permit-types (H_PermitTypes) =====
DROP VIEW IF EXISTS Vi_SPC_PermitTypeListSummary;
CREATE OR REPLACE VIEW Vi_SPC_PermitTypeListSummary AS
SELECT
m.Id,
m.ActENUM,
m.ActivityClassENUM,
m.Title,
m.AllowedServiceCategories,
m.Extendable,
m.ProfileDependant,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_PermitTypes m
WHERE m.RecordDeleted IS NULL;

-- ===== transport.batches (H_TransportBatches) =====
DROP VIEW IF EXISTS Vi_SPC_BatchListSummary;
CREATE OR REPLACE VIEW Vi_SPC_BatchListSummary AS
SELECT
m.Id,
m.FMS_OId,
m.DistributorId,
m.TotalFareAtDispatch,
m.FarePortionAmount_CVO,
m.FarePortionAmount_Distributor,
m.FarePortionAmount_Driver,
m.AllowedDiscountPercent,
m.IsEditable,
m.IsChargePerItem,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS DistributorTitle,
  (SELECT COUNT(*) FROM H_TransportBatchItems cc WHERE cc.BatchId = m.Id AND cc.RecordDeleted IS NULL) AS ItemsCount
FROM H_TransportBatches m
  LEFT JOIN H_Synced_Distributors h0 ON h0.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_BatchProfile;
CREATE OR REPLACE VIEW Vi_SPC_BatchProfile AS
SELECT
m.Id,
m.FMS_OId,
m.DistributorId,
m.TotalFareAtDispatch,
m.FarePortionAmount_CVO,
m.FarePortionAmount_Distributor,
m.FarePortionAmount_Driver,
m.AllowedDiscountPercent,
m.IsEditable,
m.IsChargePerItem,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS DistributorTitle
FROM H_TransportBatches m
  LEFT JOIN H_Synced_Distributors h0 ON h0.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_BatchItems;
CREATE OR REPLACE VIEW Vi_SPC_BatchItems AS
SELECT
j.Id,
j.BatchId,
j.ItemOrder,
j.TransportReqRideId,
j.TransportReqDeliveryId,
j.Discriminator,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted
FROM H_TransportBatchItems j
WHERE j.RecordDeleted IS NULL;

-- ===== transport.deliveries (H_TransportReqDeliveries) =====
DROP VIEW IF EXISTS Vi_SPC_DeliveryListSummary;
CREATE OR REPLACE VIEW Vi_SPC_DeliveryListSummary AS
SELECT
m.Id,
m.IsEditable,
m.CustomerId,
m.DistributorId,
m.CVOId,
m.FromContactLocationId,
m.ToContactLocationId,
m.PickupAfterDateTime,
m.PickupAfterDateTime_UTC,
m.PickupBeforeDateTime,
m.PickupBeforeDateTime_UTC,
m.DropOffAfterDateTime,
m.DropOffAfterDateTime_UTC,
m.DropOffBeforeDateTime,
m.DropOffBeforeDateTime_UTC,
m.VehicleType,
m.VehicleProfileSubType,
m.ServiceClass,
m.ActionOnAbsentReceiver,
m.Comments,
m.FareAtSubmission,
m.PromoCode,
m.PaymentCategory,
m.PaymentMethod,
m.PaidAt_UTC,
m.Status,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS DistributorTitle,
  h2e.Title AS CVOTitle,
  h4e.Title AS CustomerTitle,
  (SELECT COUNT(*) FROM H_TransportBatchItems cc WHERE cc.TransportReqDeliveryId = m.Id AND cc.RecordDeleted IS NULL) AS BatchItemsCount,
  (SELECT COUNT(*) FROM H_TransportReqDeliveryAddons cc WHERE cc.TransportReqDeliveryId = m.Id AND cc.RecordDeleted IS NULL) AS ReqDeliveryAddonsCount,
  (SELECT COUNT(*) FROM H_TransportReqDeliveryGoods cc WHERE cc.ReqDeliveryId = m.Id AND cc.RecordDeleted IS NULL) AS ReqDeliveryGoodsCount
FROM H_TransportReqDeliveries m
  LEFT JOIN H_Synced_Distributors h0 ON h0.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_CVOs h2 ON h2.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_TransportCustomers h4 ON h4.Id = m.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h4e ON h4e.Id = h4.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DeliveryProfile;
CREATE OR REPLACE VIEW Vi_SPC_DeliveryProfile AS
SELECT
m.Id,
m.IsEditable,
m.CustomerId,
m.DistributorId,
m.CVOId,
m.FromContactLocationId,
m.ToContactLocationId,
m.PickupAfterDateTime,
m.PickupAfterDateTime_UTC,
m.PickupBeforeDateTime,
m.PickupBeforeDateTime_UTC,
m.DropOffAfterDateTime,
m.DropOffAfterDateTime_UTC,
m.DropOffBeforeDateTime,
m.DropOffBeforeDateTime_UTC,
m.VehicleType,
m.VehicleProfileSubType,
m.ServiceClass,
m.ActionOnAbsentReceiver,
m.Comments,
m.FareAtSubmission,
m.PromoCode,
m.PaymentCategory,
m.PaymentMethod,
m.PaidAt_UTC,
m.Status,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS DistributorTitle,
  h2e.Title AS CVOTitle,
  h4e.Title AS CustomerTitle
FROM H_TransportReqDeliveries m
  LEFT JOIN H_Synced_Distributors h0 ON h0.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_CVOs h2 ON h2.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_TransportCustomers h4 ON h4.Id = m.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h4e ON h4e.Id = h4.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DeliveryBatchItems;
CREATE OR REPLACE VIEW Vi_SPC_DeliveryBatchItems AS
SELECT
j.Id,
j.BatchId,
j.ItemOrder,
j.TransportReqRideId,
j.TransportReqDeliveryId,
j.Discriminator,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted
FROM H_TransportBatchItems j
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DeliveryReqDeliveryAddons;
CREATE OR REPLACE VIEW Vi_SPC_DeliveryReqDeliveryAddons AS
SELECT
j.Id,
j.TransportReqDeliveryId,
j.CalculationItem,
j.CalculationUnit,
j.Amount,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted
FROM H_TransportReqDeliveryAddons j
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DeliveryReqDeliveryGoods;
CREATE OR REPLACE VIEW Vi_SPC_DeliveryReqDeliveryGoods AS
SELECT
j.Id,
j.ReqDeliveryId,
j.CustomerGoodId,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h1.Title AS CustomerGoodTitle
FROM H_TransportReqDeliveryGoods j
  LEFT JOIN H_TransportCustomerMasterGoods h1 ON h1.Id = j.CustomerGoodId
WHERE j.RecordDeleted IS NULL;

-- ===== transport.dispatch (H_TransportTransacts) =====
DROP VIEW IF EXISTS Vi_SPC_DispatchListSummary;
CREATE OR REPLACE VIEW Vi_SPC_DispatchListSummary AS
SELECT
m.Id,
m.FMS_OvId,
m.BatchId,
m.PickupZoneId,
m.CVOId,
m.VehicleId,
m.DriverId,
m.CurrentStatus,
m.OfferType,
m.PaidTripFare,
m.PaidAddonFee,
m.AppliedDiscount,
m.PaidTip,
m.PaidToll,
m.ActualTotalFareAtTripEnd,
m.DriverAgreedFareAmount,
m.EnforceItemsCreationSequense,
m.PaymentTransactionNumber,
m.ExtraData,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h3e.Title AS CVOTitle,
  h4.Title AS PickupZoneTitle,
  (SELECT COUNT(*) FROM H_TransportTransactItems cc WHERE cc.TransportTransactId = m.Id) AS TransactItemsCount,
  (SELECT COUNT(*) FROM H_TransportTransactStages cc WHERE cc.TransportTransactId = m.Id) AS TransactStagesCount
FROM H_TransportTransacts m
  LEFT JOIN H_Synced_CVOs h3 ON h3.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN _ZoneBases h4 ON h4.Id = m.PickupZoneId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DispatchProfile;
CREATE OR REPLACE VIEW Vi_SPC_DispatchProfile AS
SELECT
m.Id,
m.FMS_OvId,
m.BatchId,
m.PickupZoneId,
m.CVOId,
m.VehicleId,
m.DriverId,
m.CurrentStatus,
m.OfferType,
m.PaidTripFare,
m.PaidAddonFee,
m.AppliedDiscount,
m.PaidTip,
m.PaidToll,
m.ActualTotalFareAtTripEnd,
m.DriverAgreedFareAmount,
m.EnforceItemsCreationSequense,
m.PaymentTransactionNumber,
m.ExtraData,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h3e.Title AS CVOTitle,
  h4.Title AS PickupZoneTitle
FROM H_TransportTransacts m
  LEFT JOIN H_Synced_CVOs h3 ON h3.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN _ZoneBases h4 ON h4.Id = m.PickupZoneId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DispatchTransactItems;
CREATE OR REPLACE VIEW Vi_SPC_DispatchTransactItems AS
SELECT
j.Id,
j.TransportTransactId,
j.TransportBatchItemId,
j.CurrentStatus,
j.AggregatedComments,
j.ImageUri,
j.SignatureUri,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy
FROM H_TransportTransactItems j;

DROP VIEW IF EXISTS Vi_SPC_DispatchTransactStages;
CREATE OR REPLACE VIEW Vi_SPC_DispatchTransactStages AS
SELECT
j.Id,
j.TimeStamp_UTC,
j.TransportTransactId,
j.Status,
j.ModifiedBy
FROM H_TransportTransactStages j;

-- ===== transport.rides (H_TransportReqRides) =====
DROP VIEW IF EXISTS Vi_SPC_RideListSummary;
CREATE OR REPLACE VIEW Vi_SPC_RideListSummary AS
SELECT
m.Id,
m.IsEditable,
m.CustomerId,
m.DistributorId,
m.CVOId,
m.FromContactLocationId,
m.ToContactLocationId,
m.PickupAfterDateTime,
m.PickupAfterDateTime_UTC,
m.PickupBeforeDateTime,
m.PickupBeforeDateTime_UTC,
m.DropOffAfterDateTime,
m.DropOffAfterDateTime_UTC,
m.DropOffBeforeDateTime,
m.DropOffBeforeDateTime_UTC,
m.VehicleType,
m.VehicleProfileSubType,
m.ServiceClass,
m.ServiceCategory,
m.TotalRequiredSeats,
m.NumberOfLuggages,
m.FeaturesJSON,
m.Comments,
m.FareAtSubmission,
m.PromoCode,
m.PaymentCategory,
m.PaymentMethod,
m.PaidAt_UTC,
m.HubCarrierInfo,
m.Status,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h1e.Title AS CVOTitle,
  h2e.Title AS CustomerTitle,
  h3e.Title AS DistributorTitle,
  (SELECT COUNT(*) FROM H_TransportBatchItems cc WHERE cc.TransportReqRideId = m.Id AND cc.RecordDeleted IS NULL) AS BatchItemsCount,
  (SELECT COUNT(*) FROM H_TransportReqRideAddons cc WHERE cc.TransportReqRideId = m.Id AND cc.RecordDeleted IS NULL) AS ReqRideAddonsCount,
  (SELECT COUNT(*) FROM H_TransportReqRidePassengers cc WHERE cc.ReqRideId = m.Id AND cc.RecordDeleted IS NULL) AS ReqRidePassengersCount
FROM H_TransportReqRides m
  LEFT JOIN H_Synced_CVOs h1 ON h1.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
  LEFT JOIN H_TransportCustomers h2 ON h2.Id = m.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_Synced_Distributors h3 ON h3.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h3e ON h3e.Id = h3.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RideProfile;
CREATE OR REPLACE VIEW Vi_SPC_RideProfile AS
SELECT
m.Id,
m.IsEditable,
m.CustomerId,
m.DistributorId,
m.CVOId,
m.FromContactLocationId,
m.ToContactLocationId,
m.PickupAfterDateTime,
m.PickupAfterDateTime_UTC,
m.PickupBeforeDateTime,
m.PickupBeforeDateTime_UTC,
m.DropOffAfterDateTime,
m.DropOffAfterDateTime_UTC,
m.DropOffBeforeDateTime,
m.DropOffBeforeDateTime_UTC,
m.VehicleType,
m.VehicleProfileSubType,
m.ServiceClass,
m.ServiceCategory,
m.TotalRequiredSeats,
m.NumberOfLuggages,
m.FeaturesJSON,
m.Comments,
m.FareAtSubmission,
m.PromoCode,
m.PaymentCategory,
m.PaymentMethod,
m.PaidAt_UTC,
m.HubCarrierInfo,
m.Status,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h1e.Title AS CVOTitle,
  h2e.Title AS CustomerTitle,
  h3e.Title AS DistributorTitle
FROM H_TransportReqRides m
  LEFT JOIN H_Synced_CVOs h1 ON h1.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
  LEFT JOIN H_TransportCustomers h2 ON h2.Id = m.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_Synced_Distributors h3 ON h3.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h3e ON h3e.Id = h3.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RideBatchItems;
CREATE OR REPLACE VIEW Vi_SPC_RideBatchItems AS
SELECT
j.Id,
j.BatchId,
j.ItemOrder,
j.TransportReqRideId,
j.TransportReqDeliveryId,
j.Discriminator,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted
FROM H_TransportBatchItems j
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RideReqRideAddons;
CREATE OR REPLACE VIEW Vi_SPC_RideReqRideAddons AS
SELECT
j.Id,
j.TransportReqRideId,
j.CalculationItem,
j.CalculationUnit,
j.Amount,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted
FROM H_TransportReqRideAddons j
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RideReqRidePassengers;
CREATE OR REPLACE VIEW Vi_SPC_RideReqRidePassengers AS
SELECT
j.Id,
j.ReqRideId,
j.PassengerId,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted
FROM H_TransportReqRidePassengers j
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RideTransactItemStages;
CREATE OR REPLACE VIEW Vi_SPC_RideTransactItemStages AS
SELECT
j.Id,
j.TimeStamp_UTC,
j.TransactStepId,
j.Status,
j.Comments,
j.ImageUri,
j.SignatureUri,
j.ModifiedBy
FROM H_TransportTransactItemStages j;

-- ===== transport.setup.contact-locations (H_TransportContactLocations) =====
DROP VIEW IF EXISTS Vi_SPC_ContactLocationListSummary;
CREATE OR REPLACE VIEW Vi_SPC_ContactLocationListSummary AS
SELECT
m.Id,
m.ContactId,
m.FavAdrLabel,
m.LocationId,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS LocationTitle,
  h1e.Title AS ContactTitle
FROM H_TransportContactLocations m
  LEFT JOIN H_TransportLocations h0 ON h0.Id = m.LocationId
  LEFT JOIN H_TransportContactRegistry h1 ON h1.Id = m.ContactId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.PossibleEntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_ContactLocationProfile;
CREATE OR REPLACE VIEW Vi_SPC_ContactLocationProfile AS
SELECT
m.Id,
m.ContactId,
m.FavAdrLabel,
m.LocationId,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS LocationTitle,
  h1e.Title AS ContactTitle
FROM H_TransportContactLocations m
  LEFT JOIN H_TransportLocations h0 ON h0.Id = m.LocationId
  LEFT JOIN H_TransportContactRegistry h1 ON h1.Id = m.ContactId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.PossibleEntityId
WHERE m.RecordDeleted IS NULL;

-- ===== transport.setup.fare-base-inclutions (H_TransportFareBaseInclutions) =====
DROP VIEW IF EXISTS Vi_SPC_FareBaseInclutionListSummary;
CREATE OR REPLACE VIEW Vi_SPC_FareBaseInclutionListSummary AS
SELECT
m.Id,
m.DistributorId,
m.CVOId,
m.TransportCategory,
m.ServiceCategory,
m.VehicleType,
m.ServiceClass,
m.IncludedSeatCounts,
m.IncludedLuggageCounts,
m.IncludedParcelCounts,
m.IncludedWeightKg,
m.IncludedVolumeCubicM,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS CVOTitle,
  h1e.Title AS DistributorTitle
FROM H_TransportFareBaseInclutions m
  LEFT JOIN H_Synced_CVOs h0 ON h0.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_Distributors h1 ON h1.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_FareBaseInclutionProfile;
CREATE OR REPLACE VIEW Vi_SPC_FareBaseInclutionProfile AS
SELECT
m.Id,
m.DistributorId,
m.CVOId,
m.TransportCategory,
m.ServiceCategory,
m.VehicleType,
m.ServiceClass,
m.IncludedSeatCounts,
m.IncludedLuggageCounts,
m.IncludedParcelCounts,
m.IncludedWeightKg,
m.IncludedVolumeCubicM,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS CVOTitle,
  h1e.Title AS DistributorTitle
FROM H_TransportFareBaseInclutions m
  LEFT JOIN H_Synced_CVOs h0 ON h0.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_Distributors h1 ON h1.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE m.RecordDeleted IS NULL;

-- ===== transport.setup.fare-by-geo-fence (H_TransportFareByGeoFence) =====
DROP VIEW IF EXISTS Vi_SPC_FareByGeoFenceListSummary;
CREATE OR REPLACE VIEW Vi_SPC_FareByGeoFenceListSummary AS
SELECT
m.Id,
m.TransportFareCalculationId,
m.SourceGeoFenceBaseId,
m.DestinationGeoFenceBaseId,
m.BaseFare,
  h1.Title AS DestinationGeoFenceBaseTitle,
  h2.Title AS SourceGeoFenceBaseTitle
FROM H_TransportFareByGeoFence m
  LEFT JOIN H_TransportGeoFenceBases h1 ON h1.Id = m.DestinationGeoFenceBaseId
  LEFT JOIN H_TransportGeoFenceBases h2 ON h2.Id = m.SourceGeoFenceBaseId;

DROP VIEW IF EXISTS Vi_SPC_FareByGeoFenceProfile;
CREATE OR REPLACE VIEW Vi_SPC_FareByGeoFenceProfile AS
SELECT
m.Id,
m.TransportFareCalculationId,
m.SourceGeoFenceBaseId,
m.DestinationGeoFenceBaseId,
m.BaseFare,
  h1.Title AS DestinationGeoFenceBaseTitle,
  h2.Title AS SourceGeoFenceBaseTitle
FROM H_TransportFareByGeoFence m
  LEFT JOIN H_TransportGeoFenceBases h1 ON h1.Id = m.DestinationGeoFenceBaseId
  LEFT JOIN H_TransportGeoFenceBases h2 ON h2.Id = m.SourceGeoFenceBaseId;

-- ===== transport.setup.fare-by-zone (H_TransportFareByZone) =====
DROP VIEW IF EXISTS Vi_SPC_FareByZoneListSummary;
CREATE OR REPLACE VIEW Vi_SPC_FareByZoneListSummary AS
SELECT
m.Id,
m.TransportFareCalculationId,
m.SourceGeoFenceBaseId,
m.DestinationGeoFenceBaseId,
m.BaseFare,
  h0.Title AS DestinationGeoFenceBaseTitle,
  h1.Title AS SourceGeoFenceBaseTitle
FROM H_TransportFareByZone m
  LEFT JOIN H_TransportGeoFenceBases h0 ON h0.Id = m.DestinationGeoFenceBaseId
  LEFT JOIN H_TransportGeoFenceBases h1 ON h1.Id = m.SourceGeoFenceBaseId;

DROP VIEW IF EXISTS Vi_SPC_FareByZoneProfile;
CREATE OR REPLACE VIEW Vi_SPC_FareByZoneProfile AS
SELECT
m.Id,
m.TransportFareCalculationId,
m.SourceGeoFenceBaseId,
m.DestinationGeoFenceBaseId,
m.BaseFare,
  h0.Title AS DestinationGeoFenceBaseTitle,
  h1.Title AS SourceGeoFenceBaseTitle
FROM H_TransportFareByZone m
  LEFT JOIN H_TransportGeoFenceBases h0 ON h0.Id = m.DestinationGeoFenceBaseId
  LEFT JOIN H_TransportGeoFenceBases h1 ON h1.Id = m.SourceGeoFenceBaseId;

-- ===== transport.setup.fare-calculations (H_TransportFareCalculations) =====
DROP VIEW IF EXISTS Vi_SPC_FareCalculationListSummary;
CREATE OR REPLACE VIEW Vi_SPC_FareCalculationListSummary AS
SELECT
m.Id,
m.DistributorId,
m.CVOId,
m.TransportCategory,
m.ServiceCategory,
m.VehicleType,
m.ServiceClass,
m.CalculationItem,
m.CalculationType,
m.CalculateMethod,
m.CalculationPriority,
m.CalculationUnit,
m.UnitAmount,
m.Price,
m.PriceTable,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS DistributorTitle,
  h1e.Title AS CVOTitle
FROM H_TransportFareCalculations m
  LEFT JOIN H_Synced_Distributors h0 ON h0.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_CVOs h1 ON h1.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_FareCalculationProfile;
CREATE OR REPLACE VIEW Vi_SPC_FareCalculationProfile AS
SELECT
m.Id,
m.DistributorId,
m.CVOId,
m.TransportCategory,
m.ServiceCategory,
m.VehicleType,
m.ServiceClass,
m.CalculationItem,
m.CalculationType,
m.CalculateMethod,
m.CalculationPriority,
m.CalculationUnit,
m.UnitAmount,
m.Price,
m.PriceTable,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS DistributorTitle,
  h1e.Title AS CVOTitle
FROM H_TransportFareCalculations m
  LEFT JOIN H_Synced_Distributors h0 ON h0.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_CVOs h1 ON h1.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE m.RecordDeleted IS NULL;

-- ===== transport.setup.geo-fence-bases (H_TransportGeoFenceBases) =====
DROP VIEW IF EXISTS Vi_SPC_GeoFenceBaseListSummary;
CREATE OR REPLACE VIEW Vi_SPC_GeoFenceBaseListSummary AS
SELECT
m.Id,
m.Code,
m.Title,
m.Coordinates,
m.Order,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_TransportGeoFenceBases m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_GeoFenceBaseProfile;
CREATE OR REPLACE VIEW Vi_SPC_GeoFenceBaseProfile AS
SELECT
m.Id,
m.Code,
m.Title,
m.Coordinates,
m.Order,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_TransportGeoFenceBases m
WHERE m.RecordDeleted IS NULL;

-- ===== transport.setup.locations (H_TransportLocations) =====
DROP VIEW IF EXISTS Vi_SPC_LocationListSummary;
CREATE OR REPLACE VIEW Vi_SPC_LocationListSummary AS
SELECT
m.Id,
m.Title,
m.Latitude,
m.Longitude,
m.Address,
m.City,
m.Province,
m.PostalCode,
m.PlaceId,
m.GoogleFullAddress,
m.CreatedAt_UTC,
m.CreatedBy,
m.RecordDeleted
FROM H_TransportLocations m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_LocationProfile;
CREATE OR REPLACE VIEW Vi_SPC_LocationProfile AS
SELECT
m.Id,
m.Title,
m.Latitude,
m.Longitude,
m.Address,
m.City,
m.Province,
m.PostalCode,
m.PlaceId,
m.GoogleFullAddress,
m.CreatedAt_UTC,
m.CreatedBy,
m.RecordDeleted
FROM H_TransportLocations m
WHERE m.RecordDeleted IS NULL;

