-- GENERATED by builder/stages/s4-spc-emit.mjs — DO NOT EDIT.
-- Scope: CORE. Apply each <backend>.spc-views.sql to THAT backend's database (views live with their tables).
-- Field rules: _fsx verbatim · ENUM ints raw (grid maps) · own-FK label hydration · per-relationship counts · overlay enrichment (§8).
-- Idempotent: safe to re-run. Order: helpers → views → authored.


-- ===== definitions.access.scenarios (H_AAA_Scenarios) [system-admin] =====
DROP VIEW IF EXISTS Vi_SPC_ScenarioListSummary;
CREATE OR REPLACE VIEW Vi_SPC_ScenarioListSummary AS
SELECT
m.Id,
m.Description,
m.ActivityClassENUM,
m.ClientEntityId,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS ClientEntityTitle,
  (SELECT COUNT(*) FROM H_AAA_EntityScenarios cc WHERE cc.ScenarioId = m.Id AND cc.RecordDeleted IS NULL) AS EntityScenariosCount,
  (SELECT COUNT(*) FROM H_AAA_ScenarioDataMap cc WHERE cc.ScenarioId = m.Id AND cc.RecordDeleted IS NULL) AS DataMapCount
FROM H_AAA_Scenarios m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.ClientEntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_ScenarioProfile;
CREATE OR REPLACE VIEW Vi_SPC_ScenarioProfile AS
SELECT
m.Id,
m.Description,
m.ActivityClassENUM,
m.ClientEntityId,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS ClientEntityTitle
FROM H_AAA_Scenarios m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.ClientEntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_ScenarioEntityScenarios;
CREATE OR REPLACE VIEW Vi_SPC_ScenarioEntityScenarios AS
SELECT
j.Id,
j.EntityId,
j.PermittedActENUM,
j.ScenarioId,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0e.Title AS ScenarioTitle,
  h1.Title AS EntityTitle
FROM H_AAA_EntityScenarios j
  LEFT JOIN H_AAA_Scenarios h0 ON h0.Id = j.ScenarioId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.ClientEntityId
  LEFT JOIN H_AAA_EntityProfile h1 ON h1.Id = j.EntityId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_ScenarioDataMap;
CREATE OR REPLACE VIEW Vi_SPC_ScenarioDataMap AS
SELECT
j.Id,
j.ScenarioId,
j.TargetActENUM,
j.PermitTableName,
j.PermitEntityFieldName,
j.SourceDataType,
j.EntityId,
j.BaseTableName,
j.JoinerActENUM,
j.JoinerFieldName,
j.JoiningTableName,
j.TargetFieldName,
j.CachedQuerySQL,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0e.Title AS ScenarioTitle
FROM H_AAA_ScenarioDataMap j
  LEFT JOIN H_AAA_Scenarios h0 ON h0.Id = j.ScenarioId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.ClientEntityId
WHERE j.RecordDeleted IS NULL;

-- ===== definitions.customers (H_TransportCustomers) =====
DROP VIEW IF EXISTS Vi_SPC_CustomerListSummary;
CREATE OR REPLACE VIEW Vi_SPC_CustomerListSummary AS
SELECT
m.Id,
m.EntityId,
m.UserId,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Firstname_fsx,
  h0.Lastname_fsx,
  h0.Username,
  h0.Email_fsx,
  h0.CellPhone_fsx,
  h1.Title AS EntityTitle,
  (SELECT COUNT(*) FROM H_TransportCustomerContacts cc WHERE cc.CustomerId = m.Id AND cc.RecordDeleted IS NULL) AS ContactsCount,
  (SELECT COUNT(*) FROM H_TransportCustomerMasterGoods cc WHERE cc.CustomerId = m.Id AND cc.RecordDeleted IS NULL) AS MasterGoodsCount,
  (SELECT COUNT(*) FROM H_TransportDistributorCustomers cc WHERE cc.CustomerId = m.Id AND cc.RecordDeleted IS NULL) AS DistributorCustomersCount
FROM H_TransportCustomers m
  LEFT JOIN H_AAA_Synced_UserInfo h0 ON h0.Id = m.UserId
  LEFT JOIN H_AAA_Synced_EntityProfile h1 ON h1.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CustomerProfile;
CREATE OR REPLACE VIEW Vi_SPC_CustomerProfile AS
SELECT
m.Id,
m.EntityId,
m.UserId,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Firstname_fsx,
  h0.Lastname_fsx,
  h0.Username,
  h0.Email_fsx,
  h0.CellPhone_fsx,
  h1.Title AS EntityTitle
FROM H_TransportCustomers m
  LEFT JOIN H_AAA_Synced_UserInfo h0 ON h0.Id = m.UserId
  LEFT JOIN H_AAA_Synced_EntityProfile h1 ON h1.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CustomerContact;
CREATE OR REPLACE VIEW Vi_SPC_CustomerContact AS
SELECT
j.Id,
j.PossibleUserId,
j.Firstname_fsx,
j.Lastname_fsx,
j.PossibleEntityId,
j.Title,
j.MainLocationId,
j.Buzzer,
j.Language,
j.TimeZone,
j.Currency,
j.SignatureUri,
j.PhotoUri,
j.BirthDate_fsx,
j.Notification_SMS_fsx,
j.Notification_Phone_fsx,
j.Notification_Phone_Extention_fsx,
j.Notification_Email_fsx,
j.Notification_WhatsApp_fsx,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0.Firstname_fsx AS PossibleUserFirstname_fsx,
  h0.Lastname_fsx AS PossibleUserLastname_fsx,
  h0.Username,
  h0.Email_fsx,
  h0.CellPhone_fsx,
  h1.Title AS PossibleEntityTitle,
  h2.Title AS MainLocationTitle
FROM H_TransportContactRegistry j
  LEFT JOIN H_AAA_Synced_UserInfo h0 ON h0.Id = j.PossibleUserId
  LEFT JOIN H_AAA_Synced_EntityProfile h1 ON h1.Id = j.PossibleEntityId
  LEFT JOIN H_TransportLocations h2 ON h2.Id = j.MainLocationId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CustomerContacts;
CREATE OR REPLACE VIEW Vi_SPC_CustomerContacts AS
SELECT
j.Id,
j.ContactId,
j.CustomerId,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0e.Title AS ContactTitle,
  h1e.Title AS CustomerTitle
FROM H_TransportCustomerContacts j
  LEFT JOIN H_TransportContactRegistry h0 ON h0.Id = j.ContactId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.PossibleEntityId
  LEFT JOIN H_TransportCustomers h1 ON h1.Id = j.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CustomerMasterGoods;
CREATE OR REPLACE VIEW Vi_SPC_CustomerMasterGoods AS
SELECT
j.Id,
j.Code,
j.Title,
j.Description,
j.CustomerId,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0e.Title AS CustomerTitle
FROM H_TransportCustomerMasterGoods j
  LEFT JOIN H_TransportCustomers h0 ON h0.Id = j.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CustomerDistributorCustomers;
CREATE OR REPLACE VIEW Vi_SPC_CustomerDistributorCustomers AS
SELECT
j.Id,
j.DistributorId,
j.CustomerId,
j.IssuedDate_UTC,
j.ExpiryDate_UTC,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0e.Title AS CustomerTitle,
  h1e.Title AS DistributorTitle
FROM H_TransportDistributorCustomers j
  LEFT JOIN H_TransportCustomers h0 ON h0.Id = j.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_Distributors h1 ON h1.Id = j.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE j.RecordDeleted IS NULL;

-- ===== system.app-registration.app-clients (H_AAA_AppClients) =====
DROP VIEW IF EXISTS Vi_SPC_AppClientListSummary;
CREATE OR REPLACE VIEW Vi_SPC_AppClientListSummary AS
SELECT
m.Id,
m.Title,
m.ClientId,
m.AppTypeId,
m.IsInactive,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS AppTypeTitle
FROM H_AAA_AppClients m
  LEFT JOIN H_AAA_AppTypes h0 ON h0.Id = m.AppTypeId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_AppClientProfile;
CREATE OR REPLACE VIEW Vi_SPC_AppClientProfile AS
SELECT
m.Id,
m.Title,
m.ClientId,
m.AppTypeId,
m.IsInactive,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS AppTypeTitle
FROM H_AAA_AppClients m
  LEFT JOIN H_AAA_AppTypes h0 ON h0.Id = m.AppTypeId
WHERE m.RecordDeleted IS NULL;

-- ===== system.app-registration.app-types (H_AAA_AppTypes) =====
DROP VIEW IF EXISTS Vi_SPC_AppTypeListSummary;
CREATE OR REPLACE VIEW Vi_SPC_AppTypeListSummary AS
SELECT
m.Id,
m.Code,
m.Title,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  (SELECT COUNT(*) FROM H_AAA_AppTypePermissions cc WHERE cc.AppTypeId = m.Id AND cc.RecordDeleted IS NULL) AS PermissionsCount
FROM H_AAA_AppTypes m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_AppTypeProfile;
CREATE OR REPLACE VIEW Vi_SPC_AppTypeProfile AS
SELECT
m.Id,
m.Code,
m.Title,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_AAA_AppTypes m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_AppTypePermissions;
CREATE OR REPLACE VIEW Vi_SPC_AppTypePermissions AS
SELECT
j.Id,
j.AppTypeId,
j.AppPermissionId,
j.Signature,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0.Title AS AppTypeTitle,
  h1.Title AS AppPermissionTitle
FROM H_AAA_AppTypePermissions j
  LEFT JOIN H_AAA_AppTypes h0 ON h0.Id = j.AppTypeId
  LEFT JOIN H_AAA_AppPermissions h1 ON h1.Id = j.AppPermissionId
WHERE j.RecordDeleted IS NULL;

-- ===== system.configurations.action-config-bases (H_CFG_ActionConfigBases) =====
DROP VIEW IF EXISTS Vi_SPC_ActionConfigBaseListSummary;
CREATE OR REPLACE VIEW Vi_SPC_ActionConfigBaseListSummary AS
SELECT
m.Id,
m.Code,
m.Description,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_CFG_ActionConfigBases m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_ActionConfigBaseProfile;
CREATE OR REPLACE VIEW Vi_SPC_ActionConfigBaseProfile AS
SELECT
m.Id,
m.Code,
m.Description,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_CFG_ActionConfigBases m
WHERE m.RecordDeleted IS NULL;

-- ===== system.configurations.actor-configs (H_CFG_ActorConfigs) =====
DROP VIEW IF EXISTS Vi_SPC_ActorConfigListSummary;
CREATE OR REPLACE VIEW Vi_SPC_ActorConfigListSummary AS
SELECT
m.Id,
m.EntityId,
m.VehicleId,
m.UserId,
m.ActENUM,
m.ScenarioId,
m.ConfigBaseId,
m.Value,
m.IsOverridable,
m.Signature,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS ScenarioTitle,
  h2.Code AS ConfigBaseCode,
  h3.Firstname_fsx,
  h3.Lastname_fsx,
  h3.Username,
  h3.Email_fsx,
  h3.CellPhone_fsx
FROM H_CFG_ActorConfigs m
  LEFT JOIN H_AAA_EntityScenarios h0 ON h0.Id = m.ScenarioId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_CFG_ActionConfigBases h2 ON h2.Id = m.ConfigBaseId
  LEFT JOIN H_AAA_Synced_UserInfo h3 ON h3.Id = m.UserId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_ActorConfigProfile;
CREATE OR REPLACE VIEW Vi_SPC_ActorConfigProfile AS
SELECT
m.Id,
m.EntityId,
m.VehicleId,
m.UserId,
m.ActENUM,
m.ScenarioId,
m.ConfigBaseId,
m.Value,
m.IsOverridable,
m.Signature,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS ScenarioTitle,
  h2.Code AS ConfigBaseCode,
  h3.Firstname_fsx,
  h3.Lastname_fsx,
  h3.Username,
  h3.Email_fsx,
  h3.CellPhone_fsx
FROM H_CFG_ActorConfigs m
  LEFT JOIN H_AAA_EntityScenarios h0 ON h0.Id = m.ScenarioId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_CFG_ActionConfigBases h2 ON h2.Id = m.ConfigBaseId
  LEFT JOIN H_AAA_Synced_UserInfo h3 ON h3.Id = m.UserId
WHERE m.RecordDeleted IS NULL;

-- ===== system.configurations.global-configs (H_CFG_GlobalConfigs) =====
DROP VIEW IF EXISTS Vi_SPC_GlobalConfigListSummary;
CREATE OR REPLACE VIEW Vi_SPC_GlobalConfigListSummary AS
SELECT
m.Id,
m.ConfigBaseId,
m.Value,
m.IsOverridable,
m.Signature,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Code AS ConfigBaseCode
FROM H_CFG_GlobalConfigs m
  LEFT JOIN H_CFG_ActionConfigBases h0 ON h0.Id = m.ConfigBaseId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_GlobalConfigProfile;
CREATE OR REPLACE VIEW Vi_SPC_GlobalConfigProfile AS
SELECT
m.Id,
m.ConfigBaseId,
m.Value,
m.IsOverridable,
m.Signature,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Code AS ConfigBaseCode
FROM H_CFG_GlobalConfigs m
  LEFT JOIN H_CFG_ActionConfigBases h0 ON h0.Id = m.ConfigBaseId
WHERE m.RecordDeleted IS NULL;

-- ===== transport.batches (H_TransportBatches) =====
DROP VIEW IF EXISTS Vi_SPC_BatchListSummary;
CREATE OR REPLACE VIEW Vi_SPC_BatchListSummary AS
SELECT
m.Id,
m.FMS_OId,
m.DistributorId,
m.TotalFareAtDispatch,
m.FarePortionAmount_CVO,
m.FarePortionAmount_Distributor,
m.FarePortionAmount_Driver,
m.AllowedDiscountPercent,
m.IsEditable,
m.IsChargePerItem,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS DistributorTitle,
  (SELECT COUNT(*) FROM H_TransportBatchItems cc WHERE cc.BatchId = m.Id AND cc.RecordDeleted IS NULL) AS ItemsCount
FROM H_TransportBatches m
  LEFT JOIN H_Synced_Distributors h0 ON h0.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_BatchProfile;
CREATE OR REPLACE VIEW Vi_SPC_BatchProfile AS
SELECT
m.Id,
m.FMS_OId,
m.DistributorId,
m.TotalFareAtDispatch,
m.FarePortionAmount_CVO,
m.FarePortionAmount_Distributor,
m.FarePortionAmount_Driver,
m.AllowedDiscountPercent,
m.IsEditable,
m.IsChargePerItem,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS DistributorTitle
FROM H_TransportBatches m
  LEFT JOIN H_Synced_Distributors h0 ON h0.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_BatchItems;
CREATE OR REPLACE VIEW Vi_SPC_BatchItems AS
SELECT
j.Id,
j.BatchId,
j.ItemOrder,
j.TransportReqRideId,
j.TransportReqDeliveryId,
j.Discriminator,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted
FROM H_TransportBatchItems j
WHERE j.RecordDeleted IS NULL;

-- ===== transport.deliveries (H_TransportReqDeliveries) =====
DROP VIEW IF EXISTS Vi_SPC_DeliveryListSummary;
CREATE OR REPLACE VIEW Vi_SPC_DeliveryListSummary AS
SELECT
m.Id,
m.IsEditable,
m.CustomerId,
m.DistributorId,
m.CVOId,
m.FromContactLocationId,
m.ToContactLocationId,
m.PickupAfterDateTime,
m.PickupAfterDateTime_UTC,
m.PickupBeforeDateTime,
m.PickupBeforeDateTime_UTC,
m.DropOffAfterDateTime,
m.DropOffAfterDateTime_UTC,
m.DropOffBeforeDateTime,
m.DropOffBeforeDateTime_UTC,
m.VehicleType,
m.VehicleProfileSubType,
m.ServiceClass,
m.ActionOnAbsentReceiver,
m.Comments,
m.FareAtSubmission,
m.PromoCode,
m.PaymentCategory,
m.PaymentMethod,
m.PaidAt_UTC,
m.Status,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS DistributorTitle,
  h2e.Title AS CVOTitle,
  h4e.Title AS CustomerTitle,
  (SELECT COUNT(*) FROM H_TransportBatchItems cc WHERE cc.TransportReqDeliveryId = m.Id AND cc.RecordDeleted IS NULL) AS BatchItemsCount,
  (SELECT COUNT(*) FROM H_TransportReqDeliveryAddons cc WHERE cc.TransportReqDeliveryId = m.Id AND cc.RecordDeleted IS NULL) AS ReqDeliveryAddonsCount,
  (SELECT COUNT(*) FROM H_TransportReqDeliveryGoods cc WHERE cc.ReqDeliveryId = m.Id AND cc.RecordDeleted IS NULL) AS ReqDeliveryGoodsCount
FROM H_TransportReqDeliveries m
  LEFT JOIN H_Synced_Distributors h0 ON h0.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_CVOs h2 ON h2.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_TransportCustomers h4 ON h4.Id = m.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h4e ON h4e.Id = h4.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DeliveryProfile;
CREATE OR REPLACE VIEW Vi_SPC_DeliveryProfile AS
SELECT
m.Id,
m.IsEditable,
m.CustomerId,
m.DistributorId,
m.CVOId,
m.FromContactLocationId,
m.ToContactLocationId,
m.PickupAfterDateTime,
m.PickupAfterDateTime_UTC,
m.PickupBeforeDateTime,
m.PickupBeforeDateTime_UTC,
m.DropOffAfterDateTime,
m.DropOffAfterDateTime_UTC,
m.DropOffBeforeDateTime,
m.DropOffBeforeDateTime_UTC,
m.VehicleType,
m.VehicleProfileSubType,
m.ServiceClass,
m.ActionOnAbsentReceiver,
m.Comments,
m.FareAtSubmission,
m.PromoCode,
m.PaymentCategory,
m.PaymentMethod,
m.PaidAt_UTC,
m.Status,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS DistributorTitle,
  h2e.Title AS CVOTitle,
  h4e.Title AS CustomerTitle
FROM H_TransportReqDeliveries m
  LEFT JOIN H_Synced_Distributors h0 ON h0.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_CVOs h2 ON h2.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_TransportCustomers h4 ON h4.Id = m.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h4e ON h4e.Id = h4.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DeliveryBatchItems;
CREATE OR REPLACE VIEW Vi_SPC_DeliveryBatchItems AS
SELECT
j.Id,
j.BatchId,
j.ItemOrder,
j.TransportReqRideId,
j.TransportReqDeliveryId,
j.Discriminator,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted
FROM H_TransportBatchItems j
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DeliveryReqDeliveryAddons;
CREATE OR REPLACE VIEW Vi_SPC_DeliveryReqDeliveryAddons AS
SELECT
j.Id,
j.TransportReqDeliveryId,
j.CalculationItem,
j.CalculationUnit,
j.Amount,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted
FROM H_TransportReqDeliveryAddons j
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DeliveryReqDeliveryGoods;
CREATE OR REPLACE VIEW Vi_SPC_DeliveryReqDeliveryGoods AS
SELECT
j.Id,
j.ReqDeliveryId,
j.CustomerGoodId,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h1.Title AS CustomerGoodTitle
FROM H_TransportReqDeliveryGoods j
  LEFT JOIN H_TransportCustomerMasterGoods h1 ON h1.Id = j.CustomerGoodId
WHERE j.RecordDeleted IS NULL;

-- ===== transport.dispatch (H_TransportTransacts) =====
DROP VIEW IF EXISTS Vi_SPC_DispatchListSummary;
CREATE OR REPLACE VIEW Vi_SPC_DispatchListSummary AS
SELECT
m.Id,
m.FMS_OvId,
m.BatchId,
m.PickupZoneId,
m.CVOId,
m.VehicleId,
m.DriverId,
m.CurrentStatus,
m.OfferType,
m.PaidTripFare,
m.PaidAddonFee,
m.AppliedDiscount,
m.PaidTip,
m.PaidToll,
m.ActualTotalFareAtTripEnd,
m.DriverAgreedFareAmount,
m.EnforceItemsCreationSequense,
m.PaymentTransactionNumber,
m.ExtraData,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h3e.Title AS CVOTitle,
  h4.Title AS PickupZoneTitle,
  (SELECT COUNT(*) FROM H_TransportTransactItems cc WHERE cc.TransportTransactId = m.Id) AS TransactItemsCount,
  (SELECT COUNT(*) FROM H_TransportTransactStages cc WHERE cc.TransportTransactId = m.Id) AS TransactStagesCount
FROM H_TransportTransacts m
  LEFT JOIN H_Synced_CVOs h3 ON h3.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN _ZoneBases h4 ON h4.Id = m.PickupZoneId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DispatchProfile;
CREATE OR REPLACE VIEW Vi_SPC_DispatchProfile AS
SELECT
m.Id,
m.FMS_OvId,
m.BatchId,
m.PickupZoneId,
m.CVOId,
m.VehicleId,
m.DriverId,
m.CurrentStatus,
m.OfferType,
m.PaidTripFare,
m.PaidAddonFee,
m.AppliedDiscount,
m.PaidTip,
m.PaidToll,
m.ActualTotalFareAtTripEnd,
m.DriverAgreedFareAmount,
m.EnforceItemsCreationSequense,
m.PaymentTransactionNumber,
m.ExtraData,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h3e.Title AS CVOTitle,
  h4.Title AS PickupZoneTitle
FROM H_TransportTransacts m
  LEFT JOIN H_Synced_CVOs h3 ON h3.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN _ZoneBases h4 ON h4.Id = m.PickupZoneId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DispatchTransactItems;
CREATE OR REPLACE VIEW Vi_SPC_DispatchTransactItems AS
SELECT
j.Id,
j.TransportTransactId,
j.TransportBatchItemId,
j.CurrentStatus,
j.AggregatedComments,
j.ImageUri,
j.SignatureUri,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy
FROM H_TransportTransactItems j;

DROP VIEW IF EXISTS Vi_SPC_DispatchTransactStages;
CREATE OR REPLACE VIEW Vi_SPC_DispatchTransactStages AS
SELECT
j.Id,
j.TimeStamp_UTC,
j.TransportTransactId,
j.Status,
j.ModifiedBy
FROM H_TransportTransactStages j;

-- ===== transport.rides (H_TransportReqRides) =====
DROP VIEW IF EXISTS Vi_SPC_RideListSummary;
CREATE OR REPLACE VIEW Vi_SPC_RideListSummary AS
SELECT
m.Id,
m.IsEditable,
m.CustomerId,
m.DistributorId,
m.CVOId,
m.FromContactLocationId,
m.ToContactLocationId,
m.PickupAfterDateTime,
m.PickupAfterDateTime_UTC,
m.PickupBeforeDateTime,
m.PickupBeforeDateTime_UTC,
m.DropOffAfterDateTime,
m.DropOffAfterDateTime_UTC,
m.DropOffBeforeDateTime,
m.DropOffBeforeDateTime_UTC,
m.VehicleType,
m.VehicleProfileSubType,
m.ServiceClass,
m.ServiceCategory,
m.TotalRequiredSeats,
m.NumberOfLuggages,
m.FeaturesJSON,
m.Comments,
m.FareAtSubmission,
m.PromoCode,
m.PaymentCategory,
m.PaymentMethod,
m.PaidAt_UTC,
m.HubCarrierInfo,
m.Status,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h1e.Title AS CVOTitle,
  h2e.Title AS CustomerTitle,
  h3e.Title AS DistributorTitle,
  (SELECT COUNT(*) FROM H_TransportBatchItems cc WHERE cc.TransportReqRideId = m.Id AND cc.RecordDeleted IS NULL) AS BatchItemsCount,
  (SELECT COUNT(*) FROM H_TransportReqRideAddons cc WHERE cc.TransportReqRideId = m.Id AND cc.RecordDeleted IS NULL) AS ReqRideAddonsCount,
  (SELECT COUNT(*) FROM H_TransportReqRidePassengers cc WHERE cc.ReqRideId = m.Id AND cc.RecordDeleted IS NULL) AS ReqRidePassengersCount
FROM H_TransportReqRides m
  LEFT JOIN H_Synced_CVOs h1 ON h1.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
  LEFT JOIN H_TransportCustomers h2 ON h2.Id = m.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_Synced_Distributors h3 ON h3.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h3e ON h3e.Id = h3.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RideProfile;
CREATE OR REPLACE VIEW Vi_SPC_RideProfile AS
SELECT
m.Id,
m.IsEditable,
m.CustomerId,
m.DistributorId,
m.CVOId,
m.FromContactLocationId,
m.ToContactLocationId,
m.PickupAfterDateTime,
m.PickupAfterDateTime_UTC,
m.PickupBeforeDateTime,
m.PickupBeforeDateTime_UTC,
m.DropOffAfterDateTime,
m.DropOffAfterDateTime_UTC,
m.DropOffBeforeDateTime,
m.DropOffBeforeDateTime_UTC,
m.VehicleType,
m.VehicleProfileSubType,
m.ServiceClass,
m.ServiceCategory,
m.TotalRequiredSeats,
m.NumberOfLuggages,
m.FeaturesJSON,
m.Comments,
m.FareAtSubmission,
m.PromoCode,
m.PaymentCategory,
m.PaymentMethod,
m.PaidAt_UTC,
m.HubCarrierInfo,
m.Status,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h1e.Title AS CVOTitle,
  h2e.Title AS CustomerTitle,
  h3e.Title AS DistributorTitle
FROM H_TransportReqRides m
  LEFT JOIN H_Synced_CVOs h1 ON h1.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
  LEFT JOIN H_TransportCustomers h2 ON h2.Id = m.CustomerId
  LEFT JOIN H_AAA_Synced_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_Synced_Distributors h3 ON h3.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h3e ON h3e.Id = h3.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RideBatchItems;
CREATE OR REPLACE VIEW Vi_SPC_RideBatchItems AS
SELECT
j.Id,
j.BatchId,
j.ItemOrder,
j.TransportReqRideId,
j.TransportReqDeliveryId,
j.Discriminator,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted
FROM H_TransportBatchItems j
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RideReqRideAddons;
CREATE OR REPLACE VIEW Vi_SPC_RideReqRideAddons AS
SELECT
j.Id,
j.TransportReqRideId,
j.CalculationItem,
j.CalculationUnit,
j.Amount,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted
FROM H_TransportReqRideAddons j
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RideReqRidePassengers;
CREATE OR REPLACE VIEW Vi_SPC_RideReqRidePassengers AS
SELECT
j.Id,
j.ReqRideId,
j.PassengerId,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted
FROM H_TransportReqRidePassengers j
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RideTransactItemStages;
CREATE OR REPLACE VIEW Vi_SPC_RideTransactItemStages AS
SELECT
j.Id,
j.TimeStamp_UTC,
j.TransactStepId,
j.Status,
j.Comments,
j.ImageUri,
j.SignatureUri,
j.ModifiedBy
FROM H_TransportTransactItemStages j;

-- ===== transport.setup.contact-locations (H_TransportContactLocations) =====
DROP VIEW IF EXISTS Vi_SPC_ContactLocationListSummary;
CREATE OR REPLACE VIEW Vi_SPC_ContactLocationListSummary AS
SELECT
m.Id,
m.ContactId,
m.FavAdrLabel,
m.LocationId,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS LocationTitle,
  h1e.Title AS ContactTitle
FROM H_TransportContactLocations m
  LEFT JOIN H_TransportLocations h0 ON h0.Id = m.LocationId
  LEFT JOIN H_TransportContactRegistry h1 ON h1.Id = m.ContactId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.PossibleEntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_ContactLocationProfile;
CREATE OR REPLACE VIEW Vi_SPC_ContactLocationProfile AS
SELECT
m.Id,
m.ContactId,
m.FavAdrLabel,
m.LocationId,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS LocationTitle,
  h1e.Title AS ContactTitle
FROM H_TransportContactLocations m
  LEFT JOIN H_TransportLocations h0 ON h0.Id = m.LocationId
  LEFT JOIN H_TransportContactRegistry h1 ON h1.Id = m.ContactId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.PossibleEntityId
WHERE m.RecordDeleted IS NULL;

-- ===== transport.setup.fare-base-inclutions (H_TransportFareBaseInclutions) =====
DROP VIEW IF EXISTS Vi_SPC_FareBaseInclutionListSummary;
CREATE OR REPLACE VIEW Vi_SPC_FareBaseInclutionListSummary AS
SELECT
m.Id,
m.DistributorId,
m.CVOId,
m.TransportCategory,
m.ServiceCategory,
m.VehicleType,
m.ServiceClass,
m.IncludedSeatCounts,
m.IncludedLuggageCounts,
m.IncludedParcelCounts,
m.IncludedWeightKg,
m.IncludedVolumeCubicM,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS CVOTitle,
  h1e.Title AS DistributorTitle
FROM H_TransportFareBaseInclutions m
  LEFT JOIN H_Synced_CVOs h0 ON h0.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_Distributors h1 ON h1.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_FareBaseInclutionProfile;
CREATE OR REPLACE VIEW Vi_SPC_FareBaseInclutionProfile AS
SELECT
m.Id,
m.DistributorId,
m.CVOId,
m.TransportCategory,
m.ServiceCategory,
m.VehicleType,
m.ServiceClass,
m.IncludedSeatCounts,
m.IncludedLuggageCounts,
m.IncludedParcelCounts,
m.IncludedWeightKg,
m.IncludedVolumeCubicM,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS CVOTitle,
  h1e.Title AS DistributorTitle
FROM H_TransportFareBaseInclutions m
  LEFT JOIN H_Synced_CVOs h0 ON h0.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_Distributors h1 ON h1.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE m.RecordDeleted IS NULL;

-- ===== transport.setup.fare-by-geo-fence (H_TransportFareByGeoFence) =====
DROP VIEW IF EXISTS Vi_SPC_FareByGeoFenceListSummary;
CREATE OR REPLACE VIEW Vi_SPC_FareByGeoFenceListSummary AS
SELECT
m.Id,
m.TransportFareCalculationId,
m.SourceGeoFenceBaseId,
m.DestinationGeoFenceBaseId,
m.BaseFare,
  h1.Title AS DestinationGeoFenceBaseTitle,
  h2.Title AS SourceGeoFenceBaseTitle
FROM H_TransportFareByGeoFence m
  LEFT JOIN H_TransportGeoFenceBases h1 ON h1.Id = m.DestinationGeoFenceBaseId
  LEFT JOIN H_TransportGeoFenceBases h2 ON h2.Id = m.SourceGeoFenceBaseId;

DROP VIEW IF EXISTS Vi_SPC_FareByGeoFenceProfile;
CREATE OR REPLACE VIEW Vi_SPC_FareByGeoFenceProfile AS
SELECT
m.Id,
m.TransportFareCalculationId,
m.SourceGeoFenceBaseId,
m.DestinationGeoFenceBaseId,
m.BaseFare,
  h1.Title AS DestinationGeoFenceBaseTitle,
  h2.Title AS SourceGeoFenceBaseTitle
FROM H_TransportFareByGeoFence m
  LEFT JOIN H_TransportGeoFenceBases h1 ON h1.Id = m.DestinationGeoFenceBaseId
  LEFT JOIN H_TransportGeoFenceBases h2 ON h2.Id = m.SourceGeoFenceBaseId;

-- ===== transport.setup.fare-by-zone (H_TransportFareByZone) =====
DROP VIEW IF EXISTS Vi_SPC_FareByZoneListSummary;
CREATE OR REPLACE VIEW Vi_SPC_FareByZoneListSummary AS
SELECT
m.Id,
m.TransportFareCalculationId,
m.SourceGeoFenceBaseId,
m.DestinationGeoFenceBaseId,
m.BaseFare,
  h0.Title AS DestinationGeoFenceBaseTitle,
  h1.Title AS SourceGeoFenceBaseTitle
FROM H_TransportFareByZone m
  LEFT JOIN H_TransportGeoFenceBases h0 ON h0.Id = m.DestinationGeoFenceBaseId
  LEFT JOIN H_TransportGeoFenceBases h1 ON h1.Id = m.SourceGeoFenceBaseId;

DROP VIEW IF EXISTS Vi_SPC_FareByZoneProfile;
CREATE OR REPLACE VIEW Vi_SPC_FareByZoneProfile AS
SELECT
m.Id,
m.TransportFareCalculationId,
m.SourceGeoFenceBaseId,
m.DestinationGeoFenceBaseId,
m.BaseFare,
  h0.Title AS DestinationGeoFenceBaseTitle,
  h1.Title AS SourceGeoFenceBaseTitle
FROM H_TransportFareByZone m
  LEFT JOIN H_TransportGeoFenceBases h0 ON h0.Id = m.DestinationGeoFenceBaseId
  LEFT JOIN H_TransportGeoFenceBases h1 ON h1.Id = m.SourceGeoFenceBaseId;

-- ===== transport.setup.fare-calculations (H_TransportFareCalculations) =====
DROP VIEW IF EXISTS Vi_SPC_FareCalculationListSummary;
CREATE OR REPLACE VIEW Vi_SPC_FareCalculationListSummary AS
SELECT
m.Id,
m.DistributorId,
m.CVOId,
m.TransportCategory,
m.ServiceCategory,
m.VehicleType,
m.ServiceClass,
m.CalculationItem,
m.CalculationType,
m.CalculateMethod,
m.CalculationPriority,
m.CalculationUnit,
m.UnitAmount,
m.Price,
m.PriceTable,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS DistributorTitle,
  h1e.Title AS CVOTitle
FROM H_TransportFareCalculations m
  LEFT JOIN H_Synced_Distributors h0 ON h0.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_CVOs h1 ON h1.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_FareCalculationProfile;
CREATE OR REPLACE VIEW Vi_SPC_FareCalculationProfile AS
SELECT
m.Id,
m.DistributorId,
m.CVOId,
m.TransportCategory,
m.ServiceCategory,
m.VehicleType,
m.ServiceClass,
m.CalculationItem,
m.CalculationType,
m.CalculateMethod,
m.CalculationPriority,
m.CalculationUnit,
m.UnitAmount,
m.Price,
m.PriceTable,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS DistributorTitle,
  h1e.Title AS CVOTitle
FROM H_TransportFareCalculations m
  LEFT JOIN H_Synced_Distributors h0 ON h0.Id = m.DistributorId
  LEFT JOIN H_AAA_Synced_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_Synced_CVOs h1 ON h1.Id = m.CVOId
  LEFT JOIN H_AAA_Synced_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE m.RecordDeleted IS NULL;

-- ===== transport.setup.geo-fence-bases (H_TransportGeoFenceBases) =====
DROP VIEW IF EXISTS Vi_SPC_GeoFenceBaseListSummary;
CREATE OR REPLACE VIEW Vi_SPC_GeoFenceBaseListSummary AS
SELECT
m.Id,
m.Code,
m.Title,
m.Coordinates,
m.Order,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_TransportGeoFenceBases m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_GeoFenceBaseProfile;
CREATE OR REPLACE VIEW Vi_SPC_GeoFenceBaseProfile AS
SELECT
m.Id,
m.Code,
m.Title,
m.Coordinates,
m.Order,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted
FROM H_TransportGeoFenceBases m
WHERE m.RecordDeleted IS NULL;

-- ===== transport.setup.locations (H_TransportLocations) =====
DROP VIEW IF EXISTS Vi_SPC_LocationListSummary;
CREATE OR REPLACE VIEW Vi_SPC_LocationListSummary AS
SELECT
m.Id,
m.Title,
m.Latitude,
m.Longitude,
m.Address,
m.City,
m.Province,
m.PostalCode,
m.PlaceId,
m.GoogleFullAddress,
m.CreatedAt_UTC,
m.CreatedBy,
m.RecordDeleted
FROM H_TransportLocations m
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_LocationProfile;
CREATE OR REPLACE VIEW Vi_SPC_LocationProfile AS
SELECT
m.Id,
m.Title,
m.Latitude,
m.Longitude,
m.Address,
m.City,
m.Province,
m.PostalCode,
m.PlaceId,
m.GoogleFullAddress,
m.CreatedAt_UTC,
m.CreatedBy,
m.RecordDeleted
FROM H_TransportLocations m
WHERE m.RecordDeleted IS NULL;

