-- GENERATED by builder/stages/s4-spc-emit.mjs — DO NOT EDIT.
-- Scope: GD. Apply each <backend>.spc-views.sql to THAT backend's database (views live with their tables).
-- Field rules: _fsx verbatim · ENUM ints raw (grid maps) · own-FK label hydration · per-relationship counts · overlay enrichment (§8).
-- Idempotent: safe to re-run. Order: helpers → views → authored.


-- ========== shared helpers ==========
DROP VIEW IF EXISTS Vi_SPC_PermitLatestStatus;
CREATE OR REPLACE VIEW Vi_SPC_PermitLatestStatus AS SELECT ranked.Id AS PermitStatusId, ranked.PermitId, ranked.ExpiryDate_UTC, ranked.ConditionENUM, ranked.ConditionEndDate_UTC, ranked.MediaRecordKey, ranked.RecordKey, ranked.CreatedAt_UTC, ranked.CreatedBy, ranked.ModifiedAt_UTC, ranked.ModifiedBy, CASE WHEN ranked.ConditionENUM = 0 THEN 'Archived' WHEN ranked.ConditionENUM = 4 THEN 'Revoked' WHEN ranked.ExpiryDate_UTC < UTC_TIMESTAMP() THEN 'Expired' WHEN ranked.ConditionENUM = 1 THEN 'Suspended' WHEN ranked.ConditionENUM IS NULL OR ranked.ConditionENUM IN (2,3) THEN 'Valid' ELSE 'Unknown' END AS StatusCategory, CASE ranked.ConditionENUM WHEN 0 THEN 'Archived' WHEN 1 THEN 'TempSuspended' WHEN 2 THEN 'TempValid' WHEN 3 THEN 'TempExtended' WHEN 4 THEN 'Revoked' ELSE 'Normal' END AS ConditionTitle, CASE WHEN ranked.ConditionENUM = 0 THEN NULL WHEN ranked.ConditionENUM = 4 THEN FALSE WHEN ranked.ExpiryDate_UTC < UTC_TIMESTAMP() THEN FALSE WHEN ranked.ConditionENUM = 1 THEN FALSE WHEN ranked.ConditionENUM IS NULL OR ranked.ConditionENUM IN (2,3) THEN TRUE ELSE NULL END AS IsCurrentlyValid, DATEDIFF(ranked.ExpiryDate_UTC, UTC_TIMESTAMP()) AS DaysUntilExpiry, CASE WHEN ranked.ExpiryDate_UTC IS NULL THEN NULL WHEN ranked.ExpiryDate_UTC < UTC_TIMESTAMP() THEN FALSE WHEN DATEDIFF(ranked.ExpiryDate_UTC, UTC_TIMESTAMP()) <= 30 THEN TRUE ELSE FALSE END AS IsExpiringSoon FROM (SELECT ps.*, ROW_NUMBER() OVER (PARTITION BY ps.PermitId ORDER BY ps.CreatedAt_UTC DESC, ps.Id DESC) AS RowNum FROM H_PermitStatuses ps WHERE ps.RecordDeleted IS NULL) AS ranked WHERE ranked.RowNum = 1;

-- ===== definitions.access.users (H_AAA_Synced_UserInfo) =====
DROP VIEW IF EXISTS Vi_SPC_UserEntityRoles;
CREATE OR REPLACE VIEW Vi_SPC_UserEntityRoles AS
SELECT
j.Id,
j.UserId,
j.EntityRoleId,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0.Title AS EntityRoleTitle,
  h1.Firstname_fsx,
  h1.Lastname_fsx,
  h1.Username,
  h1.Email_fsx,
  h1.CellPhone_fsx
FROM H_AAA_UserEntityRoles j
  LEFT JOIN H_AAA_EntityRoles h0 ON h0.Id = j.EntityRoleId
  LEFT JOIN H_AAA_Synced_UserInfo h1 ON h1.Id = j.UserId
WHERE j.RecordDeleted IS NULL;

-- ===== definitions.cvos (H_CVOs) =====
DROP VIEW IF EXISTS Vi_SPC_CVOListSummary;
CREATE OR REPLACE VIEW Vi_SPC_CVOListSummary AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS EntityTitle
FROM H_CVOs m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CVOProfile;
CREATE OR REPLACE VIEW Vi_SPC_CVOProfile AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS EntityTitle
FROM H_CVOs m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CVODrivers;
CREATE OR REPLACE VIEW Vi_SPC_CVODrivers AS
SELECT
  j.Id AS LinkId,
  j.CVOId,
  j.DriverId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.UserId,
rel.PersonCVOId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Firstname_fsx,
  rh0.Lastname_fsx,
  rh0.Username,
  rh0.Email_fsx,
  rh0.CellPhone_fsx,
  rh1e.Title AS PersonCVOTitle
FROM H_CVODrivers j
  JOIN H_Drivers rel ON rel.Id = j.DriverId
  LEFT JOIN H_AAA_Synced_UserInfo rh0 ON rh0.Id = rel.UserId
  LEFT JOIN H_CVOs rh1 ON rh1.Id = rel.PersonCVOId
  LEFT JOIN H_AAA_EntityProfile rh1e ON rh1e.Id = rh1.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CVOServices;
CREATE OR REPLACE VIEW Vi_SPC_CVOServices AS
SELECT
j.Id,
j.CVOId,
j.ServiceId,
j.ServiceCategory,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h1e.Title AS CVOTitle
FROM H_CVOServices j
  LEFT JOIN H_CVOs h1 ON h1.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CVOVehicles;
CREATE OR REPLACE VIEW Vi_SPC_CVOVehicles AS
SELECT
  j.Id AS LinkId,
  j.CVOId,
  j.VehicleId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.Plate,
rel.VIN,
rel.Make,
rel.Model,
rel.Province,
rel.Color,
rel.Year,
rel.TransportCategory,
rel.Cargo_Height,
rel.Cargo_Weight,
rel.Cargo_Length,
rel.Cargo_Width,
rel.Capacity_Passengers,
rel.Capacity_Luggage,
rel.VehicleType,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted
FROM H_CVOVehicles j
  JOIN H_VehicleProfile rel ON rel.Id = j.VehicleId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CVODistributors;
CREATE OR REPLACE VIEW Vi_SPC_CVODistributors AS
SELECT
  j.Id AS LinkId,
  j.DistributorId,
  j.CVOId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Title AS EntityTitle
FROM H_DistributorCVOs j
  JOIN H_Distributors rel ON rel.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_CVOPermits;
CREATE OR REPLACE VIEW Vi_SPC_CVOPermits AS
SELECT
j.Id,
j.HUBId,
j.DistributorId,
j.CVOId,
j.VehicleId,
j.DriverId,
j.ActENUM,
j.PermitIssuerId,
j.PermitTypeId,
j.Code,
j.ServiceCategory,
j.IssuedDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h2e.Title AS HUBTitle,
  h3e.Title AS CVOTitle,
  h5e.Title AS DistributorTitle,
  h6.Title AS PermitTypeTitle,
  h7e.Title AS PermitIssuerTitle
FROM H_Permits j
  LEFT JOIN H_HUBs h2 ON h2.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_CVOs h3 ON h3.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_Distributors h5 ON h5.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_PermitTypes h6 ON h6.Id = j.PermitTypeId
  LEFT JOIN H_PermitIssuers h7 ON h7.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h7e ON h7e.Id = h7.EntityId
WHERE j.RecordDeleted IS NULL;

-- ===== definitions.distributors (H_Distributors) =====
DROP VIEW IF EXISTS Vi_SPC_DistributorListSummary;
CREATE OR REPLACE VIEW Vi_SPC_DistributorListSummary AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS EntityTitle
FROM H_Distributors m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DistributorProfile;
CREATE OR REPLACE VIEW Vi_SPC_DistributorProfile AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS EntityTitle
FROM H_Distributors m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DistributorCVOs;
CREATE OR REPLACE VIEW Vi_SPC_DistributorCVOs AS
SELECT
  j.Id AS LinkId,
  j.DistributorId,
  j.CVOId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Title AS EntityTitle
FROM H_DistributorCVOs j
  JOIN H_CVOs rel ON rel.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DistributorDrivers;
CREATE OR REPLACE VIEW Vi_SPC_DistributorDrivers AS
SELECT
  j.Id AS LinkId,
  j.DistributorId,
  j.DriverId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.UserId,
rel.PersonCVOId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Firstname_fsx,
  rh0.Lastname_fsx,
  rh0.Username,
  rh0.Email_fsx,
  rh0.CellPhone_fsx,
  rh1e.Title AS PersonCVOTitle
FROM H_DistributorDrivers j
  JOIN H_Drivers rel ON rel.Id = j.DriverId
  LEFT JOIN H_AAA_Synced_UserInfo rh0 ON rh0.Id = rel.UserId
  LEFT JOIN H_CVOs rh1 ON rh1.Id = rel.PersonCVOId
  LEFT JOIN H_AAA_EntityProfile rh1e ON rh1e.Id = rh1.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DistributorHUBs;
CREATE OR REPLACE VIEW Vi_SPC_DistributorHUBs AS
SELECT
  j.Id AS LinkId,
  j.DistributorId,
  j.HUBId,
  j.ParticipationCategory,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Title AS EntityTitle
FROM H_HUBDistributors j
  JOIN H_HUBs rel ON rel.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DistributorPermits;
CREATE OR REPLACE VIEW Vi_SPC_DistributorPermits AS
SELECT
j.Id,
j.HUBId,
j.DistributorId,
j.CVOId,
j.VehicleId,
j.DriverId,
j.ActENUM,
j.PermitIssuerId,
j.PermitTypeId,
j.Code,
j.ServiceCategory,
j.IssuedDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h2e.Title AS HUBTitle,
  h3e.Title AS CVOTitle,
  h5e.Title AS DistributorTitle,
  h6.Title AS PermitTypeTitle,
  h7e.Title AS PermitIssuerTitle
FROM H_Permits j
  LEFT JOIN H_HUBs h2 ON h2.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_CVOs h3 ON h3.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_Distributors h5 ON h5.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_PermitTypes h6 ON h6.Id = j.PermitTypeId
  LEFT JOIN H_PermitIssuers h7 ON h7.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h7e ON h7e.Id = h7.EntityId
WHERE j.RecordDeleted IS NULL;

-- ===== definitions.drivers (H_Drivers) =====
DROP VIEW IF EXISTS Vi_SPC_DriverListSummary;
CREATE OR REPLACE VIEW Vi_SPC_DriverListSummary AS
SELECT
m.Id,
m.UserId,
m.PersonCVOId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Firstname_fsx,
  h0.Lastname_fsx,
  h0.Username,
  h0.Email_fsx,
  h0.CellPhone_fsx,
  h1e.Title AS PersonCVOTitle,
  (SELECT p.Code FROM H_Permits p WHERE p.DriverId = m.Id AND p.PermitTypeId = 5001 AND p.RecordDeleted IS NULL ORDER BY p.IssuedDate_UTC DESC, p.Id DESC LIMIT 1) AS DriverLicense,
  (SELECT pls.ExpiryDate_UTC FROM H_Permits p LEFT JOIN Vi_SPC_PermitLatestStatus pls ON pls.PermitId = p.Id WHERE p.DriverId = m.Id AND p.PermitTypeId = 5001 AND p.RecordDeleted IS NULL ORDER BY p.IssuedDate_UTC DESC, p.Id DESC LIMIT 1) AS DriverLicenseExpiry,
  (SELECT COALESCE(pls.StatusCategory,'Unknown') FROM H_Permits p LEFT JOIN Vi_SPC_PermitLatestStatus pls ON pls.PermitId = p.Id WHERE p.DriverId = m.Id AND p.PermitTypeId = 5001 AND p.RecordDeleted IS NULL ORDER BY p.IssuedDate_UTC DESC, p.Id DESC LIMIT 1) AS DriverLicenseStatus,
  (SELECT CASE WHEN COUNT(*) = 0 THEN 'All Valid' ELSE CONCAT('Invalid (', COUNT(*), ')') END FROM H_Permits p JOIN Vi_SPC_PermitLatestStatus pls ON pls.PermitId = p.Id WHERE p.DriverId = m.Id AND pls.IsCurrentlyValid = FALSE AND p.RecordDeleted IS NULL) AS PermitStatus,
  (SELECT MAX(pls.ExpiryDate_UTC) FROM H_Permits p JOIN Vi_SPC_PermitLatestStatus pls ON pls.PermitId = p.Id WHERE p.DriverId = m.Id AND pls.IsCurrentlyValid = TRUE AND p.RecordDeleted IS NULL) AS NextValidPermitExpiry,
  (SELECT JSON_ARRAYAGG(b.VehicleTypeTitle) FROM (SELECT vt.Title AS VehicleTypeTitle FROM H_DriverPermitVehicleTypes dpvt JOIN H_Permits p ON p.Id = dpvt.PermitId JOIN H_ENUM_VehicleTypes vt ON vt.ENUM = dpvt.VehicleType WHERE p.DriverId = m.Id AND p.PermitTypeId = 5001 AND dpvt.RecordDeleted IS NULL AND p.RecordDeleted IS NULL ORDER BY vt.Title, dpvt.Id LIMIT 3) AS b) AS LicensedVehicleTypeBadges
FROM H_Drivers m
  LEFT JOIN H_AAA_Synced_UserInfo h0 ON h0.Id = m.UserId
  LEFT JOIN H_CVOs h1 ON h1.Id = m.PersonCVOId
  LEFT JOIN H_AAA_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DriverProfile;
CREATE OR REPLACE VIEW Vi_SPC_DriverProfile AS
SELECT
m.Id,
m.UserId,
m.PersonCVOId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Firstname_fsx,
  h0.Lastname_fsx,
  h0.Username,
  h0.Email_fsx,
  h0.CellPhone_fsx,
  h1e.Title AS PersonCVOTitle
FROM H_Drivers m
  LEFT JOIN H_AAA_Synced_UserInfo h0 ON h0.Id = m.UserId
  LEFT JOIN H_CVOs h1 ON h1.Id = m.PersonCVOId
  LEFT JOIN H_AAA_EntityProfile h1e ON h1e.Id = h1.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DriverCVOs;
CREATE OR REPLACE VIEW Vi_SPC_DriverCVOs AS
SELECT
  j.Id AS LinkId,
  j.CVOId,
  j.DriverId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Title AS EntityTitle
FROM H_CVODrivers j
  JOIN H_CVOs rel ON rel.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DriverDistributors;
CREATE OR REPLACE VIEW Vi_SPC_DriverDistributors AS
SELECT
  j.Id AS LinkId,
  j.DistributorId,
  j.DriverId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Title AS EntityTitle
FROM H_DistributorDrivers j
  JOIN H_Distributors rel ON rel.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DriverPermits;
CREATE OR REPLACE VIEW Vi_SPC_DriverPermits AS
SELECT
j.Id,
j.HUBId,
j.DistributorId,
j.CVOId,
j.VehicleId,
j.DriverId,
j.ActENUM,
j.PermitIssuerId,
j.PermitTypeId,
j.Code,
j.ServiceCategory,
j.IssuedDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h2e.Title AS HUBTitle,
  h3e.Title AS CVOTitle,
  h5e.Title AS DistributorTitle,
  h6.Title AS PermitTypeTitle,
  h7e.Title AS PermitIssuerTitle
FROM H_Permits j
  LEFT JOIN H_HUBs h2 ON h2.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_CVOs h3 ON h3.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_Distributors h5 ON h5.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_PermitTypes h6 ON h6.Id = j.PermitTypeId
  LEFT JOIN H_PermitIssuers h7 ON h7.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h7e ON h7e.Id = h7.EntityId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_DriverVehicles;
CREATE OR REPLACE VIEW Vi_SPC_DriverVehicles AS
SELECT
  j.Id AS LinkId,
  j.VehicleId,
  j.DriverId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.Plate,
rel.VIN,
rel.Make,
rel.Model,
rel.Province,
rel.Color,
rel.Year,
rel.TransportCategory,
rel.Cargo_Height,
rel.Cargo_Weight,
rel.Cargo_Length,
rel.Cargo_Width,
rel.Capacity_Passengers,
rel.Capacity_Luggage,
rel.VehicleType,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted
FROM H_VehicleDrivers j
  JOIN H_VehicleProfile rel ON rel.Id = j.VehicleId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

-- ===== definitions.hubs (H_HUBs) =====
DROP VIEW IF EXISTS Vi_SPC_HUBListSummary;
CREATE OR REPLACE VIEW Vi_SPC_HUBListSummary AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS EntityTitle
FROM H_HUBs m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_HUBProfile;
CREATE OR REPLACE VIEW Vi_SPC_HUBProfile AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS EntityTitle
FROM H_HUBs m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_HUBDistributors;
CREATE OR REPLACE VIEW Vi_SPC_HUBDistributors AS
SELECT
  j.Id AS LinkId,
  j.DistributorId,
  j.HUBId,
  j.ParticipationCategory,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Title AS EntityTitle
FROM H_HUBDistributors j
  JOIN H_Distributors rel ON rel.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_HUBPermits;
CREATE OR REPLACE VIEW Vi_SPC_HUBPermits AS
SELECT
j.Id,
j.HUBId,
j.DistributorId,
j.CVOId,
j.VehicleId,
j.DriverId,
j.ActENUM,
j.PermitIssuerId,
j.PermitTypeId,
j.Code,
j.ServiceCategory,
j.IssuedDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h2e.Title AS HUBTitle,
  h3e.Title AS CVOTitle,
  h5e.Title AS DistributorTitle,
  h6.Title AS PermitTypeTitle,
  h7e.Title AS PermitIssuerTitle
FROM H_Permits j
  LEFT JOIN H_HUBs h2 ON h2.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_CVOs h3 ON h3.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_Distributors h5 ON h5.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_PermitTypes h6 ON h6.Id = j.PermitTypeId
  LEFT JOIN H_PermitIssuers h7 ON h7.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h7e ON h7e.Id = h7.EntityId
WHERE j.RecordDeleted IS NULL;

-- ===== definitions.requests (H_RequestStatuses) =====
DROP VIEW IF EXISTS Vi_SPC_RequestsApprovalListSummary;
CREATE OR REPLACE VIEW Vi_SPC_RequestsApprovalListSummary AS
SELECT
m.Id,
m.RequestId,
m.RequesteeUserId,
m.RequesteeEntityId,
m.RequesteeActENUM,
m.Status,
m.StatusReason,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS RequesteeEntityTitle,
  h1.Firstname_fsx,
  h1.Lastname_fsx,
  h1.Username,
  h1.Email_fsx,
  h1.CellPhone_fsx,
  h2e.Title AS RequestTitle
FROM H_RequestStatuses m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.RequesteeEntityId
  LEFT JOIN H_AAA_Synced_UserInfo h1 ON h1.Id = m.RequesteeUserId
  LEFT JOIN H_RequestBases h2 ON h2.Id = m.RequestId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.RequesterEntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RequestsApprovalProfile;
CREATE OR REPLACE VIEW Vi_SPC_RequestsApprovalProfile AS
SELECT
m.Id,
m.RequestId,
m.RequesteeUserId,
m.RequesteeEntityId,
m.RequesteeActENUM,
m.Status,
m.StatusReason,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS RequesteeEntityTitle,
  h1.Firstname_fsx,
  h1.Lastname_fsx,
  h1.Username,
  h1.Email_fsx,
  h1.CellPhone_fsx,
  h2e.Title AS RequestTitle
FROM H_RequestStatuses m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.RequesteeEntityId
  LEFT JOIN H_AAA_Synced_UserInfo h1 ON h1.Id = m.RequesteeUserId
  LEFT JOIN H_RequestBases h2 ON h2.Id = m.RequestId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.RequesterEntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_RequestsApprovalPermitStatusVerifications;
CREATE OR REPLACE VIEW Vi_SPC_RequestsApprovalPermitStatusVerifications AS
SELECT
j.Id,
j.PermitStatusId,
j.RequestStatusId,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h1e.Title AS RequestStatusTitle
FROM H_PermitStatusVerifications j
  LEFT JOIN H_RequestStatuses h1 ON h1.Id = j.RequestStatusId
  LEFT JOIN H_AAA_EntityProfile h1e ON h1e.Id = h1.RequesteeEntityId
WHERE j.RecordDeleted IS NULL;

-- ===== definitions.vehicles (H_VehicleProfile) =====
DROP VIEW IF EXISTS Vi_SPC_VehicleCVOs;
CREATE OR REPLACE VIEW Vi_SPC_VehicleCVOs AS
SELECT
  j.Id AS LinkId,
  j.CVOId,
  j.VehicleId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.EntityId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Title AS EntityTitle
FROM H_CVOVehicles j
  JOIN H_CVOs rel ON rel.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile rh0 ON rh0.Id = rel.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_VehiclePermits;
CREATE OR REPLACE VIEW Vi_SPC_VehiclePermits AS
SELECT
j.Id,
j.HUBId,
j.DistributorId,
j.CVOId,
j.VehicleId,
j.DriverId,
j.ActENUM,
j.PermitIssuerId,
j.PermitTypeId,
j.Code,
j.ServiceCategory,
j.IssuedDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h2e.Title AS HUBTitle,
  h3e.Title AS CVOTitle,
  h5e.Title AS DistributorTitle,
  h6.Title AS PermitTypeTitle,
  h7e.Title AS PermitIssuerTitle
FROM H_Permits j
  LEFT JOIN H_HUBs h2 ON h2.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_CVOs h3 ON h3.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_Distributors h5 ON h5.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_PermitTypes h6 ON h6.Id = j.PermitTypeId
  LEFT JOIN H_PermitIssuers h7 ON h7.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h7e ON h7e.Id = h7.EntityId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_VehicleDrivers;
CREATE OR REPLACE VIEW Vi_SPC_VehicleDrivers AS
SELECT
  j.Id AS LinkId,
  j.VehicleId,
  j.DriverId,
  j.HasRule,
  j.IssuedDate_UTC,
  j.ExpiryDate_UTC,
  j.RecordKey AS LinkRecordKey,
rel.Id,
rel.UserId,
rel.PersonCVOId,
rel.RecordKey,
rel.CreatedAt_UTC,
rel.CreatedBy,
rel.ModifiedAt_UTC,
rel.ModifiedBy,
rel.RecordDeleted,
  rh0.Firstname_fsx,
  rh0.Lastname_fsx,
  rh0.Username,
  rh0.Email_fsx,
  rh0.CellPhone_fsx,
  rh1e.Title AS PersonCVOTitle
FROM H_VehicleDrivers j
  JOIN H_Drivers rel ON rel.Id = j.DriverId
  LEFT JOIN H_AAA_Synced_UserInfo rh0 ON rh0.Id = rel.UserId
  LEFT JOIN H_CVOs rh1 ON rh1.Id = rel.PersonCVOId
  LEFT JOIN H_AAA_EntityProfile rh1e ON rh1e.Id = rh1.EntityId
WHERE j.RecordDeleted IS NULL AND rel.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_VehicleFeatures;
CREATE OR REPLACE VIEW Vi_SPC_VehicleFeatures AS
SELECT
j.Id,
j.FeatureId,
j.VehicleId,
j.HasRule,
j.IssuedDate_UTC,
j.ExpiryDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0.Title AS FeatureTitle
FROM H_VehicleFeatures j
  LEFT JOIN H_Features h0 ON h0.Id = j.FeatureId
WHERE j.RecordDeleted IS NULL;

-- ===== system.configurations.entity-configs (H_CFG_EntityConfigs) =====
DROP VIEW IF EXISTS Vi_SPC_EntityConfigListSummary;
CREATE OR REPLACE VIEW Vi_SPC_EntityConfigListSummary AS
SELECT
m.Id,
m.PermitIssuerId,
m.HUBId,
m.DistributorId,
m.CVOId,
m.VehicleId,
m.DriverId,
m.ActENUM,
m.ScenarioId,
m.ConfigBaseId,
m.Value,
m.IsOverridable,
m.Signature,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS PermitIssuerTitle,
  h1.Code AS ConfigBaseCode,
  h2e.Title AS DistributorTitle,
  h3e.Title AS ScenarioTitle,
  h5e.Title AS CVOTitle,
  h6e.Title AS HUBTitle
FROM H_CFG_EntityConfigs m
  LEFT JOIN H_PermitIssuers h0 ON h0.Id = m.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_CFG_ActionConfigBases h1 ON h1.Id = m.ConfigBaseId
  LEFT JOIN H_Distributors h2 ON h2.Id = m.DistributorId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_AAA_EntityScenarios h3 ON h3.Id = m.ScenarioId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_CVOs h5 ON h5.Id = m.CVOId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_HUBs h6 ON h6.Id = m.HUBId
  LEFT JOIN H_AAA_EntityProfile h6e ON h6e.Id = h6.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_EntityConfigProfile;
CREATE OR REPLACE VIEW Vi_SPC_EntityConfigProfile AS
SELECT
m.Id,
m.PermitIssuerId,
m.HUBId,
m.DistributorId,
m.CVOId,
m.VehicleId,
m.DriverId,
m.ActENUM,
m.ScenarioId,
m.ConfigBaseId,
m.Value,
m.IsOverridable,
m.Signature,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0e.Title AS PermitIssuerTitle,
  h1.Code AS ConfigBaseCode,
  h2e.Title AS DistributorTitle,
  h3e.Title AS ScenarioTitle,
  h5e.Title AS CVOTitle,
  h6e.Title AS HUBTitle
FROM H_CFG_EntityConfigs m
  LEFT JOIN H_PermitIssuers h0 ON h0.Id = m.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_CFG_ActionConfigBases h1 ON h1.Id = m.ConfigBaseId
  LEFT JOIN H_Distributors h2 ON h2.Id = m.DistributorId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_AAA_EntityScenarios h3 ON h3.Id = m.ScenarioId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_CVOs h5 ON h5.Id = m.CVOId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_HUBs h6 ON h6.Id = m.HUBId
  LEFT JOIN H_AAA_EntityProfile h6e ON h6e.Id = h6.EntityId
WHERE m.RecordDeleted IS NULL;

-- ===== system.permit-management.permit-issuers (H_PermitIssuers) =====
DROP VIEW IF EXISTS Vi_SPC_PermitIssuerListSummary;
CREATE OR REPLACE VIEW Vi_SPC_PermitIssuerListSummary AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS EntityTitle
FROM H_PermitIssuers m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_PermitIssuerProfile;
CREATE OR REPLACE VIEW Vi_SPC_PermitIssuerProfile AS
SELECT
m.Id,
m.EntityId,
m.RecordKey,
m.CreatedAt_UTC,
m.CreatedBy,
m.ModifiedAt_UTC,
m.ModifiedBy,
m.RecordDeleted,
  h0.Title AS EntityTitle
FROM H_PermitIssuers m
  LEFT JOIN H_AAA_EntityProfile h0 ON h0.Id = m.EntityId
WHERE m.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_PermitIssuerPermitTypeIssuers;
CREATE OR REPLACE VIEW Vi_SPC_PermitIssuerPermitTypeIssuers AS
SELECT
j.Id,
j.PermitIssuerId,
j.PermitTypeId,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h0e.Title AS PermitIssuerTitle,
  h1.Title AS PermitTypeTitle
FROM H_PermitTypeIssuers j
  LEFT JOIN H_PermitIssuers h0 ON h0.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h0e ON h0e.Id = h0.EntityId
  LEFT JOIN H_PermitTypes h1 ON h1.Id = j.PermitTypeId
WHERE j.RecordDeleted IS NULL;

DROP VIEW IF EXISTS Vi_SPC_PermitIssuerPermits;
CREATE OR REPLACE VIEW Vi_SPC_PermitIssuerPermits AS
SELECT
j.Id,
j.HUBId,
j.DistributorId,
j.CVOId,
j.VehicleId,
j.DriverId,
j.ActENUM,
j.PermitIssuerId,
j.PermitTypeId,
j.Code,
j.ServiceCategory,
j.IssuedDate_UTC,
j.RecordKey,
j.CreatedAt_UTC,
j.CreatedBy,
j.ModifiedAt_UTC,
j.ModifiedBy,
j.RecordDeleted,
  h2e.Title AS HUBTitle,
  h3e.Title AS CVOTitle,
  h5e.Title AS DistributorTitle,
  h6.Title AS PermitTypeTitle,
  h7e.Title AS PermitIssuerTitle
FROM H_Permits j
  LEFT JOIN H_HUBs h2 ON h2.Id = j.HUBId
  LEFT JOIN H_AAA_EntityProfile h2e ON h2e.Id = h2.EntityId
  LEFT JOIN H_CVOs h3 ON h3.Id = j.CVOId
  LEFT JOIN H_AAA_EntityProfile h3e ON h3e.Id = h3.EntityId
  LEFT JOIN H_Distributors h5 ON h5.Id = j.DistributorId
  LEFT JOIN H_AAA_EntityProfile h5e ON h5e.Id = h5.EntityId
  LEFT JOIN H_PermitTypes h6 ON h6.Id = j.PermitTypeId
  LEFT JOIN H_PermitIssuers h7 ON h7.Id = j.PermitIssuerId
  LEFT JOIN H_AAA_EntityProfile h7e ON h7e.Id = h7.EntityId
WHERE j.RecordDeleted IS NULL;

