-- GENERATED by builder/stages/s4-spc-emit.mjs — DO NOT EDIT.
-- Scope: NTF. Apply each <backend>.spc-views.sql to THAT backend's database (views live with their tables).
-- Field rules: _fsx verbatim · ENUM ints raw (grid maps) · own-FK label hydration · per-relationship counts · overlay enrichment (§8).
-- Idempotent: safe to re-run. Order: helpers → views → authored.


-- ===== header.notifications (H_NotificationQueue) =====
-- Vi_SPC_NotificationTray: authored in spc-view-overlay.json (see "authored views" section).


-- ========== authored views ==========
DROP VIEW IF EXISTS Vi_SPC_NotificationTray;
CREATE OR REPLACE VIEW Vi_SPC_NotificationTray AS SELECT q.Id, q.NotificationRequestId, q.UserId, q.EntityId, ui.RecordKey AS UserRecordKey, ep.RecordKey AS EntityRecordKey, q.ChannelType, q.Status, JSON_UNQUOTE(JSON_EXTRACT(r.Body, '$.subject')) AS Subject, JSON_UNQUOTE(JSON_EXTRACT(r.Body, '$.text')) AS Text, r.Body, q.BroadcastedAt_UTC, q.CreatedAt_UTC, q.RecordDeleted FROM H_NotificationQueue q JOIN H_NotificationRequests r ON r.Id = q.NotificationRequestId AND r.RecordDeleted IS NOT TRUE LEFT JOIN H_AAA_Synced_UserInfo ui ON ui.Id = q.UserId AND ui.RecordDeleted IS NOT TRUE LEFT JOIN H_AAA_Synced_EntityProfile ep ON ep.Id = q.EntityId AND ep.RecordDeleted IS NOT TRUE WHERE q.ChannelType = 1 AND q.Status IN (3, 5) AND q.RecordDeleted IS NOT TRUE;

