-- GENERATED by builder/stages/s4-spc-emit.mjs — DO NOT EDIT.
-- Scope: NTF. Apply each <backend>.spc-views.sql to THAT backend's database (views live with their tables).
-- Field rules: _fsx verbatim · ENUM ints raw (grid maps) · own-FK label hydration · per-relationship counts · overlay enrichment (§8).
-- Idempotent: safe to re-run. Order: helpers → views → authored.


-- ===== header.notifications (H_NotificationQueue) =====
-- Vi_SPC_NotificationTray: authored in spc-view-overlay.json (see "authored views" section).


-- ========== authored views ==========
DROP VIEW IF EXISTS Vi_SPC_NotificationTray;
CREATE OR REPLACE VIEW Vi_SPC_NotificationTray AS SELECT q.Id, q.NotificationRequestId, q.UserId, q.EntityId, q.ChannelType, q.Status, q.Destination_fsx, q.BroadcastedAt_UTC, q.CreatedAt_UTC, q.CreatedBy, q.ModifiedAt_UTC, q.ModifiedBy, q.RecordDeleted, r.HasRule, r.Body, r.UserRecordKey, r.EntityRecordKey, r.RuleRecordKey FROM H_NotificationQueue q JOIN H_NotificationRequests r ON r.Id = q.NotificationRequestId WHERE q.ChannelType = 1 AND r.RecordDeleted IS NULL;

