-- GENERATED by builder/stages/s4-spc-emit.mjs — DO NOT EDIT.
-- Scope: NTF. Apply each <backend>.spc-views.sql to THAT backend's database (views live with their tables).
-- Field rules: _fsx verbatim · ENUM ints raw (grid maps) · own-FK label hydration · per-relationship counts · overlay enrichment (§8).
-- Idempotent: safe to re-run. Order: helpers → views → authored.


-- ===== header.notifications (H_NotificationQueue) =====
-- TODO(tray): Vi_SPC_NotificationTray  (source H_NotificationQueue)

