/* GENERATED by builder/stages/s5-scaffold.mjs — DO NOT EDIT. */
import type { PortalSurface } from "./portal-chrom-surface-registry.config";

export const generatedPortalSurfaces: readonly PortalSurface[] = [
  {
    "id": "dashboard",
    "route": "/dashboard",
    "title": "Dashboard",
    "section": "dashboard",
    "surfaceKind": "dashboard",
    "implementationStatus": "placeholder",
    "backendOwner": "none"
  },
  {
    "id": "definitions.access.entities",
    "route": "/definitions/access/entities",
    "title": "Entities",
    "section": "definitions",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "gd"
  },
  {
    "id": "definitions.access.scenarios",
    "route": "/definitions/access/scenarios",
    "title": "Scenarios",
    "section": "definitions",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "definitions.access.users",
    "route": "/definitions/access/users",
    "title": "Users",
    "section": "definitions",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "none"
  },
  {
    "id": "definitions.customers",
    "route": "/definitions/customers",
    "title": "Customers",
    "section": "definitions",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "definitions.cvos",
    "route": "/definitions/cvos",
    "title": "CVOs",
    "section": "definitions",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "gd"
  },
  {
    "id": "definitions.distributors",
    "route": "/definitions/distributors",
    "title": "Distributors",
    "section": "definitions",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "gd",
    "readModel": "Vi_SPC_DistributorListSummary"
  },
  {
    "id": "definitions.drivers",
    "route": "/definitions/drivers",
    "title": "Drivers",
    "section": "definitions",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "gd",
    "readModel": "Vi_SPC_DriverListSummary"
  },
  {
    "id": "definitions.hubs",
    "route": "/definitions/hubs",
    "title": "HUBs",
    "section": "definitions",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "gd",
    "readModel": "Vi_SPC_HUBListSummary"
  },
  {
    "id": "definitions.requests",
    "route": "/definitions/requests",
    "title": "Requests & Approvals",
    "section": "definitions",
    "surfaceKind": "requests-control-plane",
    "implementationStatus": "contract-only",
    "backendOwner": "gd"
  },
  {
    "id": "definitions.vehicles",
    "route": "/definitions/vehicles",
    "title": "Vehicles",
    "section": "definitions",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "gd",
    "readModel": "Vi_SPC_VehicleListSummary"
  },
  {
    "id": "reports",
    "route": "/reports",
    "title": "Reports",
    "section": "info",
    "surfaceKind": "reports",
    "implementationStatus": "placeholder",
    "backendOwner": "none"
  },
  {
    "id": "system.app-registration.app-clients",
    "route": "/system/app-registration/app-clients",
    "title": "App Clients",
    "section": "system",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "system.app-registration.app-types",
    "route": "/system/app-registration/app-types",
    "title": "App Types",
    "section": "system",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "system.configurations.action-config-bases",
    "route": "/system/configurations/action-config-bases",
    "title": "Action Config Bases",
    "section": "system",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "system.configurations.actor-configs",
    "route": "/system/configurations/actor-configs",
    "title": "Actor Configs",
    "section": "system",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "system.configurations.entity-configs",
    "route": "/system/configurations/entity-configs",
    "title": "Entity Configs",
    "section": "system",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "gd"
  },
  {
    "id": "system.configurations.global-configs",
    "route": "/system/configurations/global-configs",
    "title": "Global Configs",
    "section": "system",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "system.notification-definitions.templates",
    "route": "/system/notification-definitions/templates",
    "title": "Notification Templates",
    "section": "system",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "notification"
  },
  {
    "id": "system.permit-management.permit-issuers",
    "route": "/system/permit-management/permit-issuers",
    "title": "Permit Issuers",
    "section": "system",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "gd"
  },
  {
    "id": "system.permit-management.permit-types",
    "route": "/system/permit-management/permit-types",
    "title": "Permit Types",
    "section": "system",
    "surfaceKind": "compact-catalog",
    "implementationStatus": "contract-only",
    "backendOwner": "gd"
  },
  {
    "id": "transport.batches",
    "route": "/transport/batches",
    "title": "Batches",
    "section": "operational",
    "surfaceKind": "production-workbench",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "transport.deliveries",
    "route": "/transport/deliveries",
    "title": "Deliveries",
    "section": "operational",
    "surfaceKind": "production-workbench",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "transport.dispatch",
    "route": "/transport/dispatch",
    "title": "Dispatch",
    "section": "operational",
    "surfaceKind": "production-workbench",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "transport.mapview",
    "route": "/transport/mapview",
    "title": "MapView",
    "section": "operational",
    "surfaceKind": "production-workbench",
    "implementationStatus": "placeholder",
    "backendOwner": "none"
  },
  {
    "id": "transport.reservation",
    "route": "/transport/reservation",
    "title": "Reservation",
    "section": "operational",
    "surfaceKind": "production-workbench",
    "implementationStatus": "placeholder",
    "backendOwner": "none"
  },
  {
    "id": "transport.rides",
    "route": "/transport/rides",
    "title": "Rides",
    "section": "operational",
    "surfaceKind": "production-workbench",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "transport.setup.contact-locations",
    "route": "/transport/setup/contact-locations",
    "title": "Contact Locations",
    "section": "operational",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "transport.setup.fare-base-inclutions",
    "route": "/transport/setup/fare-base-inclutions",
    "title": "Fare Base Inclutions",
    "section": "operational",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "transport.setup.fare-by-geo-fence",
    "route": "/transport/setup/fare-by-geo-fence",
    "title": "Fare By Geo Fence",
    "section": "operational",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "transport.setup.fare-by-zone",
    "route": "/transport/setup/fare-by-zone",
    "title": "Fare By Zone",
    "section": "operational",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "transport.setup.fare-calculations",
    "route": "/transport/setup/fare-calculations",
    "title": "Fare Calculations",
    "section": "operational",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "transport.setup.geo-fence-bases",
    "route": "/transport/setup/geo-fence-bases",
    "title": "Geo Fence Bases",
    "section": "operational",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "transport.setup.locations",
    "route": "/transport/setup/locations",
    "title": "Locations",
    "section": "operational",
    "surfaceKind": "managed-list",
    "implementationStatus": "contract-only",
    "backendOwner": "core"
  },
  {
    "id": "transport.tracking",
    "route": "/transport/tracking",
    "title": "Tracking",
    "section": "operational",
    "surfaceKind": "production-workbench",
    "implementationStatus": "placeholder",
    "backendOwner": "none"
  }
];
