/* GENERATED by builder/stages/s5-scaffold.mjs — DO NOT EDIT. */
import type { PortalSidebarMenuNode } from "./portal-chrom-sidebar-bottom-menu.config";

export const generatedSidebarSettingsMenu: readonly PortalSidebarMenuNode[] = [
  {
    "title": "System",
    "items": [
      {
        "title": "Configurations",
        "items": [
          {
            "title": "Action Config Bases",
            "href": "/system/configurations/action-config-bases"
          },
          {
            "title": "Actor Configs",
            "href": "/system/configurations/actor-configs"
          },
          {
            "title": "Entity Configs",
            "href": "/system/configurations/entity-configs"
          },
          {
            "title": "Global Configs",
            "href": "/system/configurations/global-configs"
          }
        ]
      },
      {
        "title": "App Registration",
        "items": [
          {
            "title": "App Clients",
            "href": "/system/app-registration/app-clients"
          },
          {
            "title": "App Types",
            "href": "/system/app-registration/app-types"
          }
        ]
      },
      {
        "title": "Notification Definitions",
        "items": [
          {
            "title": "Notification Templates",
            "href": "/system/notification-definitions/templates"
          }
        ]
      },
      {
        "title": "Permit Management",
        "items": [
          {
            "title": "Permit Issuers",
            "href": "/system/permit-management/permit-issuers"
          },
          {
            "title": "Permit Types",
            "href": "/system/permit-management/permit-types"
          }
        ]
      }
    ]
  },
  {
    "title": "Transport",
    "items": [
      {
        "title": "Setup",
        "items": [
          {
            "title": "Contact Locations",
            "href": "/transport/setup/contact-locations"
          },
          {
            "title": "Fare Base Inclutions",
            "href": "/transport/setup/fare-base-inclutions"
          },
          {
            "title": "Fare By Geo Fence",
            "href": "/transport/setup/fare-by-geo-fence"
          },
          {
            "title": "Fare By Zone",
            "href": "/transport/setup/fare-by-zone"
          },
          {
            "title": "Fare Calculations",
            "href": "/transport/setup/fare-calculations"
          },
          {
            "title": "Geo Fence Bases",
            "href": "/transport/setup/geo-fence-bases"
          },
          {
            "title": "Locations",
            "href": "/transport/setup/locations"
          }
        ]
      }
    ]
  },
  {
    "title": "Definitions",
    "items": [
      {
        "title": "Actors",
        "items": [
          {
            "title": "Customers",
            "href": "/definitions/customers"
          },
          {
            "title": "CVOs",
            "href": "/definitions/cvos"
          },
          {
            "title": "Distributors",
            "href": "/definitions/distributors"
          },
          {
            "title": "Drivers",
            "href": "/definitions/drivers"
          },
          {
            "title": "HUBs",
            "href": "/definitions/hubs"
          }
        ]
      },
      {
        "title": "Identity & Access",
        "items": [
          {
            "title": "Entities",
            "href": "/definitions/access/entities"
          },
          {
            "title": "Users",
            "href": "/definitions/access/users"
          }
        ]
      },
      {
        "title": "Requests & Approvals",
        "items": [
          {
            "title": "Requests & Approvals",
            "href": "/definitions/requests"
          }
        ]
      },
      {
        "title": "Facilitators",
        "items": [
          {
            "title": "Vehicles",
            "href": "/definitions/vehicles"
          }
        ]
      }
    ]
  }
];
