/* GENERATED by builder/stages/s5-scaffold.mjs — DO NOT EDIT. */
import { SurfacePage } from "@/src/portal/surface-renderers/surface-page";

export default function Page() {
  return <SurfacePage surfaceId="system.configurations.entity-configs" />;
}
