/*
 * Active palette — derived from
 * `@conitdev/tms-ui-kit/palettes`["indigo"].
 * GENERATED by scripts/sync-palette.mjs. DO NOT EDIT.
 */
export const activePalette = {
  "name": "indigo",
  "portal": {
    "background": "#fcfcfd",
    "foreground": "#1c2024"
  },
  "radixTheme": {
    "accentColor": "indigo",
    "grayColor": "slate",
    "radius": "medium",
    "scaling": "100%"
  }
} as const;
