/*
 * GENERATED by builder/stages/s1-evidence.mjs — DO NOT EDIT.
 * tables evidence re-exports, keyed by source.
 */
import type { TableEvidence } from '../evidence-types';
import { coreTables } from './core.tables';
import { gdTables } from './gd.tables';
import { ntfTables } from './ntf.tables';

export const tablesBySource = {
  core: coreTables,
  gd: gdTables,
  ntf: ntfTables,
} as const;

export const allTables: Record<string, TableEvidence> = {
  ...coreTables,
  ...gdTables,
  ...ntfTables,
};
