/**
 * sync-palette — resolve the active palette and emit portal artifacts.
 *
 * The kit (`@conitdev/tms-ui-kit`) is the single source of truth for
 * every palette. This script reads the resolved palette via
 * `@conitdev/tms-ui-kit/palettes` and writes three small derived
 * artifacts into the portal so that:
 *
 *   1. `app/globals.css` can `@import` the kit's full compiled bundle
 *      (Tailwind v4 compile of the kit's source — `:root` vars + every
 *      utility class kit components reference + kit component CSS).
 *      Loaded globally so any route can render kit components without
 *      per-layout CSS plumbing.
 *
 *   2. `app/globals.css` can paint `body { background; color }` from
 *      the kit's portal-chrome tokens, which match the active palette.
 *
 *   3. `app/layout.tsx` can configure `<Theme accentColor=... />`
 *      from the kit's `radixTheme` block.
 *
 * Outputs (under `src/config/`):
 *   - `active-palette.ts`  — `{name, portal, radixTheme}` for app/layout.tsx
 * Palette resolution order (highest to lowest):
 *   1. CLI arg:                  `node scripts/sync-palette.mjs yellow`
 *   2. Env var:                  `PORTAL_UI_PALETTE=yellow npm run dev`
 *   3. Default:                  indigo
 *
 * Governance reference:
 *   DP_Library_UI-Kit/docs/architecture/responsive-primitives.md
 */
import nextEnv from '@next/env';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const { loadEnvConfig } = nextEnv;
const projectDir = process.cwd();

loadEnvConfig(projectDir);

const SUPPORTED_PALETTES = ['indigo', 'yellow', 'orange'];

function resolvePaletteName() {
  const override = process.argv[2]?.trim().toLowerCase();
  const fromEnv = (
    process.env.PORTAL_UI_PALETTE ?? process.env.PORTAL_PALETTE
  )?.trim().toLowerCase();
  const name = override || (fromEnv === 'yello' ? 'yellow' : fromEnv) || 'indigo';

  if (!SUPPORTED_PALETTES.includes(name)) {
    throw new Error(
      `Unsupported PORTAL_UI_PALETTE "${name}". Expected one of: ${SUPPORTED_PALETTES.join(', ')}`,
    );
  }

  return name;
}

async function main() {
  const paletteName = resolvePaletteName();

  // Dynamic import — the kit's palettes subpath is ESM-only
  // (its `exports` map declares only an `import` condition).
  const { palettes } = await import('@conitdev/tms-ui-kit/palettes');
  const active = palettes[paletteName];

  const configDir = path.join(projectDir, 'src', 'config');
  await mkdir(configDir, { recursive: true });

  const activePaletteTs = `/*
 * Active palette — derived from
 * \`@conitdev/tms-ui-kit/palettes\`[${JSON.stringify(paletteName)}].
 * GENERATED by scripts/sync-palette.mjs. DO NOT EDIT.
 */
export const activePalette = ${JSON.stringify(
    {
      name: active.paletteName,
      portal: active.portal,
      radixTheme: active.radixTheme,
    },
    null,
    2,
  )} as const;
`;
  await writeFile(
    path.join(configDir, 'active-palette.ts'),
    activePaletteTs,
    'utf8',
  );

  console.log(`Synced active palette: ${paletteName}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
