/*
 * GENERATED by builder/stages/s2-classify.mjs — DO NOT EDIT.
 * S2 classification record types. See ruleset mechanical-classification-and-action-model.
 */
export interface EvidenceCitation { source: string; sha256: string | null; }
export interface ClassificationRecord {
  table: string;
  sources: string[];
  master: string | null;
  replicas: string[];
  references: string[];
  evidence: EvidenceCitation[];
  domain: string;
  layer: string | null;
  role: string;
  subjectRole: 'subject' | null;
  pageWorthiness: string;
  writeChannel: 'write' | 'read-only';
  writeMaster: string | null;
  participationScope: string | null;
  confidence: 'high' | 'approved' | 'noise';
  basis: string;
}
