/* GENERATED by builder/stages/s3-catalog.mjs — DO NOT EDIT. Projection of surface-catalog.final. */
export const navigationTree = {
  "header": [
    {
      "name": "Notification Preferences",
      "archetype": "user-pref-modal",
      "key": "header.user-menu.notification-prefs"
    },
    {
      "name": "Notifications",
      "archetype": "notification-tray",
      "key": "header.notifications"
    }
  ],
  "upperSidebar": [
    {
      "name": "Dashboard",
      "route": "/dashboard",
      "node": "direct",
      "key": "dashboard"
    },
    {
      "name": "Tracking",
      "route": "/transport/tracking",
      "node": "end",
      "key": "transport.tracking"
    },
    {
      "name": "MapView",
      "route": "/transport/mapview",
      "node": "end",
      "key": "transport.mapview"
    },
    {
      "name": "Reservation",
      "route": "/transport/reservation",
      "node": "end",
      "key": "transport.reservation"
    },
    {
      "name": "Batches",
      "route": "/transport/batches",
      "node": "direct",
      "key": "transport.batches"
    },
    {
      "name": "Deliveries",
      "route": "/transport/deliveries",
      "node": "direct",
      "key": "transport.deliveries"
    },
    {
      "name": "Dispatch",
      "route": "/transport/dispatch",
      "node": "direct",
      "key": "transport.dispatch"
    },
    {
      "name": "Rides",
      "route": "/transport/rides",
      "node": "direct",
      "key": "transport.rides"
    },
    {
      "name": "Reports",
      "route": "/reports",
      "node": "direct",
      "key": "reports"
    }
  ],
  "lowerSidebar": {
    "System": {
      "Configurations": [
        {
          "name": "Action Config Bases",
          "route": "/system/configurations/action-config-bases",
          "node": "end",
          "key": "system.configurations.action-config-bases",
          "origin": "derived"
        },
        {
          "name": "Actor Configs",
          "route": "/system/configurations/actor-configs",
          "node": "end",
          "key": "system.configurations.actor-configs",
          "origin": "derived"
        },
        {
          "name": "Entity Configs",
          "route": "/system/configurations/entity-configs",
          "node": "end",
          "key": "system.configurations.entity-configs",
          "origin": "derived"
        },
        {
          "name": "Global Configs",
          "route": "/system/configurations/global-configs",
          "node": "end",
          "key": "system.configurations.global-configs",
          "origin": "derived"
        }
      ],
      "App Registration": [
        {
          "name": "App Clients",
          "route": "/system/app-registration/app-clients",
          "node": "end",
          "key": "system.app-registration.app-clients",
          "origin": "derived"
        },
        {
          "name": "App Types",
          "route": "/system/app-registration/app-types",
          "node": "end",
          "key": "system.app-registration.app-types",
          "origin": "derived"
        }
      ],
      "Notification Definitions": [
        {
          "name": "Notification Templates",
          "route": "/system/notification-definitions/templates",
          "node": "end",
          "key": "system.notification-definitions.templates",
          "origin": "derived"
        }
      ],
      "Permit Management": [
        {
          "name": "Permit Issuers",
          "route": "/system/permit-management/permit-issuers",
          "node": "end",
          "key": "system.permit-management.permit-issuers",
          "origin": "derived"
        },
        {
          "name": "Permit Types",
          "route": "/system/permit-management/permit-types",
          "node": "end",
          "key": "system.permit-management.permit-types",
          "origin": "derived"
        }
      ]
    },
    "Transport": {
      "Setup": [
        {
          "name": "Contact Locations",
          "route": "/transport/setup/contact-locations",
          "node": "end",
          "key": "transport.setup.contact-locations",
          "origin": "derived"
        },
        {
          "name": "Fare Base Inclutions",
          "route": "/transport/setup/fare-base-inclutions",
          "node": "end",
          "key": "transport.setup.fare-base-inclutions",
          "origin": "derived"
        },
        {
          "name": "Fare By Geo Fence",
          "route": "/transport/setup/fare-by-geo-fence",
          "node": "end",
          "key": "transport.setup.fare-by-geo-fence",
          "origin": "derived"
        },
        {
          "name": "Fare By Zone",
          "route": "/transport/setup/fare-by-zone",
          "node": "end",
          "key": "transport.setup.fare-by-zone",
          "origin": "derived"
        },
        {
          "name": "Fare Calculations",
          "route": "/transport/setup/fare-calculations",
          "node": "end",
          "key": "transport.setup.fare-calculations",
          "origin": "derived"
        },
        {
          "name": "Geo Fence Bases",
          "route": "/transport/setup/geo-fence-bases",
          "node": "end",
          "key": "transport.setup.geo-fence-bases",
          "origin": "derived"
        },
        {
          "name": "Locations",
          "route": "/transport/setup/locations",
          "node": "end",
          "key": "transport.setup.locations",
          "origin": "derived"
        }
      ]
    },
    "Definitions": {
      "Actors": [
        {
          "name": "Customers",
          "route": "/definitions/customers",
          "node": "end",
          "key": "definitions.customers",
          "origin": "derived"
        },
        {
          "name": "CVOs",
          "route": "/definitions/cvos",
          "node": "end",
          "key": "definitions.cvos",
          "origin": "derived"
        },
        {
          "name": "Distributors",
          "route": "/definitions/distributors",
          "node": "end",
          "key": "definitions.distributors",
          "origin": "derived"
        },
        {
          "name": "Drivers",
          "route": "/definitions/drivers",
          "node": "end",
          "key": "definitions.drivers",
          "origin": "derived"
        },
        {
          "name": "HUBs",
          "route": "/definitions/hubs",
          "node": "end",
          "key": "definitions.hubs",
          "origin": "derived"
        }
      ],
      "Identity & Access": [
        {
          "name": "Entities",
          "route": "/definitions/access/entities",
          "node": "end",
          "key": "definitions.access.entities",
          "origin": "derived"
        },
        {
          "name": "Scenarios",
          "route": "/definitions/access/scenarios",
          "node": "end",
          "key": "definitions.access.scenarios",
          "origin": "derived"
        },
        {
          "name": "Users",
          "route": "/definitions/access/users",
          "node": "end",
          "key": "definitions.access.users",
          "origin": "derived"
        }
      ],
      "Requests & Approvals": [
        {
          "name": "Requests & Approvals",
          "route": "/definitions/requests",
          "node": "end",
          "key": "definitions.requests",
          "origin": "derived"
        }
      ],
      "Facilitators": [
        {
          "name": "Vehicles",
          "route": "/definitions/vehicles",
          "node": "end",
          "key": "definitions.vehicles",
          "origin": "derived"
        }
      ]
    }
  },
  "info": [
    {
      "name": "Help",
      "route": "/info/help"
    },
    {
      "name": "Support",
      "route": "/info/support"
    },
    {
      "name": "Knowledge",
      "route": "/info/knowledge"
    }
  ]
} as const;
