/* GENERATED by builder/stages/s3-catalog.mjs — DO NOT EDIT. Projection of surface-catalog. */
export const navigationTree = {
  "header": [
    {
      "name": "Notifications",
      "archetype": "notification-tray",
      "key": "header.notifications"
    },
    {
      "name": "Notification Preferences",
      "archetype": "user-pref-modal",
      "key": "header.user-menu.notification-prefs"
    }
  ],
  "upperSidebar": [
    {
      "name": "Dashboard",
      "route": "/dashboard",
      "node": "direct"
    },
    {
      "name": "Batches",
      "route": "/production/batches",
      "node": "direct",
      "key": "production.batches"
    },
    {
      "name": "Deliveries",
      "route": "/production/deliveries",
      "node": "direct",
      "key": "production.deliveries"
    },
    {
      "name": "Rides",
      "route": "/production/rides",
      "node": "direct",
      "key": "production.rides"
    },
    {
      "name": "Dispatch",
      "route": "/production/dispatch",
      "node": "direct",
      "key": "production.dispatch"
    }
  ],
  "lowerSidebar": {
    "System": {
      "App Registration": [
        {
          "name": "App Clients",
          "route": "/system/app-registration/app-clients",
          "node": "end",
          "key": "system.app-registration.app-clients"
        },
        {
          "name": "App Types",
          "route": "/system/app-registration/app-types",
          "node": "end",
          "key": "system.app-registration.app-types"
        }
      ],
      "Configurations": [
        {
          "name": "Action Config Bases",
          "route": "/system/configurations/action-config-bases",
          "node": "end",
          "key": "system.configurations.action-config-bases"
        },
        {
          "name": "Actor Configs",
          "route": "/system/configurations/actor-configs",
          "node": "end",
          "key": "system.configurations.actor-configs"
        },
        {
          "name": "Entity Configs",
          "route": "/system/configurations/entity-configs",
          "node": "end",
          "key": "system.configurations.entity-configs"
        },
        {
          "name": "Global Configs",
          "route": "/system/configurations/global-configs",
          "node": "end",
          "key": "system.configurations.global-configs"
        }
      ],
      "Notification Definitions": [
        {
          "name": "Notification Templates",
          "route": "/system/notification-definitions/templates",
          "node": "end",
          "key": "system.notification-definitions.templates"
        }
      ],
      "Permit Management": [
        {
          "name": "Permit Issuers",
          "route": "/system/permit-management/permit-issuers",
          "node": "end",
          "key": "system.permit-management.permit-issuers"
        },
        {
          "name": "Permit Types",
          "route": "/system/permit-management/permit-types",
          "node": "end",
          "key": "system.permit-management.permit-types"
        }
      ]
    },
    "Definitions": {
      "Identity & Access": [
        {
          "name": "Entities",
          "route": "/definitions/access/entities",
          "node": "end",
          "key": "definitions.access.entities"
        },
        {
          "name": "Users",
          "route": "/definitions/access/users",
          "node": "end",
          "key": "definitions.access.users"
        }
      ],
      "Actors": [
        {
          "name": "CVOs",
          "route": "/definitions/cvos",
          "node": "end",
          "key": "definitions.cvos"
        },
        {
          "name": "Distributors",
          "route": "/definitions/distributors",
          "node": "end",
          "key": "definitions.distributors"
        },
        {
          "name": "Drivers",
          "route": "/definitions/drivers",
          "node": "end",
          "key": "definitions.drivers"
        },
        {
          "name": "HUBs",
          "route": "/definitions/hubs",
          "node": "end",
          "key": "definitions.hubs"
        },
        {
          "name": "Customers",
          "route": "/definitions/customers",
          "node": "end",
          "key": "definitions.customers"
        }
      ],
      "Requests & Approvals": [
        {
          "name": "Requests & Approvals",
          "route": "/definitions/requests",
          "node": "end",
          "key": "definitions.requests"
        }
      ],
      "Facilitators": [
        {
          "name": "Vehicles",
          "route": "/definitions/vehicles",
          "node": "end",
          "key": "definitions.vehicles"
        }
      ]
    },
    "Production": {
      "Transport Setup": [
        {
          "name": "Contact Locations",
          "route": "/production/setup/contact-locations",
          "node": "end",
          "key": "production.setup.contact-locations"
        },
        {
          "name": "Fare Base Inclutions",
          "route": "/production/setup/fare-base-inclutions",
          "node": "end",
          "key": "production.setup.fare-base-inclutions"
        },
        {
          "name": "Fare By Geo Fence",
          "route": "/production/setup/fare-by-geo-fence",
          "node": "end",
          "key": "production.setup.fare-by-geo-fence"
        },
        {
          "name": "Fare By Zone",
          "route": "/production/setup/fare-by-zone",
          "node": "end",
          "key": "production.setup.fare-by-zone"
        },
        {
          "name": "Fare Calculations",
          "route": "/production/setup/fare-calculations",
          "node": "end",
          "key": "production.setup.fare-calculations"
        },
        {
          "name": "Geo Fence Bases",
          "route": "/production/setup/geo-fence-bases",
          "node": "end",
          "key": "production.setup.geo-fence-bases"
        },
        {
          "name": "Locations",
          "route": "/production/setup/locations",
          "node": "end",
          "key": "production.setup.locations"
        }
      ]
    }
  },
  "info": [
    {
      "name": "Help",
      "route": "/info/help"
    },
    {
      "name": "Support",
      "route": "/info/support"
    },
    {
      "name": "Knowledge",
      "route": "/info/knowledge"
    }
  ]
} as const;
