/* GENERATED by builder/stages/s3-catalog.mjs — DO NOT EDIT. */
export const surfaceCatalogManifest = {
  "generatedAt": "2026-06-15",
  "totalSurfaces": 36,
  "byFamily": {
    "Production": 15,
    "Definition": 10,
    "Inbox": 1,
    "Info": 1,
    "System": 9
  },
  "byOrigin": {
    "scaffold": 2,
    "derived": 31,
    "manual": 3
  },
  "overlay": {
    "renames": 0,
    "placements": 0,
    "manualMenus": 3
  }
} as const;
