/* GENERATED by builder/stages/s6-forms.mjs — DO NOT EDIT. 28 form contracts. */
export type FormFieldType = 'text' | 'email' | 'mobile' | 'number' | 'date' | 'boolean' | 'select';
export type SurfaceFormFieldPicker = { source: string; valueKey: string; labelKey: string | null; mode: 'lookup' | 'select' };
export type SurfaceFormFieldOption = { value: string; label: string };
export type SurfaceFormField = { name: string; label: string; type: FormFieldType; required: boolean; enumTable?: string; options?: SurfaceFormFieldOption[]; picker?: SurfaceFormFieldPicker };
export type SurfaceFormContract = { surfaceKey: string; primarySubject: string; backend: string | null; fields: SurfaceFormField[] };

export const surfaceFormContracts: Record<string, SurfaceFormContract> = {
  "definitions.access.entities": {
    "surfaceKey": "definitions.access.entities",
    "primarySubject": "H_AAA_EntityProfile",
    "backend": "gd",
    "fields": [
      {
        "name": "PartyCode",
        "label": "Party Code",
        "required": false,
        "type": "text"
      },
      {
        "name": "Title",
        "label": "Title",
        "required": true,
        "type": "text"
      },
      {
        "name": "Address_fsx",
        "label": "Address",
        "required": false,
        "type": "text"
      },
      {
        "name": "City",
        "label": "City",
        "required": false,
        "type": "text"
      },
      {
        "name": "Province",
        "label": "Province",
        "required": false,
        "type": "text"
      },
      {
        "name": "Country",
        "label": "Country",
        "required": false,
        "type": "text"
      },
      {
        "name": "PostalCode_fsx",
        "label": "Postal Code",
        "required": false,
        "type": "text"
      },
      {
        "name": "Phone_fsx",
        "label": "Phone",
        "required": false,
        "type": "mobile"
      },
      {
        "name": "FaxNumber_fsx",
        "label": "Fax Number",
        "required": false,
        "type": "text"
      },
      {
        "name": "Email_fsx",
        "label": "Email",
        "required": false,
        "type": "email"
      },
      {
        "name": "Discriminator",
        "label": "Discriminator",
        "required": false,
        "type": "text"
      }
    ]
  },
  "definitions.access.scenarios": {
    "surfaceKey": "definitions.access.scenarios",
    "primarySubject": "H_AAA_Scenarios",
    "backend": "core",
    "fields": [
      {
        "name": "Description",
        "label": "Description",
        "required": false,
        "type": "text"
      },
      {
        "name": "ActivityClassENUM",
        "label": "Activity Class ENUM",
        "required": true,
        "type": "select",
        "enumTable": "H_ENUM_ActivityClasses"
      },
      {
        "name": "ClientEntityId",
        "label": "Client Entity Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_AAA_EntityProfile",
          "valueKey": "Id",
          "labelKey": "Title",
          "mode": "lookup"
        }
      }
    ]
  },
  "definitions.customers": {
    "surfaceKey": "definitions.customers",
    "primarySubject": "H_TransportCustomers",
    "backend": "core",
    "fields": [
      {
        "name": "EntityId",
        "label": "Entity Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_AAA_Synced_EntityProfile",
          "valueKey": "Id",
          "labelKey": "Title",
          "mode": "lookup"
        }
      },
      {
        "name": "UserId",
        "label": "User Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_AAA_Synced_UserInfo",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      }
    ]
  },
  "definitions.cvos": {
    "surfaceKey": "definitions.cvos",
    "primarySubject": "H_CVOs",
    "backend": "gd",
    "fields": [
      {
        "name": "EntityId",
        "label": "Entity Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_AAA_EntityProfile",
          "valueKey": "Id",
          "labelKey": "Title",
          "mode": "lookup"
        }
      }
    ]
  },
  "definitions.distributors": {
    "surfaceKey": "definitions.distributors",
    "primarySubject": "H_Distributors",
    "backend": "gd",
    "fields": [
      {
        "name": "EntityId",
        "label": "Entity Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_AAA_EntityProfile",
          "valueKey": "Id",
          "labelKey": "Title",
          "mode": "lookup"
        }
      }
    ]
  },
  "definitions.drivers": {
    "surfaceKey": "definitions.drivers",
    "primarySubject": "H_Drivers",
    "backend": "gd",
    "fields": [
      {
        "name": "UserId",
        "label": "User Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_AAA_Synced_UserInfo",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "PersonCVOId",
        "label": "Person CVOId",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_CVOs",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      }
    ]
  },
  "definitions.hubs": {
    "surfaceKey": "definitions.hubs",
    "primarySubject": "H_HUBs",
    "backend": "gd",
    "fields": [
      {
        "name": "EntityId",
        "label": "Entity Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_AAA_EntityProfile",
          "valueKey": "Id",
          "labelKey": "Title",
          "mode": "lookup"
        }
      }
    ]
  },
  "definitions.requests": {
    "surfaceKey": "definitions.requests",
    "primarySubject": "H_RequestStatuses",
    "backend": "gd",
    "fields": [
      {
        "name": "RequestId",
        "label": "Request Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_RequestBases",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "RequesteeUserId",
        "label": "Requestee User Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_AAA_Synced_UserInfo",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "RequesteeEntityId",
        "label": "Requestee Entity Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_AAA_EntityProfile",
          "valueKey": "Id",
          "labelKey": "Title",
          "mode": "lookup"
        }
      },
      {
        "name": "RequesteeActENUM",
        "label": "Requestee Act ENUM",
        "required": false,
        "type": "select",
        "enumTable": "H_ENUM_Actors"
      },
      {
        "name": "Status",
        "label": "Status",
        "required": true,
        "type": "number"
      },
      {
        "name": "StatusReason",
        "label": "Status Reason",
        "required": false,
        "type": "text"
      }
    ]
  },
  "definitions.vehicles": {
    "surfaceKey": "definitions.vehicles",
    "primarySubject": "H_VehicleProfile",
    "backend": "gd",
    "fields": [
      {
        "name": "Plate",
        "label": "Plate",
        "required": false,
        "type": "text"
      },
      {
        "name": "VIN",
        "label": "VIN",
        "required": false,
        "type": "text"
      },
      {
        "name": "Make",
        "label": "Make",
        "required": false,
        "type": "text"
      },
      {
        "name": "Model",
        "label": "Model",
        "required": false,
        "type": "text"
      },
      {
        "name": "Province",
        "label": "Province",
        "required": false,
        "type": "text"
      },
      {
        "name": "Color",
        "label": "Color",
        "required": false,
        "type": "text"
      },
      {
        "name": "Year",
        "label": "Year",
        "required": false,
        "type": "number"
      },
      {
        "name": "TransportCategory",
        "label": "Transport Category",
        "required": false,
        "type": "number"
      },
      {
        "name": "Cargo_Height",
        "label": "Cargo_Height",
        "required": false,
        "type": "number"
      },
      {
        "name": "Cargo_Weight",
        "label": "Cargo_Weight",
        "required": false,
        "type": "number"
      },
      {
        "name": "Cargo_Length",
        "label": "Cargo_Length",
        "required": false,
        "type": "number"
      },
      {
        "name": "Cargo_Width",
        "label": "Cargo_Width",
        "required": false,
        "type": "number"
      },
      {
        "name": "Capacity_Passengers",
        "label": "Capacity_Passengers",
        "required": false,
        "type": "number"
      },
      {
        "name": "Capacity_Luggage",
        "label": "Capacity_Luggage",
        "required": false,
        "type": "number"
      },
      {
        "name": "VehicleType",
        "label": "Vehicle Type",
        "required": false,
        "type": "number"
      }
    ]
  },
  "header.notifications": {
    "surfaceKey": "header.notifications",
    "primarySubject": "H_NotificationQueue",
    "backend": "ntf",
    "fields": [
      {
        "name": "NotificationRequestId",
        "label": "Notification Request Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_NotificationRequests",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "UserId",
        "label": "User Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_AAA_Synced_UserInfo",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "EntityId",
        "label": "Entity Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_AAA_Synced_EntityProfile",
          "valueKey": "Id",
          "labelKey": "Title",
          "mode": "lookup"
        }
      },
      {
        "name": "ChannelType",
        "label": "Channel Type",
        "required": true,
        "type": "number"
      },
      {
        "name": "Destination_fsx",
        "label": "Destination",
        "required": false,
        "type": "text"
      },
      {
        "name": "Status",
        "label": "Status",
        "required": true,
        "type": "number"
      },
      {
        "name": "Reason",
        "label": "Reason",
        "required": false,
        "type": "text"
      },
      {
        "name": "RetryCount",
        "label": "Retry Count",
        "required": false,
        "type": "number"
      },
      {
        "name": "BroadcastedAt_UTC",
        "label": "Broadcasted At",
        "required": false,
        "type": "date"
      }
    ]
  },
  "header.user-menu.notification-prefs": {
    "surfaceKey": "header.user-menu.notification-prefs",
    "primarySubject": "H_UserNotificationSettings",
    "backend": "ntf",
    "fields": [
      {
        "name": "UserId",
        "label": "User Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_AAA_Synced_UserInfo",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "IsEnabledInApp",
        "label": "Is Enabled In App",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "IsEnabledEmail",
        "label": "Is Enabled Email",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "IsEnabledSMS",
        "label": "Is Enabled SMS",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "IsEnabledPhone",
        "label": "Is Enabled Phone",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "IsEnabledWhatsApp",
        "label": "Is Enabled Whats App",
        "required": false,
        "type": "boolean"
      }
    ]
  },
  "system.configurations.action-config-bases": {
    "surfaceKey": "system.configurations.action-config-bases",
    "primarySubject": "H_CFG_ActionConfigBases",
    "backend": "core",
    "fields": [
      {
        "name": "Code",
        "label": "Code",
        "required": true,
        "type": "text"
      },
      {
        "name": "Description",
        "label": "Description",
        "required": true,
        "type": "text"
      }
    ]
  },
  "system.configurations.actor-configs": {
    "surfaceKey": "system.configurations.actor-configs",
    "primarySubject": "H_CFG_ActorConfigs",
    "backend": "core",
    "fields": [
      {
        "name": "EntityId",
        "label": "Entity Id",
        "required": false,
        "type": "number"
      },
      {
        "name": "VehicleId",
        "label": "Vehicle Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_Synced_VehicleProfile",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "UserId",
        "label": "User Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_AAA_Synced_UserInfo",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "ActENUM",
        "label": "Act ENUM",
        "required": true,
        "type": "select",
        "enumTable": "H_ENUM_Actors"
      },
      {
        "name": "ScenarioId",
        "label": "Scenario Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_AAA_EntityScenarios",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "ConfigBaseId",
        "label": "Config Base Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_CFG_ActionConfigBases",
          "valueKey": "Id",
          "labelKey": "Code",
          "mode": "lookup"
        }
      },
      {
        "name": "Value",
        "label": "Value",
        "required": true,
        "type": "text"
      },
      {
        "name": "IsOverridable",
        "label": "Is Overridable",
        "required": true,
        "type": "boolean"
      },
      {
        "name": "Signature",
        "label": "Signature",
        "required": false,
        "type": "text"
      }
    ]
  },
  "system.configurations.entity-configs": {
    "surfaceKey": "system.configurations.entity-configs",
    "primarySubject": "H_CFG_EntityConfigs",
    "backend": "gd",
    "fields": [
      {
        "name": "PermitIssuerId",
        "label": "Permit Issuer Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_PermitIssuers",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "HUBId",
        "label": "HUBId",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_HUBs",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "DistributorId",
        "label": "Distributor Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_Distributors",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "CVOId",
        "label": "CVOId",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_CVOs",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "VehicleId",
        "label": "Vehicle Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_VehicleProfile",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "DriverId",
        "label": "Driver Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_Drivers",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "ActENUM",
        "label": "Act ENUM",
        "required": true,
        "type": "select",
        "enumTable": "H_ENUM_Actors"
      },
      {
        "name": "ScenarioId",
        "label": "Scenario Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_AAA_EntityScenarios",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "ConfigBaseId",
        "label": "Config Base Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_CFG_ActionConfigBases",
          "valueKey": "Id",
          "labelKey": "Code",
          "mode": "lookup"
        }
      },
      {
        "name": "Value",
        "label": "Value",
        "required": true,
        "type": "text"
      },
      {
        "name": "IsOverridable",
        "label": "Is Overridable",
        "required": true,
        "type": "boolean"
      },
      {
        "name": "Signature",
        "label": "Signature",
        "required": false,
        "type": "text"
      }
    ]
  },
  "system.configurations.global-configs": {
    "surfaceKey": "system.configurations.global-configs",
    "primarySubject": "H_CFG_GlobalConfigs",
    "backend": "core",
    "fields": [
      {
        "name": "ConfigBaseId",
        "label": "Config Base Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_CFG_ActionConfigBases",
          "valueKey": "Id",
          "labelKey": "Code",
          "mode": "lookup"
        }
      },
      {
        "name": "Value",
        "label": "Value",
        "required": true,
        "type": "text"
      },
      {
        "name": "IsOverridable",
        "label": "Is Overridable",
        "required": true,
        "type": "boolean"
      },
      {
        "name": "Signature",
        "label": "Signature",
        "required": false,
        "type": "text"
      }
    ]
  },
  "system.notification-definitions.templates": {
    "surfaceKey": "system.notification-definitions.templates",
    "primarySubject": "H_NotificationTemplateSettings",
    "backend": "ntf",
    "fields": [
      {
        "name": "NotificationTypeENUM",
        "label": "Notification Type ENUM",
        "required": true,
        "type": "number"
      },
      {
        "name": "NotificationTemplateENUM",
        "label": "Notification Template ENUM",
        "required": true,
        "type": "select",
        "enumTable": "H_ENUM_NotificationTemplates"
      },
      {
        "name": "NotificationPlatformENUM",
        "label": "Notification Platform ENUM",
        "required": true,
        "type": "select",
        "enumTable": "H_ENUM_NotificationPlatforms"
      },
      {
        "name": "Settings",
        "label": "Settings",
        "required": true,
        "type": "text"
      }
    ]
  },
  "system.permit-management.permit-issuers": {
    "surfaceKey": "system.permit-management.permit-issuers",
    "primarySubject": "H_PermitIssuers",
    "backend": "gd",
    "fields": [
      {
        "name": "EntityId",
        "label": "Entity Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_AAA_EntityProfile",
          "valueKey": "Id",
          "labelKey": "Title",
          "mode": "lookup"
        }
      }
    ]
  },
  "system.permit-management.permit-types": {
    "surfaceKey": "system.permit-management.permit-types",
    "primarySubject": "H_PermitTypes",
    "backend": "gd",
    "fields": [
      {
        "name": "ActENUM",
        "label": "Act ENUM",
        "required": true,
        "type": "select",
        "enumTable": "H_ENUM_Actors"
      },
      {
        "name": "ActivityClassENUM",
        "label": "Activity Class ENUM",
        "required": true,
        "type": "select",
        "enumTable": "H_ENUM_ActivityClasses"
      },
      {
        "name": "Title",
        "label": "Title",
        "required": true,
        "type": "text"
      },
      {
        "name": "AllowedServiceCategories",
        "label": "Allowed Service Categories",
        "required": false,
        "type": "text"
      },
      {
        "name": "Extendable",
        "label": "Extendable",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "ProfileDependant",
        "label": "Profile Dependant",
        "required": false,
        "type": "number"
      }
    ]
  },
  "transport.batches": {
    "surfaceKey": "transport.batches",
    "primarySubject": "H_TransportBatches",
    "backend": "core",
    "fields": [
      {
        "name": "FMS_OId",
        "label": "FMS_OId",
        "required": false,
        "type": "number"
      },
      {
        "name": "DistributorId",
        "label": "Distributor Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_Synced_Distributors",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "TotalFareAtDispatch",
        "label": "Total Fare At Dispatch",
        "required": false,
        "type": "number"
      },
      {
        "name": "FarePortionAmount_CVO",
        "label": "Fare Portion Amount_CVO",
        "required": false,
        "type": "number"
      },
      {
        "name": "FarePortionAmount_Distributor",
        "label": "Fare Portion Amount_Distributor",
        "required": false,
        "type": "number"
      },
      {
        "name": "FarePortionAmount_Driver",
        "label": "Fare Portion Amount_Driver",
        "required": false,
        "type": "number"
      },
      {
        "name": "AllowedDiscountPercent",
        "label": "Allowed Discount Percent",
        "required": false,
        "type": "number"
      },
      {
        "name": "IsEditable",
        "label": "Is Editable",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "IsChargePerItem",
        "label": "Is Charge Per Item",
        "required": false,
        "type": "boolean"
      }
    ]
  },
  "transport.deliveries": {
    "surfaceKey": "transport.deliveries",
    "primarySubject": "H_TransportReqDeliveries",
    "backend": "core",
    "fields": [
      {
        "name": "IsEditable",
        "label": "Is Editable",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "CustomerId",
        "label": "Customer Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_TransportCustomers",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "DistributorId",
        "label": "Distributor Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_Synced_Distributors",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "CVOId",
        "label": "CVOId",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_Synced_CVOs",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "FromContactLocationId",
        "label": "From Contact Location Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_TransportContactLocations",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "ToContactLocationId",
        "label": "To Contact Location Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_TransportContactLocations",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "PickupAfterDateTime",
        "label": "Pickup After Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "PickupAfterDateTime_UTC",
        "label": "Pickup After Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "PickupBeforeDateTime",
        "label": "Pickup Before Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "PickupBeforeDateTime_UTC",
        "label": "Pickup Before Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "DropOffAfterDateTime",
        "label": "Drop Off After Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "DropOffAfterDateTime_UTC",
        "label": "Drop Off After Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "DropOffBeforeDateTime",
        "label": "Drop Off Before Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "DropOffBeforeDateTime_UTC",
        "label": "Drop Off Before Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "VehicleType",
        "label": "Vehicle Type",
        "required": false,
        "type": "number"
      },
      {
        "name": "VehicleProfileSubType",
        "label": "Vehicle Profile Sub Type",
        "required": false,
        "type": "number"
      },
      {
        "name": "ServiceClass",
        "label": "Service Class",
        "required": false,
        "type": "number"
      },
      {
        "name": "ActionOnAbsentReceiver",
        "label": "Action On Absent Receiver",
        "required": true,
        "type": "number"
      },
      {
        "name": "Comments",
        "label": "Comments",
        "required": false,
        "type": "text"
      },
      {
        "name": "FareAtSubmission",
        "label": "Fare At Submission",
        "required": false,
        "type": "number"
      },
      {
        "name": "PromoCode",
        "label": "Promo Code",
        "required": false,
        "type": "text"
      },
      {
        "name": "PaymentCategory",
        "label": "Payment Category",
        "required": false,
        "type": "number"
      },
      {
        "name": "PaymentMethod",
        "label": "Payment Method",
        "required": false,
        "type": "number"
      },
      {
        "name": "PaidAt_UTC",
        "label": "Paid At",
        "required": false,
        "type": "date"
      },
      {
        "name": "Status",
        "label": "Status",
        "required": true,
        "type": "number"
      }
    ]
  },
  "transport.dispatch": {
    "surfaceKey": "transport.dispatch",
    "primarySubject": "H_TransportTransacts",
    "backend": "core",
    "fields": [
      {
        "name": "FMS_OvId",
        "label": "FMS_Ov Id",
        "required": false,
        "type": "number"
      },
      {
        "name": "BatchId",
        "label": "Batch Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_TransportBatches",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "PickupZoneId",
        "label": "Pickup Zone Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "_ZoneBases",
          "valueKey": "Id",
          "labelKey": "Title",
          "mode": "lookup"
        }
      },
      {
        "name": "CVOId",
        "label": "CVOId",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_Synced_CVOs",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "VehicleId",
        "label": "Vehicle Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_Synced_VehicleProfile",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "DriverId",
        "label": "Driver Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_Synced_Drivers",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "CurrentStatus",
        "label": "Current Status",
        "required": true,
        "type": "number"
      },
      {
        "name": "OfferType",
        "label": "Offer Type",
        "required": false,
        "type": "number"
      },
      {
        "name": "PaidTripFare",
        "label": "Paid Trip Fare",
        "required": false,
        "type": "number"
      },
      {
        "name": "PaidAddonFee",
        "label": "Paid Addon Fee",
        "required": false,
        "type": "number"
      },
      {
        "name": "AppliedDiscount",
        "label": "Applied Discount",
        "required": false,
        "type": "number"
      },
      {
        "name": "PaidTip",
        "label": "Paid Tip",
        "required": false,
        "type": "number"
      },
      {
        "name": "PaidToll",
        "label": "Paid Toll",
        "required": false,
        "type": "number"
      },
      {
        "name": "ActualTotalFareAtTripEnd",
        "label": "Actual Total Fare At Trip End",
        "required": false,
        "type": "number"
      },
      {
        "name": "DriverAgreedFareAmount",
        "label": "Driver Agreed Fare Amount",
        "required": false,
        "type": "number"
      },
      {
        "name": "EnforceItemsCreationSequense",
        "label": "Enforce Items Creation Sequense",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "PaymentTransactionNumber",
        "label": "Payment Transaction Number",
        "required": false,
        "type": "text"
      },
      {
        "name": "ExtraData",
        "label": "Extra Data",
        "required": false,
        "type": "text"
      }
    ]
  },
  "transport.rides": {
    "surfaceKey": "transport.rides",
    "primarySubject": "H_TransportReqRides",
    "backend": "core",
    "fields": [
      {
        "name": "IsEditable",
        "label": "Is Editable",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "CustomerId",
        "label": "Customer Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_TransportCustomers",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "DistributorId",
        "label": "Distributor Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_Synced_Distributors",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "CVOId",
        "label": "CVOId",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_Synced_CVOs",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "FromContactLocationId",
        "label": "From Contact Location Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_TransportContactLocations",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "ToContactLocationId",
        "label": "To Contact Location Id",
        "required": false,
        "type": "select",
        "picker": {
          "source": "H_TransportContactLocations",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "PickupAfterDateTime",
        "label": "Pickup After Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "PickupAfterDateTime_UTC",
        "label": "Pickup After Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "PickupBeforeDateTime",
        "label": "Pickup Before Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "PickupBeforeDateTime_UTC",
        "label": "Pickup Before Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "DropOffAfterDateTime",
        "label": "Drop Off After Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "DropOffAfterDateTime_UTC",
        "label": "Drop Off After Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "DropOffBeforeDateTime",
        "label": "Drop Off Before Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "DropOffBeforeDateTime_UTC",
        "label": "Drop Off Before Date Time",
        "required": false,
        "type": "date"
      },
      {
        "name": "VehicleType",
        "label": "Vehicle Type",
        "required": true,
        "type": "number"
      },
      {
        "name": "VehicleProfileSubType",
        "label": "Vehicle Profile Sub Type",
        "required": false,
        "type": "number"
      },
      {
        "name": "ServiceClass",
        "label": "Service Class",
        "required": true,
        "type": "number"
      },
      {
        "name": "ServiceCategory",
        "label": "Service Category",
        "required": true,
        "type": "number"
      },
      {
        "name": "TotalRequiredSeats",
        "label": "Total Required Seats",
        "required": false,
        "type": "number"
      },
      {
        "name": "NumberOfLuggages",
        "label": "Number Of Luggages",
        "required": false,
        "type": "number"
      },
      {
        "name": "FeaturesJSON",
        "label": "Features JSON",
        "required": false,
        "type": "text"
      },
      {
        "name": "Comments",
        "label": "Comments",
        "required": false,
        "type": "text"
      },
      {
        "name": "FareAtSubmission",
        "label": "Fare At Submission",
        "required": false,
        "type": "number"
      },
      {
        "name": "PromoCode",
        "label": "Promo Code",
        "required": false,
        "type": "text"
      },
      {
        "name": "PaymentCategory",
        "label": "Payment Category",
        "required": false,
        "type": "number"
      },
      {
        "name": "PaymentMethod",
        "label": "Payment Method",
        "required": false,
        "type": "number"
      },
      {
        "name": "PaidAt_UTC",
        "label": "Paid At",
        "required": false,
        "type": "date"
      },
      {
        "name": "HubCarrierInfo",
        "label": "Hub Carrier Info",
        "required": false,
        "type": "text"
      },
      {
        "name": "Status",
        "label": "Status",
        "required": true,
        "type": "number"
      }
    ]
  },
  "transport.setup.contact-locations": {
    "surfaceKey": "transport.setup.contact-locations",
    "primarySubject": "H_TransportContactLocations",
    "backend": "core",
    "fields": [
      {
        "name": "ContactId",
        "label": "Contact Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_TransportContactRegistry",
          "valueKey": "Id",
          "labelKey": "Title",
          "mode": "lookup"
        }
      },
      {
        "name": "FavAdrLabel",
        "label": "Fav Adr Label",
        "required": false,
        "type": "text"
      },
      {
        "name": "LocationId",
        "label": "Location Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_TransportLocations",
          "valueKey": "Id",
          "labelKey": "Title",
          "mode": "lookup"
        }
      }
    ]
  },
  "transport.setup.fare-base-inclutions": {
    "surfaceKey": "transport.setup.fare-base-inclutions",
    "primarySubject": "H_TransportFareBaseInclutions",
    "backend": "core",
    "fields": [
      {
        "name": "DistributorId",
        "label": "Distributor Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_Synced_Distributors",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "CVOId",
        "label": "CVOId",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_Synced_CVOs",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "TransportCategory",
        "label": "Transport Category",
        "required": true,
        "type": "number"
      },
      {
        "name": "ServiceCategory",
        "label": "Service Category",
        "required": true,
        "type": "number"
      },
      {
        "name": "VehicleType",
        "label": "Vehicle Type",
        "required": true,
        "type": "number"
      },
      {
        "name": "ServiceClass",
        "label": "Service Class",
        "required": true,
        "type": "number"
      },
      {
        "name": "IncludedSeatCounts",
        "label": "Included Seat Counts",
        "required": false,
        "type": "number"
      },
      {
        "name": "IncludedLuggageCounts",
        "label": "Included Luggage Counts",
        "required": false,
        "type": "number"
      },
      {
        "name": "IncludedParcelCounts",
        "label": "Included Parcel Counts",
        "required": false,
        "type": "number"
      },
      {
        "name": "IncludedWeightKg",
        "label": "Included Weight Kg",
        "required": false,
        "type": "number"
      },
      {
        "name": "IncludedVolumeCubicM",
        "label": "Included Volume Cubic M",
        "required": false,
        "type": "number"
      }
    ]
  },
  "transport.setup.fare-by-geo-fence": {
    "surfaceKey": "transport.setup.fare-by-geo-fence",
    "primarySubject": "H_TransportFareByGeoFence",
    "backend": "core",
    "fields": [
      {
        "name": "TransportFareCalculationId",
        "label": "Transport Fare Calculation Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_TransportFareCalculations",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "SourceGeoFenceBaseId",
        "label": "Source Geo Fence Base Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_TransportGeoFenceBases",
          "valueKey": "Id",
          "labelKey": "Title",
          "mode": "lookup"
        }
      },
      {
        "name": "DestinationGeoFenceBaseId",
        "label": "Destination Geo Fence Base Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_TransportGeoFenceBases",
          "valueKey": "Id",
          "labelKey": "Title",
          "mode": "lookup"
        }
      },
      {
        "name": "BaseFare",
        "label": "Base Fare",
        "required": true,
        "type": "number"
      }
    ]
  },
  "transport.setup.fare-calculations": {
    "surfaceKey": "transport.setup.fare-calculations",
    "primarySubject": "H_TransportFareCalculations",
    "backend": "core",
    "fields": [
      {
        "name": "DistributorId",
        "label": "Distributor Id",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_Synced_Distributors",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "CVOId",
        "label": "CVOId",
        "required": true,
        "type": "select",
        "picker": {
          "source": "H_Synced_CVOs",
          "valueKey": "Id",
          "labelKey": null,
          "mode": "lookup"
        }
      },
      {
        "name": "TransportCategory",
        "label": "Transport Category",
        "required": true,
        "type": "number"
      },
      {
        "name": "ServiceCategory",
        "label": "Service Category",
        "required": true,
        "type": "number"
      },
      {
        "name": "VehicleType",
        "label": "Vehicle Type",
        "required": true,
        "type": "number"
      },
      {
        "name": "ServiceClass",
        "label": "Service Class",
        "required": true,
        "type": "number"
      },
      {
        "name": "CalculationItem",
        "label": "Calculation Item",
        "required": true,
        "type": "number"
      },
      {
        "name": "CalculationType",
        "label": "Calculation Type",
        "required": true,
        "type": "number"
      },
      {
        "name": "CalculateMethod",
        "label": "Calculate Method",
        "required": true,
        "type": "number"
      },
      {
        "name": "CalculationPriority",
        "label": "Calculation Priority",
        "required": false,
        "type": "number"
      },
      {
        "name": "CalculationUnit",
        "label": "Calculation Unit",
        "required": false,
        "type": "number"
      },
      {
        "name": "UnitAmount",
        "label": "Unit Amount",
        "required": false,
        "type": "number"
      },
      {
        "name": "Price",
        "label": "Price",
        "required": false,
        "type": "number"
      },
      {
        "name": "PriceTable",
        "label": "Price Table",
        "required": false,
        "type": "text"
      }
    ]
  },
  "transport.setup.geo-fence-bases": {
    "surfaceKey": "transport.setup.geo-fence-bases",
    "primarySubject": "H_TransportGeoFenceBases",
    "backend": "core",
    "fields": [
      {
        "name": "Code",
        "label": "Code",
        "required": true,
        "type": "text"
      },
      {
        "name": "Title",
        "label": "Title",
        "required": false,
        "type": "text"
      },
      {
        "name": "Coordinates",
        "label": "Coordinates",
        "required": true,
        "type": "text"
      },
      {
        "name": "Order",
        "label": "Order",
        "required": false,
        "type": "number"
      }
    ]
  },
  "transport.setup.locations": {
    "surfaceKey": "transport.setup.locations",
    "primarySubject": "H_TransportLocations",
    "backend": "core",
    "fields": [
      {
        "name": "Title",
        "label": "Title",
        "required": false,
        "type": "text"
      },
      {
        "name": "Latitude",
        "label": "Latitude",
        "required": true,
        "type": "number"
      },
      {
        "name": "Longitude",
        "label": "Longitude",
        "required": true,
        "type": "number"
      },
      {
        "name": "Address",
        "label": "Address",
        "required": true,
        "type": "text"
      },
      {
        "name": "City",
        "label": "City",
        "required": true,
        "type": "text"
      },
      {
        "name": "Province",
        "label": "Province",
        "required": true,
        "type": "text"
      },
      {
        "name": "PostalCode",
        "label": "Postal Code",
        "required": false,
        "type": "text"
      },
      {
        "name": "PlaceId",
        "label": "Place Id",
        "required": true,
        "type": "text"
      },
      {
        "name": "GoogleFullAddress",
        "label": "Google Full Address",
        "required": false,
        "type": "text"
      }
    ]
  }
};
