/*
 * GENERATED by builder/stages/s1-evidence.mjs — DO NOT EDIT.
 * Shared S1 evidence types.
 */

export interface ColumnEvidence {
  name: string;
  rawType: string;
  nullable: boolean;
  default: string | null;
  autoIncrement: boolean;
  onUpdate: string | null;
  ordinal: number;
  raw: string;
}

export interface ForeignKeyEvidence {
  name: string;
  columns: string[];
  referencesTable: string;
  referencesColumns: string[];
  onDelete: string | null;
  onUpdate: string | null;
}

export interface IndexEvidence {
  name: string;
  columns: string[];
  unique: boolean;
}

export interface TableEvidence {
  name: string;
  source: string;
  primaryKey: string[];
  columns: ColumnEvidence[];
  foreignKeys: ForeignKeyEvidence[];
  indexes: IndexEvidence[];
  engine: string | null;
  charset: string | null;
  collation: string | null;
}

export interface ViewEvidence {
  name: string;
  source: string;
  columns: string[];
  definition: string;
}

export interface SourceManifest {
  source: string;
  sourceFile: string;
  database: string | null;
  dialect: string;
  sha256: string;
  capturedAt: string;
  tableCount: number;
  viewCount: number;
}

export interface ApiEndpointEvidence {
  id: number;
  url: string;
  resource: string;
  action: string;
  kind: 'read' | 'write';
}

export interface ApiSourceManifest {
  source: string;
  baseUrl: string;
  sha256: string | null;
  capturedAt: string;
  endpointCount: number;
  status: string;
}

export interface PermissionEvidence {
  raw: string;
  scope: string;
  resource: string;
  action: string;
}

export interface PermissionSourceManifest {
  source: string;
  sourceFile: string;
  sha256: string;
  capturedAt: string;
  permissionCount: number;
}
