/*
 * GENERATED by builder/stages/s1-evidence.mjs — DO NOT EDIT.
 * views evidence re-exports, keyed by source.
 */
import type { ViewEvidence } from '../evidence-types';
import { coreViews } from './core.views';
import { gdViews } from './gd.views';
import { ntfViews } from './ntf.views';

export const viewsBySource = {
  core: coreViews,
  gd: gdViews,
  ntf: ntfViews,
} as const;

export const allViews: Record<string, ViewEvidence> = {
  ...coreViews,
  ...gdViews,
  ...ntfViews,
};
